### ISSUE TITLE
javax.net.ssl.SSLException: Received fatal alert: bad_record_mac

### ISSUE THREAD

**Issue by pawelantczak** [oblac/jodd#110]
Hello.
I'm getting:

``` java
javax.net.ssl.SSLException: Received fatal alert: bad_record_mac
```

when connection to url:

```
https://www.siodemka.com/monitoring-przesylek
```

It seems like a known JRE bug. My server runs recent java.
Is there a chance, that this can be fixed within jodd?

**Comment by ecki** [comment]
BTW: https://bugs.openjdk.java.net/browse/JDK-4615819
It is a known java client bug - it calculates the mac with the actual protcol negotiated not the one offered. This was done for compatibility with some servers. not offering TLS is therefore the solution (and a security risk).

**Comment by igorspasic** [comment]
Thank you for sharing!
