### ISSUE TITLE
Question: how to populate string value to date type from JSP

### ISSUE THREAD

**Issue by shawnye** [oblac/jodd#132]
I have a pojo:with property:
<code>
@DbColumn(sqlType=TimestampSqlType.class)
private Date startTime; 
</code>

then I want to populate value from jsp:(entity is the output parameter)
<code>
&lt;input type="text" name="entity.startTime" id="startTime" /&gt;
</code>

when submit the form , the property 'startTime' can not get the value from JSP
I know   mismatch type.between JSP and property cause that.error

I want to know where can I register sth like TypeConverter to populate without further intervention.
thank you.

**Comment by igorspasic** [comment]
Closing as backlog
