### ISSUE TITLE
Upgrade dependency of javax.servlet-api to 3.1.0 and override setContentLengthLong 

### ISSUE THREAD

**Issue by cnico** [oblac/jodd#189]
Hello, 

I have been trying to use the gzip servlet filter in wildfly and it did not work at first.
You can read the details and explanations of the reason why it did not work through: https://issues.jboss.org/browse/WFLY-4196.

So this point is to make you upgrade the version dependency of servlet-api to 3.1 in jodd with an override of the method setContentLengthLong in order to make the gzip filter works with a 3.1 servlet container. It has very little other impacts on the code than overriding the setContentLengthLong method because of the dependency upgrade.

For information, I did a small override to implement setContentLengthLong in GzipResponseWrapper in my web application and it works successfully. It also works with previous versions of jboss for my use case so there is particular risk at upgrading it to 3.1 version.

**Comment by igorspasic** [comment]
Would you be so kind to check this when possible? Ive tried it on WildFly 8.2, and the content length seems to be correct now. Thank you!

**Comment by cnico** [comment]
Hi,
It is correct.
I will update my application to the latest version once released.

**Comment by igorspasic** [comment]
Awesome, thank you for your time!
