### ISSUE TITLE
BOM pom is empty

### ISSUE THREAD

**Issue by ldez** [oblac/jodd#190]
The generated pom for BOM doesn't have `dependencyManagement` and `dependencies` descriptor.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.jodd</groupId>
  <artifactId>jodd-bom</artifactId>
  <version>3.6.3</version>
  <name>jodd-bom</name>
  <description>Jodd (Bill of Materials)</description>
  <url>http://jodd.org</url>
  <organization>
    <name>Jodd</name>
    <url>http://jodd.org</url>
  </organization>
  <licenses>
    <license>
      <name>The New BSD License</name>
      <url>http://jodd.org/license.html</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>igor</id>
      <name>Igor Spasic</name>
      <email>igor@jodd.org</email>
      <timezone>+1</timezone>
    </developer>
  </developers>
  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/oblac/jodd/issues</url>
  </issueManagement>
  <scm>
    <connection>scm:git:git://github.com/oblac/jodd.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/oblac/jodd.git</developerConnection>
    <url>https://github.com/oblac/jodd</url>
  </scm>
</project>
```

**Comment by igorspasic** [comment]
You are right, this is the content of latest [Maven BOM file](http://central.maven.org/maven2/org/jodd/jodd-bom/3.6.3/jodd-bom-3.6.3.pom)

Which is strange, since when I do the following:

    > gradlew clean build -x test
    > gradlew install

I got the right file in my local repo. I will upload a snapshot today to maven central repo to see what is going on.

**Comment by ldez** [comment]
All version of your BOM on Maven Central have the same problem.
Why you build a jar ? You should publish only a POM.

**Comment by igorspasic** [comment]
Yes, I realized that now :( When I build everything locally, the BOM POM is complete. I assumed this will work when I publish artifacts, too...

And for jar: we are using gradle for building everything and generating POMs. There is an issue with gradle (GRADLE-2427) that required BOM module to be java module - hence we have an empty jar there. I see now there is a new plugin: `maven-publish` that should work better.

I will check what is going on and resolve this ;)

**Comment by igorspasic** [comment]
Figured out - the BOM data was set only in `install` task, but not in the `uploadArchives`.

**Comment by igorspasic** [comment]
Just uploaded the snapshot; BOM seems ok now:

https://oss.sonatype.org/content/repositories/snapshots/org/jodd/jodd-bom/3.6.4-SNAPSHOT/jodd-bom-3.6.4-20150103.165006-1.pom

**Comment by ldez** [comment]
Well done.
Your link works but doesn't appear in Nexus browser (see capture)
![sonatype nexus professional 2015-01-03 18-14-17](https://cloud.githubusercontent.com/assets/5674651/5603110/61bd3c5c-9374-11e4-80b3-88c3311d3efa.png)

**Comment by igorspasic** [comment]
Maybe this is because this is just a snapshot repo? afaik, when we do next full release to central maven repo, everything should be ok. And it should be ok when using snapshot dependency in your maven, i guess ;)
