### ISSUE TITLE
Retrieving Message-ID with sendMail()

### ISSUE THREAD

**Issue by filipeg** [oblac/jodd#197]
The method `SendMailSession.sendMail(Email)` could return the Message-Id of the e-mail sent so that its replies can be identified.
Integrating with `javax.mail.Transport*` might provide this information and complete delivery reports but that may not be quite practical.

**Comment by igorspasic** [comment]
Good idea - actually, it is more simpler, as `MimeMessage` has method `getMessageID` :)
