### ISSUE TITLE
HttpBrowser does not respect port of relative redirects

### ISSUE THREAD

**Issue by mweststrate** [oblac/jodd#198]
I'm running a server locally on `localhost:3000`, which returns on a certain path a relative redirect `Location: /mypath`. The `HttpBrowser` tries to follow this redirect, however the next by `HttpBrowser` is send to to `localhost/mypath` instead of `localhost:3000/mypath`. 

The issue seems to originate in [HttpBrowser](https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpBrowser.java#L127) where the new location is calculated entirely based on the location header without taking into regard the request where this redirect is coming from.

Tried on both jodd 3.6.1 and 3.6.4. If any more reproduction steps are required please let me know.

**Comment by mweststrate** [comment]
Didn't test, but the same issue might hold for the protocol

**Comment by igorspasic** [comment]
Thank you for reporting this! I will check this today and fix it, should be easy:) What do you mean by 'hold for the protocol'?

**Comment by mweststrate** [comment]
Probably a redirect like `Location: /mypath` coming from
https://localhost/about-to-redirect will also fallback to a default, so `
http://localhost/mypath` instead of `https://localhost/mypath`?

**Comment by igorspasic** [comment]
Yes, exactly, will have that in mind! Thank you for your time!

**Comment by slandelle** [comment]
@igorspasic FYI: https://tools.ietf.org/html/rfc7231#section-7.1.2

**Comment by igorspasic** [comment]
Done! Would you be so kind to test how it works now?

Hey @slandelle, thanx for the detailed info - i even put that info in the javadoc :)

**Comment by mweststrate** [comment]
Hi, the redirect now works correctly, thanks for the quick response!

However, an other issue was revealed by this, the headers we set for the initial request are lost for subsequent requests. (we try to emulate a browser so we want to be able to set user agent and accept headers for all next requests). Could this be solved as well or do we need to set up the tests in a different way?

**Comment by mweststrate** [comment]
It seems that a client is not required to automatically include all headers in request that follows a redirect (http://stackoverflow.com/questions/1969709/how-to-forward-headers-on-http-redirect), so maybe a `setDefaultHeader(key,value)` on the `HttpBrowser` might also do the trick? This way it can be made explicit which headers should be send with all requests. 

(P.s, if this should be a separte issue i'll open up another one)

**Comment by igorspasic** [comment]
Cool!, we can do the default header on `HttpBrowser`! In fact, I remember that it was on our todo, but somehow it slipped out :)

**Comment by igorspasic** [comment]
Hey @mweststrate , what to do when provided `request` to `HttpBrowser` contains the same header? For example:

+ Default header: `foo=aaa`
+ Request header: `foo=bbb`

I guess the resolution would be _overwriting_, so request header, if they exist, overwrite default headers.

**Comment by igorspasic** [comment]
btw, i might add also `onRedirect` or `onRequest` callback so you can tweak new requests even more ;) But maybe not now, might be too much ;)

**Comment by mweststrate** [comment]
@igorspasic : I think the request header should overwrite the default header (as its name suggests). I think that is fine for 90% of the cases (some headers might exist multiple times in a request, but if there is also a getDefaultHeaders one can work around that). 

`onRedirect` event would be nice, especially because during testing some additional assertions (e.g.: "I expect 3 directs after login") could be made, but that is only a nice-to-have imho.

**Comment by igorspasic** [comment]
Added default parameter (https://github.com/oblac/jodd/commit/a36f0ec84e9dd4cf6f3b85dffad84b10c7310edb) If you have time, please see if this is working for you :)

I will add events in future, maybe there will be some more events so need to think more.

Thank you!

**Comment by mweststrate** [comment]
Works awesomely for us. Thanks!

One suggestion for improvement: return the HttpBrowser in the set function for easy chainging.

**Comment by igorspasic** [comment]
Absolutely! see: https://github.com/oblac/jodd/commit/4e4c2b32d36beeaec603830e103863cbb4c0dc8c

Happy coding !

**Comment by mweststrate** [comment]
So fast! You're awesome. Will this become a new release?

**Comment by igorspasic** [comment]
:)

We have just released the new release last week, so the new one is scheduled in next 3-4 weeks; but we could publish BETA without a problem, if you need it for your build process?

**Comment by ablok** [comment]
Yes please! :)

**Comment by igorspasic** [comment]
Hey @ablok and @mweststrate, Ive just released 3.6.5-BETA1, should be available on Maven in couple of minutes.

Enjoy!
