### ISSUE TITLE
JsonParserBase.java#L65

### ISSUE THREAD

**Issue by zqq90** [oblac/jodd#203]
https://github.com/oblac/jodd/blob/master/jodd-json/src/main/java/jodd/json/JsonParserBase.java#L65
:bug: 
`targetType`  is an instance of `java.lang.Class`,
 `targetType.getClass().getName()`
->
`targetType.getName()`

**Comment by igorspasic** [comment]
:+1: Thank you for finding this!!!! Fixed: 299f1bfb3391ec3f32a4673f6fd7466744972886
