### ISSUE TITLE
[madvoc] may be we can make `ActionRequest#invoke()` simpler

### ISSUE THREAD

**Issue by zqq90** [oblac/jodd#204]
step 1:  4 type of `ActionWrapper`, `Filter ` , `Interceptor`, and the other two, `ResultRenderWrapper`, `ActionInvoker`.

> `ResultRenderWrapper`  render result
> `ActionInvoker` invoke action method

step 2: just put all of them in one array, with order
~~~~~
wrappers = { filter_1, ..., filter_n, resultRenderWrapper, interceptor_1, ...., interceptor_n,  actionInvoker };
~~~~~

step 3: in this way the `ActionRequest#invoke()` may like this:
~~~~~
public Object invoke() throws Exception {
        return wrappers[wrapperIndex++].invoke(this);
}
~~~~~

Done!

**Comment by igorspasic** [comment]
That can actually work!!!!! Wow
I will try it

**Comment by igorspasic** [comment]
This worked VERY well :) Awesome, the most complicated piece was removed by this simple approach!

Thank you, thank you, thank you!
