### ISSUE TITLE
HtmlStapler breaks HTML or takes very long to load

### ISSUE THREAD

**Issue by ldeseta** [oblac/jodd#205]
Im having very strange behaviour with HtmlStapler. When using it with default setup with a very simple HTML with no JS nor CSS, the webpage takes about 20 seconds to load. When it includes a simple local CSS, the HTML returned is broken (it doesnt return the whole file, resulting in stripped content and an invalid HTML). 

I'm using Jodd 3.6.4, but I tried it with previous versions with no luck.

I've reproduced this situation in: 
* Windows 7 64-bits, Tomcat 8.0.20, JDK 8u40 and JDK 7u76
* Windows XP 32-bits, Tomcat 8.0.12, JDK 8

This error does NOT happen when deploying in Linux (Centos 7 64-bits, Tomcat 8.0.20, JDK 8u40), it works just fine.

Ive created a very small webapp where you can check this issue. It contains 3 HTML with these scenarios: 
* Compiled WAR: https://dl.dropboxusercontent.com/u/159166/jodd-demos.war
* Source code: https://dl.dropboxusercontent.com/u/159166/jodd-demos.zip

**Comment by igorspasic** [comment]
Wow, that is something weird going on! It looks this is Windows related; Im installing the windows box at the moment and will try to figure what is going on.

Thank you for notifying; this type of issues are especially hard to detect :) Stay tuned!

**Comment by igorspasic** [comment]
Would you be so kind to test on Tomcat **7** by any chance? I now remembered that we experienced weird issue with filters and Tomcat 8 that sounds like yours: HTML page is stripped and long response. This test was on Mac, however; still; it might be something with Tomcat version, as version **7** worked for us.

**Comment by ldeseta** [comment]
Ok, I've tested this on Tomcat 7.0.59 with JDK 7u76 and JDK 8u40: the file test1.html loads quickly with no problems. The file test2.html takes 20 seconds to load. The file test3.html loads quickly with no problems.

This still looks like Windows related, but with Tomcat 7 there is a slight different behaviour.

**Comment by igorspasic** [comment]
Ok, thanx, will investigate this (and call ghostbusters :)

**Comment by igorspasic** [comment]
It seems there are two overlapping issues. I am now inspecting the issue with **Tomcat 8**, that I can reproduce;  and it is quite weird one. Stay tuned, working on this...

**Comment by ldeseta** [comment]
Great, let me know if there is anything I can do to help (maybe calling a voodoo witch or something...)

**Comment by igorspasic** [comment]
OK, figured out something: Tomcat 8 realizes that e.g. `test3.html` is a resource, i.e. a file, and sets the content length to file size; while real file size of modified file is greater then that.

**Comment by igorspasic** [comment]
OK, it seems that reseting content length is solving the issue (at least regarding tomcat8, will check windows tomorrow).

Meanwhile - would it be possible for you to test the new jars? I will commit the fix; so you can either:

1. checkout github
2. i can send new jars via email
3. i can publish a snapshot to snapshot repo (which is not maven central, but nexus one)

Just let me know what works best for you!

**Comment by ldeseta** [comment]
If you can just send me the jars thats best.

**Comment by igorspasic** [comment]
The fix is committed. I have the jars. I just need your email :)))

Can you send me your email? Here is how you can contact us:
http://jodd.org/contact.html

Thanx for that voodoo, it helped ;) Let's hope this solves issue on Windows, as well; didn't have time to check it yet :(

**Comment by igorspasic** [comment]
Thank you @ldeseta for testing, everything works now, so I will close the issue.

p.s. also take a look at the 92163dafdcc1ff225ddf732a69e821e53faa4634 :)
