### ISSUE TITLE
forced silent populate

### ISSUE THREAD

**Issue by mbjelac** [oblac/jodd#206]
it would be handy to have a populate method which uses `BeanUtil.setPropertyForcedSilent` so i don't have to do this:

```
props.entrySet()
	 .forEach(entry -> BeanUtil
			 .setPropertyForcedSilent(bean,
									  entry.getKey().toString(),
									  entry.getValue()));
```

**Comment by igorspasic** [comment]
Agree! So that method would simply populate target bean with the props, in forced/silent way. Yeah, will add it today!

**Comment by igorspasic** [comment]
One question - this enhancement is about our [Props](http://jodd.org/doc/props.html) module or when you say "props" you mean Java `Properties`?

**Comment by mbjelac** [comment]
No, just the beans module. `props` is just a variable name, it's a `Map<?, ?>`

**Comment by igorspasic** [comment]
Because, with Java properties/map you can simply use `BeanCopy`:

    BeanCopy.beans(properties, bean).copy();

The `BeanCopy` is designed for this kind of population. However, I will need to add the `forced` flag, so in your case the usage would be:

    BeanCopy.beans(properties, bean).forced(true).copy();

Wdyt?

**Comment by mbjelac** [comment]
if you're referring to `public static BeanCopy beans(java.lang.Object source, java.lang.Object destination)`, then that API is confusing - it implies that you can only copy data from one POJO to another, not from a map to a POJO.
if it works, great, but i would consider making another method which explicitly takes a `Map<?, ?>` as the `source` parameter and a POJO as the `destination`.

**Comment by igorspasic** [comment]
You are right, method name `BeanCopy#beans()` really implies you can copy only POJOs. What about to rename the method (or actually add a new one with different name)? I am asking this as all combinations now works:

+ bean :arrow_right: bean
+ bean :arrow_right: map
+ map :arrow_right: map
+ map :arrow_right: bean

They all works within the same `beans` method.

So maybe we can have methods like:

    BeanCopy.from(zzz).to(xxxx).forced(true).copy()

Or just to rename method to eg `using()`:

    BeanCopy.with(zzz, xxxx).forced(true).copy()

How this sounds? ;)

**Comment by mbjelac** [comment]
since you suggested a fluent API, i'm for the most fluent one: `BeanCopy.from(zzz).to(xxxx).forced(true).copy()`

but i would prefer that method names reflect behaviour.
so if the process is copying from a map to a pojo, that should be visible in method names. it is not visible in the proposed methods `from` and `to`, you have to look at the signature type to figure it out.

here's my proposal:

`BeanCopy.fromProperties(Map<?, ?> properties).toBean(Object bean).forced(true).copy()`
`BeanCopy.fromBean(Object bean).toBean(Object bean).forced(true).copy()`
`BeanCopy.fromBean(Object bean).toProperties(Map<?, ?> properties).forced(true).copy()`

i don't see the requirement to copy from map to map, yes?

**Comment by igorspasic** [comment]
Nice. I would just maybe call `fromMap` instead of `fromProperties`.

> i don't see the requirement to copy from map to map, yes?

It is rare, but can happens. For example, once one user had to join several input maps (properties) into a single target map; he used this.

Great, let me code this and then, if you have time, you can quickly review :)

**Comment by mbjelac** [comment]
> Nice. I would just maybe call fromMap instead of fromProperties.

yes, that's ok.

> if you have time, you can quickly review :)

whoa, i'm just suggesting improvements here! :)
sure, i'll take a look.

**Comment by igorspasic** [comment]
Please see last 3 commits, now the interface is more clear i hope ;)

> whoa, i'm just suggesting improvements here! :)
that's the power of open source :+1:

**Comment by mbjelac** [comment]
reviewed, ok!

**Comment by mbjelac** [comment]
could you make a release? i would prefer to use the public maven repo so i don't have to build and publish locally...

**Comment by igorspasic** [comment]
It is going to be today or tomorrow ;)

**Comment by mbjelac** [comment]
great, thanks!
