### ISSUE TITLE
mail session properties

### ISSUE THREAD

**Issue by omarriaga** [oblac/jodd#208]
let the user add properties to the mail session, sometimes throws exception for email address and i can't change `mail.mime.address.strict` to `false`

**Comment by igorspasic** [comment]
Hi there! Did you try using `[MailSystem](https://github.com/oblac/jodd/blob/master/jodd-mail/src/main/java/jodd/mail/MailSystem.java)` class? Something like:

    JoddMail.mailSystem = new MyMailSystem();

with all your settings; just be sure to call it before using Jodd Mail for the first time.

**Comment by igorspasic** [comment]
Did this worked for you, @omarriaga ?

**Comment by omarriaga** [comment]
yeah normally, i used but didnt work, reading on internet said that this property have to put on session object when im creating it

**Comment by igorspasic** [comment]
Aha, on session object, that is different. Will solve this ;)

**Comment by omarriaga** [comment]
thanks

**Comment by igorspasic** [comment]
Looking at the code, it seems that you can resolve this with code like this:

    SmtpServer smtpServer = SmtpServer
                .create("mail.jodd.org")
                .authenticateWith("user", "password")
                .property("mail.mime.address.strict", "false");

Checkout `property()` and `properties()` methods of `SmtpServer` class. These properties are copied to the session, when it is created.

Let me know if this worked for you :) We can even add a method for you, since this might be something used more often.

**Comment by igorspasic** [comment]
Just added property, so you can do the following:

     SmtpServer smtpServer = SmtpServer
            .create("mail.jodd.org")
            .authenticateWith("user", "password")
            .strictAddress(false);

since this commit.

**Comment by igorspasic** [comment]
... and happy coding ;)
