### ISSUE TITLE
Better support for STARTTLS 

### ISSUE THREAD

**Issue by petromir** [oblac/jodd#210]
It's very difficult to understand how to configure `SmtpSslServer` in order to use `STARTTLS`. 
I managed to find a way by setting the following property **`mail.smtp.socketFactory.class`** to empty string. Мoreover everything else throws exceptions. (e.g. `javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection`). Default value of this property is `javax.net.ssl.SSLSocketFactory`. 

It would be great if you implement more convenient way for setting `STARTTLS` properly and add documentation for it.

**Comment by igorspasic** [comment]
Sure!!

Can you please send me your code, just want to see how did you use it; so we can model the interface in the best way?

**Comment by petromir** [comment]
This how I my code looks like:
```java
SmtpSslServer smtpServer = SmtpSslServer.create("xxx", 587)
   .authenticateWith("xxx", "xxx")
   .property("mail.smtp.socketFactory.class", "");
```
According to this post http://stackoverflow.com/a/414396, `mail.smtp.socketFactory.class` shouldn't be present, and I'm not sure whether you should remove it at all or just set it to empty string.

I see it something like this:
```java
SmtpSslServer smtpServer = SmtpSslServer.create("xxx", 587)
   .authenticateWith("xxx", "xxx").
   .startTlsRequired(true) // Similar to Apache Commons Email
   .setDebug(true) // Should set 'mail.debug' - very useful for debugging.
```

**Comment by igorspasic** [comment]
Just a question - would you mind if TLS is set on by default? Just to keep backward compatibility, so you can use either:

+ `startTlsRequired(false)` or
+ `plaintextOverTLS(true)`

which one would be better in your opinion?

btw, just added `debug` flag ;)

**Comment by petromir** [comment]
After thorough reading of Apache Commons Email sources and Java Mail settings (https://javamail.java.net/nonav/docs/api/com/sun/mail/smtp/package-summary.html) I think that it would be nice if you think about the following stuff:
* `startTlsRequired()` - sets `mail.smtp.starttls.required` which according to Java Mail API means:
_If true, requires the use of the STARTTLS command. If the server doesn't support the STARTTLS command, or the command fails, the connect method will fail. Defaults to false._

I saw that Jodd Mail sets implicitly `mail.smtp.starttls.enable` to true, and I'm not sure if it's good idea do expose only one of the STARTTLS settings.

* `plaintextOverTLS` can do the actual job by just resetting the default value of `mail.smtp.socketFactory.class` to empty string (Jodd Mail uses `javax.net.ssl.SSLSocketFactory` for its `SmtpSslServer`)

Sorry if I have misled you with my previous code proposal.

**Comment by igorspasic** [comment]
No problem, I will just add few of these methods... stay tuned, will send some code soon.

**Comment by igorspasic** [comment]
Did exactly how you proposed it :) Thank you for your time, I really appreciate!

**Comment by petromir** [comment]
Thanks for the fast response. I will be glad if you suggest me some nice Java mock mail server :)

**Comment by igorspasic** [comment]
I am on the same search as well ;) For now, I think I will use [GreenMail](http://www.icegreen.com/greenmail/) in my tests; but havent tried it yet.

**Comment by petromir** [comment]
Thanks.It looks promising. I will try it along with its the competitors.
