### ISSUE TITLE
Jodd MailAddress parse email incorrectly

### ISSUE THREAD

**Issue by nguyennp** [oblac/jodd#211]
MailAddress class drop one character when parse email.
Code:

        String testAddress = "Some One<someone@yahoo.com>";
        MailAddress addr = new MailAddress(testAddress);
        System.out.println("Original:"+testAddress);
        System.out.println("After parsed by MailAddress class:" + addr.toString());

Output:

Original:`Some One<someone@yahoo.com>`
After parsed by MailAddress class:`Some On <someone@yahoo.com>`

One character was lost.

**Comment by igorspasic** [comment]
Ooops. This is kind of embarrassing :)

Sorry for this, its fixed now. Thank you!
