### ISSUE TITLE
Create a generator for JSON Paths

### ISSUE THREAD

**Issue by thiagonuic** [oblac/jodd#212]
Hi,
The JSON serializer looks great! The one thing that is missing from making it perfect would be a generator to create builder classes form JPA Entities. This way it would be possible to include paths in the serializer without dealing with string directly.

**Comment by igorspasic** [comment]
Lets make it perfect than :)))

Just to be 100% sure that I got everything, would you be so kind to drop here few lines in sudo-java, just to outline your idea? Thank you!

**Comment by thiagonuic** [comment]
I don't think I understood, sudo-java? Like an example? =D

**Comment by igorspasic** [comment]
Yeah, exactly:) Like a p**s**e**udo** code example, quick-n-dirty, doesn't have to be syntaxly correct:)

**Comment by thiagonuic** [comment]
Ok, to start, my use case would be this:
I am using jhipster generator to start the project, so basicly spring and jackson. The problem is: jackson serializes everything that have been loaded from hibernate, but that is not always what I want. Since I don't want to create a DTO for every single complex rest endpoint and set all the properties, jodd json comes in as a solution.

When returning a rest endpoint I would do something like this:
```java
Person person = new Person();
return new JsonSerializer
        .include(new PersonPath().getPhonesPath().path())
        .serialize(person);
```

and of course it could go on and on:
```java
Person person = new Person();
return new JsonSerializer
        .include(new PersonPath().getAddressPath().getCityPath().getStatePath().path())
        .serialize(person);
```
This:
```java
new PersonPath().getAddressPath().getCityPath().getStatePath().path()
```
Would create this:
```java
address.city.state
```

**Comment by thiagonuic** [comment]
I even started looking for some code generation libs like: https://github.com/square/javapoet

**Comment by thiagonuic** [comment]
On my use case I would create those paths from @Entity annotaded classes.

**Comment by igorspasic** [comment]
Here is one question. Instead of this:

    Person person = new Person();
    return new JsonSerializer()
        .include(new PersonPath().getAddressPath().getCityPath().getStatePath().path())
        .serialize(person);

can you call this:

    Person person = new Person();
    return new JsonSerializer()
        .serialize(person.getAddress().getCity().getState());

I guess you will probably use more `includes`, right? In other words, you want to _compose_ custom results. In similar case I would go with this approach:

    Map<String, Object> map = new HashMap<>();
    Person person = new Person();
    map.put("state", person.getAddress().getCity().getState());
    map.put("name", person.getName());
    ....
    return new JsonSerializer().serialize(map);

If there is like un-reasonable number of DTOs ;) I personally would not mind to have more of them, and that is great place where Java needs some mixins :)

But your question is more related to beans and getting the property path, just by calling it. This reminds me to our [Methref](http://jodd.org/doc/methref.html) tool, that just returns a method name; let me think a bit if something similar can be done to return the path, so you might call this like:

    Person person = new Person();
    return new JsonSerializer()
        .include(new SomeMagic(person).getAddress().getCity().getState().path())
        .serialize(person);

without the need of any generation.

**Comment by thiagonuic** [comment]
Answering the first question, no, it would not solve the problem because I want the person object the whole tree that I specified. Sometimes it has lists on the path.

The Methref idea is brilliant. That way it would not be necessary to generate code at all. I will have a look at this lib.

**Comment by igorspasic** [comment]
Yeah, Methref gives just one method, but I am exploring option to make Pathref - that gives you a full path :) I see the problem with arrays, cause we can't make a proxy of an array, but hey, it would work for beans... i hope :)

**Comment by igorspasic** [comment]
What do you mean by: 

> Sometimes it has lists on the path.

and how that is a problem?

**Comment by thiagonuic** [comment]
Lists is the @OneToMany on the JPA, like this:

```java
public class Person {
    private List<Phone> phoneList;
}
```

I don't think it would be a problem since JsonSerializer already deals with it.

**Comment by thiagonuic** [comment]
Actually, it would be problem in the path generation, because it would have to return the path os the object type of the list, instead the of List methods.

**Comment by igorspasic** [comment]
See this commit: https://github.com/oblac/jodd/commit/0c5d61774333a24ac63a4153db8e6b832a13e6a5

You can use it like this, for example:

    Pathref<Person> p = Pathref.on(Person.class);
    p.path(p.to().getFriends().get(123).getAddress().getStreet());

This would give you the following string:

    friends[123].address.street

It works _only_ with getters.

Anyway, can you please check if this works for you?

**Comment by igorspasic** [comment]
I am going to mark this as 'backlog' and soon to close it (as we did for all other backlogs). The thing is that source generator is completely separate functionality and module; we don't have any experience on how to make it better then existing ones. It is too broad topic for our resources :)))

**Comment by thiagonuic** [comment]
Looks very promissing! I really like the way it was done. The only thing I was actually thinking how to do is the lists. How to get by reflection the Object from list. For example:

```java
private List<Person> personList
```

Should return the Person not the List. So you can return all objects from the list instead of a especific one. Do you think it can be done?

Thanks for the great work!

**Comment by igorspasic** [comment]
Yeah, that is working ;) Actually, if you have lists, you _must_ specify generic type, otherwise it will fail. See testcase, it shows exactly that use case :smile:

**Comment by thiagonuic** [comment]
I am sorry I did not wrote exactly what I was thinking. I need to return all the objects from the list, not just one. hehe... So insted of returning the list and then call get(0) or get(123), I would need to return all the objects from the list and more levels from there. =)

**Comment by igorspasic** [comment]
Can you show me the example with path that you expect?

**Comment by thiagonuic** [comment]
Sure! =D
```java
Pathref<Person> p = Pathref.on(Person.class);
p.path(p.to().getFriends().getAddress().getStreet());
```

```java
friends.address.street
```

**Comment by thiagonuic** [comment]
Looking at the code you wrote, I believe it would be something like create a new:

```java
protected C createProxyObject(Class<C> target){}
```

Like this:

```java
protected C createProxyObject(Class<List<C>> target)
``´

**Comment by thiagonuic** [comment]
Better yet, insted of list, use Collection, then it would work for Set and List.

**Comment by igorspasic** [comment]
The only way to mimic this is for example:

   ...getFriends().get(-1).getAddress()

Since -1 is invalid, we can skip the '[]' generation. How that looks to you, so to -1 becomes ALL?

**Comment by thiagonuic** [comment]
Sounds good for the first version. When I get home I will try to find a solution as well...

**Comment by igorspasic** [comment]
See: https://github.com/oblac/jodd/commit/50473b08a1ff76f12f16c18455311d9e7d614645

Not bad :)

**Comment by thiagonuic** [comment]
Looks good! Now everthing is strongly typed. Much better! :)

**Comment by thiagonuic** [comment]
Hi, do you have a scheduled date for releasing this feature? Thanks! :)

**Comment by igorspasic** [comment]
Sure, its end of this month: https://github.com/oblac/jodd/milestones

**Comment by thiagonuic** [comment]
Hi, any news on this release? Thanks!

**Comment by igorspasic** [comment]
Just released on Maven - maybe need to wait few hours to propagate ;)

**Comment by thiagonuic** [comment]
Thanks!
