### ISSUE TITLE
return File object from ZipUtil class for 'compress' methods

### ISSUE THREAD

**Issue by jgangemi** [oblac/jodd#213]
it would be great if the 'compress' methods (`zip`, `gzip`, `zlib`) could return a `File` object representing the path of the newly compressed file.

this would save me the work of having to reconstruct the path in the calling code.

**Comment by jgangemi** [comment]
actually, it would be great if all the methods could return a `File` object.

**Comment by igorspasic** [comment]
Yes! Sure! This is a must! Please see: https://github.com/oblac/jodd/commit/dccd50667f303939d1e01bac26a140f55a2dae52. Do you see any other place where we can add it?

Thank you!
