### ISSUE TITLE
 Copyright issue

### ISSUE THREAD

**Issue by dturner** [oblac/jodd#219]
Your readme states that this is an open source project, however, your source files contain ["All rights reserved"](http://desktoppub.about.com/cs/copyrights/a/infringement_2.htm) at the top of each file. 

"All rights reserved" forbids copying, modification and commercial use without permission. Would you consider updating your licensing to something more aligned with open source such as [Apache License 2.0](http://www.apache.org/licenses/LICENSE-2.0)?

**Comment by slandelle** [comment]
Oh, right. Site states "Jodd is free software, released under the terms of the BSD License." but the file header and the license file say otherwise.

**Comment by igorspasic** [comment]
Sorry -  I really, really was not aware of that meaning :((( I though it was cool, thats all :(

Would you not mind if I stay with BSD simplified license, as it is very broad - all I really want is just to have link back to the origin, thats all.

**Comment by igorspasic** [comment]
@slandelle which license file? I believe it is BSD license file?

**Comment by igorspasic** [comment]
[License File](https://github.com/oblac/jodd/blob/master/LICENSE) is BSD license file, afaik :)

**Comment by igorspasic** [comment]
would it be ok if I replace the line with the:

    Jodd is free software, released under the terms of the BSD License. (http://jodd.org)

**Comment by slandelle** [comment]
I'm no lawyer, but I think you're supposed to copy the license header in every file. :)

**Comment by slandelle** [comment]
But you're right, the license file in the 3 clause BSD one.

**Comment by igorspasic** [comment]
And I though it was newer, 2-clause :))) I need to review it. Thanx!

**Comment by slandelle** [comment]
Well, you have 3 clauses ;)

* Redistributions of source code...
* Redistributions in binary form...
* Neither the name of the Jodd team...

**Comment by igorspasic** [comment]
Yeah, I totally made a mess! I am doing a change now :) So long my beauty-sleep.... :)))

**Comment by igorspasic** [comment]
Here is a license template, just for the record: http://opensource.org/licenses/BSD-2-Clause

**Comment by dturner** [comment]
Many thanks for the quick response. BSD-2-Clause is perfect :)

**Comment by igorspasic** [comment]
As of 0cea98ced0330c8bdea8d22c1a21b8322ef1c5db the copyright should be changed, each file contains full license. (i hope all the tests pass;)

Thank you for notifying me this @dturner , if you come to [VoxxedDays Belgrade](https://voxxeddays.com/belgrade15), I will take you with @slandelle to some nice beers :)
