### ISSUE TITLE
JDK9 : Usage of JDK internal libraries by jodd-core

### ISSUE THREAD

**Issue by pmouawad** [oblac/jodd#220]
Hello,
Within Apache JMeter project, we ran jdeps on jmeter and found jodd-core-3.6.4.jar  was using internal libraries from jdk:
jodd-core-3.6.4.jar ->
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/rt.jar
(Full JRE)
   jodd.util.UnsafeUtil (jodd-core-3.6.4.jar)
      -> sun.misc.Unsafe                                    JDK
internal API (rt.jar)

See:
https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool

Thanks for your great library !
Regards
Philippe M.

**Comment by igorspasic** [comment]
Heya, you are very welocome! Yes, you are right, we are using infamous `Unsafe` class - mainly to get inner `char[]` of a `String`.

Does this produces any issue for you? I am thinking, we can 'soften' the dependency and load dynamically the `Unsafe` class, to remove any hard dependency on that class.

How that sounds to you?

**Comment by pmouawad** [comment]
Hello,
AFAIU, you use it to optimize getChars by not creating a new char array and directly accessing memory.

From what I see there  is a big discussion around Unsafe, some say it should absolutely not be used:
http://mail.openjdk.java.net/pipermail/openjfx-dev/2015-April/017028.html
Other find it very useful and think it may become public.

In your case I suppose you benchmarked it and found improvements (even with JDK > 7u40 ?), by the way is there some benchmark somewhere ?

Regarding it's use or not:
- For now it works with last JDK9, but of course it will not work with IBM JVM
- Maybe you should make it optional by providing a System property to enable/disable it , see for example how netty does it:
https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/internal/PlatformDependent.java
https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/internal/PlatformDependent0.java

Regards
Philippe M.

**Comment by igorspasic** [comment]
I was thinking in going into Netty direction, but their `PlatformDependent0` still have reference to `Unsafe`.

The only way to go is to load this class by name and to use reflection on calls. Which now brings us to interesting point: is the reflection + direct memory access faster then just creating new `char[]`?

**Comment by igorspasic** [comment]
We also got email from OpenJDK:

> As part of the preparations for JDK 9, Oracle’s engineers have been analyzing open source projects like yours to understand usage. One area of concern involves identifying compatibility problems, such as reliance on JDK-internal APIs. 

Anyway, we are putting this issue in the backlog; as soon as JDK9 comes out, we will act accordingly, like the rest of the world :)

Thank you!
