### ISSUE TITLE
BeanUtil benchmarks and performance

### ISSUE THREAD

**Issue by dewos** [oblac/jodd#221]
Hello there jodd people!

In my spare time I have built an extreme-minimalistic reflection API with performance in mind, and next a "Apache BeanUtils-alike" tools upon it. While I was benchmarking the whole thing, I came across jodd framework, and I must say that I liked it (I'm totally in for keeping things simple, too :+1: ), maybe in the future I'll make some pull-requests on your project, too :) ).

Anyway, if you're curious, I put (see link below) some benchmarks for Spring BeanWrapper, Apache PropertyUtil, Jodd BeanUtil and others. Jodd comes out pretty well, I think, maybe you should think about exposing the indexed and mapped functions as public, as usually the index and the key are known, and parsing the string in that case is a little bit an overkill.

See you, and congrats for the project.
 
https://github.com/minimalcode-org/minimalcode-beans

**Comment by igorspasic** [comment]
Awesome! We are all for simple things - and like your minimal beans, I will check in more details over the weekend! I will do as you said, i think we even have `getIndexedProperty` method, but let me check how to make it better :) Than you!!!

One more thing - Jodd BeanUtil does also type conversion, so eg if you set `String` into e.g. `Integer` property, it will convert; moreover it understands generics, where possible, e.g. property can be `List<User>` and Jodd will know to create `User`.

**Comment by dewos** [comment]
Thanks @igorspasic for the kindly reply,

Property conversions are my next "goal" for 0.6, but maybe I'll keep them outside the wrapping, I'm a big fan of separation of concerns, and I want to keep MinimalCode project an atomic toolset for other framworks instead than a full-stack framework itself.

Anyway, if you have the opportunity to take a look on my code, any feedback is most welcome.

Thinking about it, in BeanUtilUtil (BeanUtilBean? I cannot tell, things are pretty much chaotic on names :) ) getIndexedProperty and getMappedProperty are now protected, if I remember correctly, maybe exposing them are sufficient for a performance boost.

**Comment by bwzhang2011** [comment]
@igorspasic, any update with such issue ?

**Comment by igorspasic** [comment]
Actually yes - I was thinking in redesigning `BeanUtil`:

https://groups.google.com/forum/#!topic/jodders/72rJMcR438k

And one of the things will be this.

**Comment by bwzhang2011** [comment]
@igorspasic, how about beanUtil improvements going on ? maybe new jodd version should be released compared to last one.

**Comment by igorspasic** [comment]
Added set and get Index property. The BeanUtil has been refactored!

See: 7c63c0a3077730682e5a2c73bbae1825c40a9298
