### ISSUE TITLE
ClassFinder.setExcludedJars

### ISSUE THREAD

**Issue by javamonkey** [oblac/jodd#226]
this method same as setIncludedJars:（version 3.3.6） 

     public void setExcludedJars(String... excludedJars) {
		for (String excludedJar : excludedJars) {
			rulesJars.include(excludedJar);
		}
	}

	public void setIncludedJars(String... includedJars) {
		for (String includedJar : includedJars) {
			rulesJars.include(includedJar);
		}
	}

**Comment by igorspasic** [comment]
Awesome, thank you very very much!
