### ISSUE TITLE
allow passing javax.mail.Session to EmailUtil parseEML

### ISSUE THREAD

**Issue by udlafar** [oblac/jodd#229]
Using default Session is not always good and desired.
For example I need to set property: 
mail.mime.address.strict
to FALSE to be able to parse wrong email addresses without MessagingException thrown from 
MimeMessage.getAddressHeader, InternetAddress.parseHeader and etc.

Without it I have to set System property and it is not a good idea since it can affect whole VM and also sending emails. Of course I can always copy paste EmailUtil ;)

**Comment by igorspasic** [comment]
Totally agree!!! In fact, I think we can now extract those util methods into separate class, that can be used for parsing EMLs.

**Comment by igorspasic** [comment]
Please check new class `EMLParser` - it is dedicated class for parsing EMLs and may be enhanced in the future.

**Comment by udlafar** [comment]
protected Session defaultSession(Properties properties) {
		if (properties == null) {
			properties = System.getProperties();
		}
		return Session.getDefaultInstance(properties, null);
	}

This will not work always - for example if someone created default session before with other properties.
You will get deafault session with other properties in it.
I think it should be:
return Session.getInstance(properties, null);

**Comment by igorspasic** [comment]
You are right, fixed: 359eb549bbb26ed6accdb58418e83c635bbcdd27 Thank you!

Do you think we should use `System.getProperties();` as  default properties?

**Comment by udlafar** [comment]
Hm... using this default session is problematic...
It will ignore properties that you passed to method if someonce created default session before.
So I thinks there should be only one method:

public EMLParser defaultSession() {
	this.session = Session.getDefaultInstance(System.getProperties());
}

because you can never be sure with getDefaultSession(Properties properties) if it used your properties or not. So there is no sense to pass them to method.

**Comment by igorspasic** [comment]
Fixed that too :) Thank you very much for your contribution on this subject!

**Comment by udlafar** [comment]
ok so next bug :PP
you can not set some of properties after you created session

	public EMLParser set(String name, String value) {
		if (session == null) {
			session = createSession(null);
		}
		this.session.getProperties().setProperty(name, value);
		return this;
	}
check constructor
    private Session(Properties props, Authenticator authenticator) {
	this.props = props;
	this.authenticator = authenticator;

	if (Boolean.valueOf(props.getProperty("mail.debug")).booleanValue())
	    debug = true;

debug will not work ;)

**Comment by igorspasic** [comment]
Damn it :)))

How about now: 53fe9398276eab8fb8addf5be5e4aeddec5be39e

Added lazy session creation, throwing exception is session already assigned.

**Comment by udlafar** [comment]
Looks ok :).
You can also consider reusing one EMLParser (and its Session) for different files so we will not create session every time on loadEML(...).parse()
Thx.

**Comment by igorspasic** [comment]
Make sense... Lets refactor again :smile: :smile: :smile:

And you officially won the award for initiating the most refactoring on the issue - thank you!

**Comment by udlafar** [comment]
Sorry. Just really bored in my work today ;).

**Comment by igorspasic** [comment]
;)))) No problem, all comments were very valuable, keep going ;)

**Comment by udlafar** [comment]
Ok so now we have to consider thread safety :P.

**Comment by igorspasic** [comment]
Ok, refactored: 775b5213ee85985c14313a5d9c79a5f6a9375abf

Thread safety for all methods or for `parse()`? Basically Jodd classes are not thread safe (unless they are:) as usually there is some other code around and all that usage is going to be synchronized as user wants....

**Comment by udlafar** [comment]
Thats ok. Thx for good support :).
