### ISSUE TITLE
bug in jodd-mail ReceivedEmail processPart

### ISSUE THREAD

**Issue by udlafar** [oblac/jodd#230]
ok so this is somehow wired bug to explain so i will try refer to sepcification first
lets start with this that `processPart` has series of `IF` statements and is missing last `ELSE`

    Object content = part.getContent();

according to [specification](https://docs.oracle.com/javaee/5/api/javax/mail/Part.html#getContent%28%29) this can be any `Object` if there is `DataHandler` than can 'handle' it...
so there shoud be some `ELSE` like this:

    else {
			String fileName = part.getFileName();
			String contentId = (part instanceof MimePart) ? ((MimePart)part).getContentID() : null;
			String mimeType = EmailUtil.extractMimeType(part.getContentType());

			InputStream is = part.getInputStream();
			FastByteArrayOutputStream fbaos = new FastByteArrayOutputStream();
			StreamUtil.copy(is, fbaos);
			email.addAttachment(fileName, mimeType, contentId, fbaos.toByteArray());
    }

I am not sure if there is also need to check disposition with

    if (disposition != null && disposition.equalsIgnoreCase(Part.ATTACHMENT))

or we can assume that it is always attachment

btw. shouldnt there be is.close() of InputStream in this if (content instanceof InputStream)
after `StreamUtil.copy(is, fbaos);` ?

So... In my case content is apparently a BufferedImage... This can happen because there is single
`javax.activation.CommandMap.getDefaultCommandMap()`
and some other library can register this DataHandler:
content-handler com.sun.xml.internal.messaging.saaj.soap.ImageDataContentHandler
more or less - it is hard to find how it happens...
but it can be any DataHandler and Object so this final ELSE is needed :)

**Comment by igorspasic** [comment]
Sorry for long response, will look at this today...

**Comment by udlafar** [comment]
sure I just extended ReceivedEmail so not a big problem ;)

**Comment by igorspasic** [comment]
You are totally right; committed the final else: 24c2c9a15c8a5c6d5df220ff7d68a509d7fa3401

Regarding the `InputStream` - I usually close them if my code opened it. In the very next commit I added closing in the final else; javadoc does not specify if the stream is opened by this method; but I guess it is logical to expect we opened it.

Regarding the disposition - you mean in the final else, that we just added? What would we do with the read bytes if this is not attachment? Is it a message? Huh:)

**Comment by udlafar** [comment]
I am not sure about that because I do not know that much about mail spec which is a bit complicated...
but only in: if (content instanceof String) { ...
we check if something is ATTACHMENT
and https://docs.oracle.com/javaee/6/api/javax/mail/Part.html#getContent%28%29
says: For example, the object returned for "text/plain" content is usually a String object.
So usually != always ;>. What if it is going to be InputStream or something else for some other mimeType?
Anyway I do not think it can happen very often. Probably only if some other library will mess with DataHandlers or some other case but I havent seen that yet.

But since we are here there is one more thing to consider ^_^ which is connected to previous one. What about images (for example: image/png) that are INLINE? They will usually go to if (content instanceof InputStream) { ...
or the new else {...
Since there is no check for disposition they will be always treated as ATTACHMENT. But I think that images can be also INLINE (probably some other stuff theoretically can be INLINE to). For example some email clients can show images inside message and some other show them as attachments.
But we loose that information...

Anyway I am not sure what you should do in such case:
email.addMessage? or maybe there should be email.addInline?

**Comment by igorspasic** [comment]
I guess `addInline` should be used, if detected... Let me try to do this and let you know ;)))

**Comment by igorspasic** [comment]
(This answer is like terrible late, but better ever then never ;)

Regarding the inlines - i believe that whats `contentId` serves for. Each `if` block while  parsing a message will also try to get the `contentId`, and if it is set, the attachment is inline, otherwise it is a 'normal' attachment. Hence this information is not lost.

I will close this issue now, but lets open new ones if we need ;)

**Comment by udlafar** [comment]
sure
