### ISSUE TITLE
Jerry can not access text node

### ISSUE THREAD

**Issue by wenerme** [oblac/jodd#233]
```
<div>
<span>name</span>value
</div>
```

```
Jerry $ = Jerry.jerry(div);
assert $.children().size() == 1;// No text node
// But $.text(); can get the text node
```

For jQuery
```
// text of a text node
$($(div).contents()[1]).text()
```

**Comment by wenerme** [comment]
Find out `$li.get(0).getLastChild()` this can access the node, but the `children` use `new Jerry` can not hold text node, is this correct ?

**Comment by igorspasic** [comment]
Hi there!

Everything is ok - `Jerry` does not know if you are looking at the snippet of full document, therefore, the root node is _always_ a `DOCUMENT` node.

Hence your call:

    $.children().

is actually getting the children of a root, `DOCUMENT` node, and that is just a `DIV`. So you need to go one more level down to reach the text node you were looking for.

In other words:

		String html = "<div><span>name</span>value</div>";

		Jerry $ = Jerry.jerry(html);

		assertEquals("namevalue", $.text());

		assertEquals(1, $.children().size());

		Node div = $.children().get(0);

		assertEquals("div", div.getNodeName());

		assertEquals(2, div.getChildNodesCount());

		assertEquals("value", div.getChild(1).getNodeValue());
