### ISSUE TITLE
Question: can jodd HttpRequest  do `XMLHttpRequest` ?

### ISSUE THREAD

**Issue by shawnye** [oblac/jodd#234]
The result header may contains:
`X-Requested-With:XMLHttpRequest`

and Request Payload is created(this is the point), for example: 
<pre>
{"orderBy":{"fieldName":"","orderMethod":""},"filterSet":{"orgId":"117000595","userId":"117004622","number":"","cssystem_no":"","fwtype":" and item.receiver in ('117000595')","type":""},"total":0}
</pre>

I do not know to achieve this result, any suggestion would be appreciated.
Thank you !

**Comment by igorspasic** [comment]
This should be rather easy:

request.get("...").header("X-Requested-With","XMLHttpRequest").body("{"orderBy"...);
.sed();
