### ISSUE TITLE
How to parsing json string to special type 

### ISSUE THREAD

**Issue by liniu** [oblac/jodd#235]
Json string such as :
```
{
"openid":100001,
"message":"ok",
"cardList": [
      {"code": "1434079154", "cardId": "c1001"},
      {"code": "1434079155", "cardId": "c1002"}
      ]
}
```
How to map `cardList` path to  `CardItem` defined as :
```
public class CardItem
{
	protected String code;
	protected String cardId;
        //.....
}
```

**Comment by igorspasic** [comment]
You have 2 options:

1. Have a `List<CardItem>` field in your target class.

2. If you don't have specific target class, you can specify the type using the `map` method, as explained [here](http://jodd.org/doc/json/json-parser.html#specifying-target-type)

I would go for the first one, so to parse to specific type :)

Let me know if this works!

**Comment by liniu** [comment]
I don't have  specific target class, so i using map method:
HashMap map = new JsonParser()
				.useAltPaths()
				.map("cardList.values", CardItem.class)
				.parse(str, HashMap.class);
List<CardItem> list = (List<CardItem>) BeanUtil.getPropertySilently(map, "cardList");

it works ,thanks :)

**Comment by igorspasic** [comment]
No problem, enjoy!
