### ISSUE TITLE
If vtor constraint has a field message would be even better

### ISSUE THREAD

**Issue by liniu** [oblac/jodd#240]
If vtor constraint has a field message , so we can define as we needed ,or are there other usage instead?
@Range(min = -2, max = 50, message = "Floor out of range")
 public int floor;

**Comment by igorspasic** [comment]
You are right. For now, we have used generic names based on constraint class, eg:

```
jodd.vtor.constraint.EqualToFieldConstraint=Value is not equal to field 
```

However, it would be better to have the name in annotation as well.

**Comment by igorspasic** [comment]
Just added default messages for all constraints. Niiice!

**Comment by zqq90** [comment]
@igorspasic  how about make is simple by two point:
1. `Max` match `MaxConstraint` and `Foo` match `FooConstraint`,   `@Constraint(MaxConstraint.class)` is not necessary.

2. `ValidationConstraint#validate` returns `String` or `boolean`,   `null` or `true` meants pass,  a NotBlank string meants the message/hint
