### ISSUE TITLE
SSLException results in native crash

### ISSUE THREAD

**Issue by pielambr** [oblac/jodd#242]
Hello all, I am using Jodd 3.6.6 on Android 6.0 now (using Nexus 5). 
No problems before on older API versions, but when I try and run my app on API 23, it results in a native crash.

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/hammerhead/hammerhead:6.0/MRA58K/2256973:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 19386, tid: 19839, name: MinervaService]  >>> com.minervafeed <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x9cfb8fff
    r0 12f3ba80  r1 9cfb9000  r2 ffffffff  r3 ffffffff
    r4 0025be38  r5 708c5680  r6 9cfb9000  r7 ffffffff
    r8 00000000  r9 9f2a6b00  sl ffffffff  fp ffffffff
    ip 00000000  sp 9ce9f3a0  lr a1374463  pc a12512fe  cpsr a00e0030

backtrace:
    #00 pc 007122fe  /data/app/com.minervafeed-1/oat/arm/base.odex (offset 0x535000)
    #01 pc 00835461  /data/app/com.minervafeed-1/oat/arm/base.odex (offset 0x535000)
```
Debugging it gives me this error instead of a native crash;

```
jodd.http.HttpException: Write error: ssl=0x9e7bc580: I/O error during system call, Broken pipe; <--- javax.net.ssl.SSLException: Write error: ssl=0x9e7bc580: I/O error during system call, Broken pipe
```

It fails in HttpBrowser.java, on the line 125 in 3.6.6 

```
this.httpResponse = httpRequest.send();
```

Any response is appreciated.

**Comment by igorspasic** [comment]
Hmmm... It sounds like [this](http://stackoverflow.com/questions/8053824/ssl-broken-pipe)?

**Comment by igorspasic** [comment]
In other words: use Authentication via header instead of CredentielsService?

**Comment by pielambr** [comment]
Authentication happens through cookies, so the Authentication header is not used though...

**Comment by igorspasic** [comment]
The only thing I may suggest is to try to use different way how to configure/use SSL... It looks like internal Android thing to me, according to similar problems.

Would it be possible for you to use different way to configure SSL? I will try to download the Android SDK and try it; however, it will take some time...

**Comment by pielambr** [comment]
I don't know of any configuration possibilities regarding SSL, but the broken pipe thing might point to a request that was closed before and then later on reused...

**Comment by pielambr** [comment]
http://stackoverflow.com/questions/3352424/httpurlconnection-openconnection-fails-second-time This seems to be a similar problem, although it does not seem to result in a native crash

**Comment by igorspasic** [comment]
Any news on this? I am not sure if I can help with this atm...

**Comment by pielambr** [comment]
No news yet, I'm monitoring this closely, I'll let you know if anything changes

**Comment by pielambr** [comment]
Yes, I will close this for now and look some more into the issue and what the root cause is... I'll report back if I know something more...
