### ISSUE TITLE
PetiteRegistry throw NPE

### ISSUE THREAD

**Issue by uin57** [oblac/jodd#243]
jodd 3.6.6

```groovy
class PetiteDemo{
   static TestBean getOne(){
        new TestBean()
    }
}
def pc = new PetiteContainer()
new PetiteRegistry(pc).provider("provider").type(PetiteDemo).method("getOne").args([] as Class[]).register()
```

https://github.com/oblac/jodd/blob/master/jodd-petite/src/main/java/jodd/petite/PetiteRegistry.java#L447
field `methodArgsTypes` should not be `null`

**Comment by igorspasic** [comment]
Thank you for this finding! Nice catch :)

Hope you will still enjoy using Petite! :)
