### ISSUE TITLE
Lagarto mishandles naked ampersands in attributes and text

### ISSUE THREAD

**Issue by fuwjax** [oblac/jodd#245]
Lagarto renders the following: 

    <tag src="http://example.com/example.jpg?child=1&parent=2">Peanut Butter & Jelly</tag>

as

    <tag src="http://example.com/example.jpg?child=1?ent=2">Peanut Butter  Jelly</tag>

instead of

    <tag src="http://example.com/example.jpg?child=1&amp;parent=2">Peanut Butter &amp; Jelly</tag>

**Comment by igorspasic** [comment]
Hey @fuwjax! Thank you for submitting this issue, I am totally ashamed, since `src` is quite common attribute...but somehow it gets overlooked.

Thanx for the fix, it's great - and the tests! Awesome!

Enjoy!
