### ISSUE TITLE
Some threads requested at the same time, jodd.db sometimes occured the issue : jodd.db.oom.DbOomException: Type already registered:

### ISSUE THREAD

**Issue by account4matt** [oblac/jodd#247]
My issue:
jodd.db.oom.DbOomException: Type already registered: class com.xxxxx.model.Activity
	at jodd.db.oom.DbOomManager.registerType(DbOomManager.java:175)
	at jodd.db.oom.DbOomManager.lookupType(DbOomManager.java:134)
	at jodd.db.oom.mapper.DefaultResultSetMapper.resolveDbEntityDescriptors(DefaultResultSetMapper.java:223)
	at jodd.db.oom.mapper.DefaultResultSetMapper.parseObjects(DefaultResultSetMapper.java:330)
	at jodd.db.oom.DbOomQuery.list(DbOomQuery.java:298)
	at jodd.db.oom.DbOomQuery.list(DbOomQuery.java:268)

Jodd.db Code:
/**
	 * Registers just type and entity names. Enough for most usages.
	 */
	public <E> DbEntityDescriptor<E> registerType(Class<E> type) {
		DbEntityDescriptor<E> ded = createDbEntityDescriptor(type);
		DbEntityDescriptor<E> existing = descriptorsMap.put(type, ded);

		if (log.isDebugEnabled()) {
			log.debug("Register " + type.getName() + " as " + ded.getTableName());
		}

		if (existing != null) {
			throw new DbOomException("Type already registered: " + existing.getType());
		}
		existing = entityNamesMap.put(ded.getEntityName(), ded);
		if (existing != null) {
			throw new DbOomException("Name '" + ded.getEntityName() + "' already mapped to an entity: " + existing.getType());
		}
		return ded;
	}

    /**
	 * Lookups {@link DbEntityDescriptor} for some type and registers the type if is new.
	 * <p>
	 * Returns <code>null</code> for core classes from <code>java</code> run-time packages!
	 * Some types are <b>not</b> entities, i.e. domain objects. Instead, primitive entities
	 * are simply mapped to one column. 
	 */
	public <E> DbEntityDescriptor<E> lookupType(Class<E> type) {
		String typeName = type.getName();
		if (StringUtil.startsWithOne(typeName, primitiveEntitiesPrefixes) != -1) {
			return null;
		}
		DbEntityDescriptor<E> ded = descriptorsMap.get(type);
		if (ded == null) {
			ded = registerType(type);
		}
		return ded;
	}

**Comment by account4matt** [comment]
Why can not when the type was existing, just return the ded?

**Comment by igorspasic** [comment]
Yes! Totally good idea - and it is more developer friendly.

Just committed the change! Thankx!!!!!!!!!!!!!!

**Comment by account4matt** [comment]
Thank you!
