### ISSUE TITLE
is HttpBrowser headless browser?

### ISSUE THREAD

**Issue by takaaptech** [oblac/jodd#249]
Hi!

Just want to confirm that HttpBrowser is headless browser?
And does it support to capture screen (take screenshot) ?

Thank so much for such a nice framework!

**Comment by igorspasic** [comment]
Hi there, thanx for stopping buy!

Yes, `HttpBrowser` (despite the name) is actually just a non-UI browser, it just handles the content. No rendering and screen capturing. But you can use:

+ `JEditorPane`
+ [FlyingSaucer](https://github.com/flyingsaucerproject/flyingsaucer)
+ CSSBox

and [more](http://stackoverflow.com/questions/2438201/pure-java-html-viewer-renderer)
