### ISSUE TITLE
Lagarto agressively url decodes href attributes

### ISSUE THREAD

**Issue by slandelle** [oblac/jodd#250]
Hey mate!

I have a new one for you, and in Scala so it's more fun for you ;)

```scala
val htmlContent = """<html>
  <body>
    <a href="/go?to=foobar&index=null" title="Choice 1">link</a>
  </body>
</html>"""

val domBuilder = new LagartoDOMBuilder
val nodeSelector = new NodeSelector(domBuilder.parse(htmlContent))
val selectedNodes = nodeSelector.select("a[title='Choice 1']")

println(selectedNodes.get(0).getAttribute("href"))
```

This prints some weird `/go?to=foobar∈dex=null` instead of the expected `/go?to=foobar&index=null`. There's nothing to decode in there.

**Comment by slandelle** [comment]
You shouldn't consider that any `&` that's not followed by some chars then `;` is a malformed entity.
IMHO, I think you should fall back to treating it as text, all the more in href attribute.

Chrome properly handles this HTML and properly follows the link. If the HTML5 spec really says this is invalid, you should provide a lenient option for supporting it.

**Comment by igorspasic** [comment]
Hey Stephane, hope you are rocking well! :)

Sorry for long response, I believe we have solved this few commits ago (in #245). I have added testcase and it looks as it works: 8472e85a4ad42ae7f548061a819a45fd881930de

I will release new build, so you can use it :)

**Comment by slandelle** [comment]
Hey Igor,

Yeah, so damn swamped, but doing great! What about you? Resting a bit after those last crazy weeks?

You're absolutely right, this is a duplicate. Thanks!

> I will release new build, so you can use it :)

It would be great, thanks!

**Comment by slandelle** [comment]
Duplicate of #245

**Comment by igorspasic** [comment]
Thanx pal!

as you see, pretty swarm as well :(

**Comment by slandelle** [comment]
Any idea when you might be able to release?

**Comment by igorspasic** [comment]
Tomorrow sounds like a great day for that :)

**Comment by slandelle** [comment]
Yeah, Friday is both troll day and release day!

**Comment by slandelle** [comment]
Thanks!

**Comment by igorspasic** [comment]
Well, its 1am, so technically its Saturday;) Released: https://bintray.com/oblac/jodd

**Comment by slandelle** [comment]
What you've deployed on Bintray are snapshots, not releases: https://bintray.com/oblac/jodd/org.jodd%3Ajodd-lagarto/view#files/org/jodd/jodd-lagarto.

And those are not synced with maven central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.jodd%22%20AND%20a%3A%22jodd-lagarto%22

Is this intended? Could you share why you went with Bintray?

I don't really get the point of going with Bintray for Java artifacts.
There are frequent synchronization issues with central (for whatever reason, Bintray is the default repo in sbt) that break builds. And if your artifacts end up only on Bintray, it takes an extra step for your users to fetch them as they have to explicitly declare an additional explicit repository in maven.
I can get the point of Bintray for other kinds of artifacts, such as npm, but I really don't get the point of Bintray for Java artifacts as maven central has always been working great.

**Comment by igorspasic** [comment]
Yes, jodd snapshots are published to Bintray. I push releases to central maven, manually, so I dont release via bintray sync. Of course, if some snapshot is important (like a beta version) i can publish on central as well.

Main reason for bintray is simplicity ;) I just run one gradle task to upload, go to bintray and do one click. So its good for snapshots, i can release often. For now I havent any issue with bintray maven or docker repo, but im not using sync.

Anyway, if you want i can publish this snapshot on central as well ;) 

By the way, snapshots of jodd so far are pretty stable - mainly bug fixes and small changes; so no problem to use it ;)

**Comment by slandelle** [comment]
Ok, I thought you were ready to release 3.6.7. Sorry for the misunderstanding.

Why don't you just set up Travis so you get a CI, and push your snapshots on [Sonatype OSS](https://oss.sonatype.org/index.html)? I can help if you want.

I can't afford to suddenly ask my users to set up the Bintray repo just because of Jodd. I'm not in a hurry (issue was reported from an OSS user, not a paying customer), so I can wait for official 3.6.7 to be released on central. And if really needed, I can still deploy Lagarto in the gatling groupId (which I'd rather not, of course).

**Comment by igorspasic** [comment]
Ah sure, 3.6.7 is ok to go ;)

I have travis, but just running tests. If you know how I can optimize publishing process to maven central, let me know few hints i overlooked ;)

**Comment by slandelle** [comment]
If that's not too much of a hassle for you, could you please release 3.6.7?

I don't have the cycles atm, but I'll try to help with Travis/Sonatype deployments next week. The thing is I've always done it with either maven or sbt, not gradle...

**Comment by igorspasic** [comment]
Sure, 3.6.7. is just released...  still not visible in Maven Central, should be soon :) Sorry I was out of network for 2 days.

No problem... the issue I have with publishing with Maven Central is the fact that I have to publish first to Sonatype and then perform manually some clicking (closing and publishing). But again, I haven't checked if there is better way for this. So no worries, take your time. I checked, there is new gradle plugin for publishing, so I will see...

**Comment by slandelle** [comment]
Thanks a lot!

Our @pdalpra wrote us some scripts that take care of the publishing.
