### ISSUE TITLE
DbOomQuery如何执行批量SQL语句

### ISSUE THREAD

**Issue by xiaofanku** [oblac/jodd#251]
//uid=1;int[] cids={8,9}
	public int[] batchBindChannelForUser(int uid, int[] cids) {
		// TODO Auto-generated method stub
		String SQL="INSERT INTO king_channel_user(uid,cid)VALUES(:uid,:cid)";
		DbSession session = ConnectionInstance.getInstance();
		int ids=0;
		DbOomQuery q=null;
		try {
			q = new DbOomQuery(session, SQL);
			q.setInteger("uid", uid);
			q.setBatch("cid", cids,1);
			ids=q.executeUpdate();
		} catch (DbSqlException e) {
			System.out.println("[CD]get cate exp:" + e.getMessage());
		} finally {
			ConnectionInstance.closeInstance(q, session);
		}
		System.out.println("[jodd]batch:"+ids);
		return null;
	}

**Comment by zqq90** [comment]
同一个 DbSession 就可以 文档的事务那一节
这里提问得用英语 或者 加QQ群250805369

**Comment by xiaofanku** [comment]
我问的是jodd db 如何执行批量sql,跟事务有关系吗？

**Comment by uin57** [comment]
他们又看不懂中文。。
RTFM
RTFS
@oddcb please close this issue. thks

**Comment by igorspasic** [comment]
Closing as suggested ;)
