### ISSUE TITLE
timeout setting does not work for HTTPS requests

### ISSUE THREAD

**Issue by ISInminkler** [oblac/jodd#252]
Currently the logic is not correct in how the timeout is being handled for SSL/HTTPS connections.  Jodd is attempting to open a socket to the remote host and handshake to the host before the timeout is set.  This causes the default timeout to always be used for the handshake (currently it appears it's 2minutes).  

References See: 
Connection is attempted before timeout: https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpRequest.java#L699
Open chains to create: https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpRequest.java#L621
Create causes handshake: https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/net/SocketHttpConnectionProvider.java#L66

Expected: SSL/HTTPS connections respect the .timeout setting when attempting to open the connection and timeout after the specified time.

Possible Solution: HTTPRequest should not be setting the timeout into the sockets itself, the timeout value is being passed with the HTTPRequest to the createHTTPconnection method/factory and should be available at time of socket creation just like the port and host values.  It would be preferable if jodd handled the timeout in an identical fashion.

**Comment by igorspasic** [comment]
Wow, great finding!

I am doing my changes here, so handshake happens _after_ the setting socket parameters.

**Comment by igorspasic** [comment]
Please see the changes :) Would you be so kind to check if this works for you?

**Comment by ISInminkler** [comment]
Do you have a maven artifact available for this somewhere? bintray doesn't seem to give one, and all of my builds need to have the artifact available from a repository.  I also wasn't able to get gradle to build properly as the http stuff threw a whole bunch of security exceptions on the test cases.

**Comment by igorspasic** [comment]
I will publish it today (soon), a new version; it will be on bintray - it does provide maven artifacts.

**Comment by igorspasic** [comment]
Just released, here it is:

https://bintray.com/oblac/jodd

Please find manual on bintray how to include it in your maven build. If you use gradle, its just a matter of adding plugin :)

Hope this will work for you !

**Comment by ISInminkler** [comment]
ah yah, bintray will not work for me, we use artifactory + ivy and it only pulls from maven central, not bintray.

**Comment by igorspasic** [comment]
Sure, 3.6.7. is just released... still not visible in Maven Central, should be soon :) Sorry I was out of network for 2 days.

Let me know how it works for you!

**Comment by ISInminkler** [comment]
@igorspasic - thanks! looks like I can get the artifact now.
