### ISSUE TITLE
Csselly fails to fetch id when it contains a dot

### ISSUE THREAD

**Issue by slandelle** [oblac/jodd#255]
Some people play with fire and use javascript ids such as "foo.bar".

Obviously, when parsing "#foo.bar", Csselly thinks bar is a class.
But Csselly should support escaping: "#foo\.bar" (works in CSS with modern browsers and jQuery).

**Comment by igorspasic** [comment]
Heya!!!

Little CSSelly supports escaping, [see this](http://jodd.org/doc/csselly/#escaping). Would this work for you?

**Comment by slandelle** [comment]
> Shamefully realize his test is broken and Jodd rocks...

**Comment by igorspasic** [comment]
It's Friday :)
