### ISSUE TITLE
Unit Tests for improved test coverage

### ISSUE THREAD

**Issue by mfarid** [oblac/jodd#258]
Hi 

I would like to know if it will be helpful if I contribute certain unit test cases that increase the overall coverage of tests.

Thank you
Farid

**Comment by igorspasic** [comment]
Hey Farid! That would be **VERY** helpful! As you can see on our [github page](https://github.com/oblac/jodd) we are stuck on 72% - and we would love to see it green!

Let me know if you want to do so, just for few notes to take care of.

Thank you!!!!!!!!!!!

**Comment by mfarid** [comment]
I appreciate your prompt response, I will soon update you with the specific module I am starting with. Please let me know if there is something specific to be kept in mind while writing these tests.

**Comment by igorspasic** [comment]
Cool - we have test coverage in the gradle. Please note that for some modules we do have integration tests that are also covered - they are in `testInt` folder.

Thank you!!!

**Comment by igorspasic** [comment]
And of course - for any help, just ping me on the email :)))

**Comment by igorspasic** [comment]
Ok Im going to close this as it was a question.
