### ISSUE TITLE
 the `AutoCloseable` feature

### ISSUE THREAD

**Issue by zqq90** [oblac/jodd#259]
Since we  targeting Java 1.7, how about use the `AutoCloseable` feature, for `DbSession`, `DbQuery` , etc..

**Comment by igorspasic** [comment]
:+1: totally right!

**Comment by igorspasic** [comment]
I have implement this on several DBoom classes.

**Comment by igorspasic** [comment]
I will close it now, don't see at the moment any other place (i might be wrong, so if anyone finds another place for `Autocloseable` please let me know:)
