### ISSUE TITLE
implement has()  and not() in Jerry

### ISSUE THREAD

**Issue by fivesmallq** [oblac/jodd#265]
Before Jerry, I used jsoup. jsoup has a problem. it's ``eq()`` function is not same as jquery.

Jerry is good. but some function is not implement. Can Jerry implement has and not function? It would be cool if it did.

http://www.w3schools.com/jquery/jquery_ref_selectors.asp

https://api.jquery.com/has-selector/
https://api.jquery.com/not-selector/

**Comment by igorspasic** [comment]
Heya! Sorry for terribly long response :(((

Jerry already have `not()` function. I will add 'has()` now.

**Comment by igorspasic** [comment]
Thank you for your patience!

**Comment by fivesmallq** [comment]
e..sorry, I did not express clearly,  i hope  ``has`` and ``not``  function implement in the css selector level, not in java.
May be implemented in the csselly? 
http://jodd.org/doc/csselly/

**Comment by igorspasic** [comment]
Aaa got it now :) Sure, this should go to dear CSSelly :)

**Comment by igorspasic** [comment]
Done!

But please see #301

**Comment by fivesmallq** [comment]
OK, Thank you!
