### ISSUE TITLE
jodd-lagarto crashing in Android Open Source Project

### ISSUE THREAD

**Issue by jeffyhao** [oblac/jodd#272]
This is related to an old bug here: https://github.com/oblac/jodd/issues/241

I'm seeing a failure instantiating a Jerry object due to the lack of a "value" field in the String class. The fix for the previous issue doesn't actually quite work because of the ordering of the static blocks during class initialization of SystemUtil. 

Currently, during SystemUtil.&lt;clinit&gt;, hasUnsafe0 will be called to populate the HAS_UNSAFE field. hasUnsafe0 calls isHostAndroid, which will read the IS_ANDROID field before it is initialized, so it always appears false.

The original fix happens to work because PlatformInternals.UNSAFE would remain null because there was no "address" field in Android's java.nio.Buffer. This has since changed with the transition of Android to OpenJDK.

**Comment by igorspasic** [comment]
Wow. This might be very beautiful Java puzzler! :) The order of execution is like you said:

    SystemUtil.hasUnsafe0
    SystemUtil.isHostAndroid
    SystemUtil.isAndroid0

Hence, `isHostAndroid` (that return IS_ANDROID) is called before `isAndroid0` is setting the `IS_ANDROID` value.

If I put `IS_ANDROID` definition before the `HAS_UNSAFE` android will be detected first, hence the `IS_ANDROID` value will be set ok.

Wow. @jeffyhao this is beautiful catch.
