### ISSUE TITLE
Jerry html(String) bug, doesn't accept empty strings

### ISSUE THREAD

**Issue by ddalcu** [oblac/jodd#279]
If you try to set `.html("")` on a jerry elements, it blows up with a null pointer exception.

     java.lang.NullPointerException: null
	at jodd.lagarto.Scanner.initialize(Scanner.java:31)
	at jodd.lagarto.LagartoParser.initialize(LagartoParser.java:69)
	at jodd.lagarto.LagartoParser.<init>(LagartoParser.java:62)
	at jodd.lagarto.dom.LagartoDOMBuilder.parse(LagartoDOMBuilder.java:119)
	at jodd.jerry.Jerry.append(Jerry.java:802)

**Comment by igorspasic** [comment]
Hey @ddalcu ! Thank you for submitting this fine bug :)

I have just pushed the fix, however, it looks that you are sending the `null` value to the `append` method and not an empty string.

Would you be so kind to check if this fixed your issue? And can you check if you are passing `null` - since in that case we should send NPE.

**Comment by ddalcu** [comment]
Thanks for fixing the html("") issue.

The append issue: I was passing null and it is causing a NPE, empty string does not cause a NPE. Sorry for the confusion.

In jQuery sending null does not cause an error, however in Jerry it ends up requiring an extra "if" statement to make sure your string is not null and not cause a NPE.

**Comment by igorspasic** [comment]
No worries - there was exception with passing the empty string as well :)))

Sure, we will add NPE checks.Thanx!

**Comment by igorspasic** [comment]
btw is the `html(null) == html("")`? I mean when you pass null in your example, jQuery will delete the inner content of the tag, right?

**Comment by ddalcu** [comment]
Correct, in jQuery: passing null is the same as passing a empty string.

**Comment by igorspasic** [comment]
I guess we covered it all
