### ISSUE TITLE
Inam attachments read not working

### ISSUE THREAD

**Issue by fpompermaier** [oblac/jodd#280]
Hi,
I was trying to read the attachments in my mail server through INMAP/INAMPS but it gets 0 bytes if you don't override protected Properties createSessionProperties() in ImapServer and ImapSslServer setting the following:

``` java
ret.setProperty("mail.imap.partialfetch", "false");
```
as specified in https://javamail.java.net/docs/NOTES.txt

**Comment by igorspasic** [comment]
Thanx! Do you thing we should set this property always for Imap servers? I think so, right?

**Comment by igorspasic** [comment]
Great! I have set the default value to false, as you said.

Moreover, we added public `setProperty` methods on Imap servers, so you don't have to override the classes, just to set a property.

**Comment by fpompermaier** [comment]
Ok thanks for the very quick support! Great!
