### ISSUE TITLE
Add helpers to filter email messages

### ISSUE THREAD

**Issue by fpompermaier** [oblac/jodd#281]
In my use case I was trying to fetch email messages received after some date with an IMAPS server (imap-mail.outlook.com). My first attempt was:
``` java
ReceiveMailSession s = ...;
EmailFilter emailFilter = new EmailFilter();
emailFilter.searchTerm = new ReceivedDateTerm(ComparisonTerm.GE, d);
s.receive(emailFilter,null);
```
but this wasn't returning anything.
Creating a **ReceivedDateSearchTerm** (similarly to SentDateSearchTerm depicted at http://www.codejava.net/java-ee/javamail/using-javamail-for-searching-e-mail-messages) I was able to correctly fetch messages.

Why not to add a bunch of common filter implementation (starting at least from **FromFieldSearchTerm**, **SentDateSearchTerm** **ContentSearchTerm** contained in that page plus similar implementation for filtering ReceivedDate and/or Subject)?

**Comment by igorspasic** [comment]
Heya, one question here, which I dont understand:

`EmailFilter` do have for example a `from()` that creates a term for filtering based on from field.

Sure, we can add more, but was `from()` working for you?

    EmailFilter.filter().from("...");

Would you be so kind to check if this is working, and then I can add more implementations :)

**Comment by fpompermaier** [comment]
Hi Igor,
in my tests I didn't have to filter the from field...looking at **FromFieldSearchTerm** example at the link above they do:

```java
package net.codejava.mail;
 
import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.search.SearchTerm;
 
public class FromFieldSearchTerm extends SearchTerm {
    private String fromEmail;
     
    public FromFieldSearchTerm(String fromEmail) {
        this.fromEmail = fromEmail;
    }
     
    @Override
    public boolean match(Message message) {
        try {
            Address[] fromAddress = message.getFrom();
            if (fromAddress != null && fromAddress.length > 0) {
                if (fromAddress[0].toString().contains(fromEmail)) {
                    return true;
                }
            }
        } catch (MessagingException ex) {
            ex.printStackTrace();
        }
         
        return false;
    }
     
}
```

**Comment by igorspasic** [comment]
Sure, I will add more, good idea!

**Comment by igorspasic** [comment]
Added missing filters for dates, message size, and text content...

Enjoy!
