### ISSUE TITLE
Attachment filename  and type not read correctly

### ISSUE THREAD

**Issue by fpompermaier** [oblac/jodd#295]
There are some email that contains the charset in the attachment filename (see https://tools.ietf.org/html/rfc6266). For example:

Content-Disposition: attachment;
                          filename*=utf-8''%e2%82%ac%20rates;

This is a problem of the JDK mail APIs. I've temporary made a workaround in ReceivedEmail:

```java
protected void processPart(ReceivedEmail email, Part part) throws IOException,
			MessagingException {
....
              else if (content instanceof InputStream) {
			String fileName = getFileName(part);
```

and then
```java
// workaround to fix case like filename*=utf-8''XXXX
	private String getFileName(Part part) throws MessagingException, UnsupportedEncodingException {
		if (!(part instanceof MimeBodyPart)) {
			return part.getFileName();
		}
		String filename = null;
		String s = ((MimeBodyPart) part).getHeader("Content-Disposition", null);
		if (s != null) {
			// Parse the header ..
			String[] tmp = s.split(";");
			for (String header : tmp) {
				if (header.contains("filename")) {
					filename = header.split("=")[1].trim();
					String[] innerSplit = filename.split("''");
					if (innerSplit.length > 1) {
						filename = java.net.URLDecoder.decode(innerSplit[1], innerSplit[0]);
					}
					break;
				}
			}
		}
		
		return filename != null ? filename : part.getFileName();
	}
```

**Comment by fpompermaier** [comment]
I discovered that my function should consider also ordinary filename and thus it should strip out double quotes at the beginning and at the end of the filename:

```java
if (header.contains("filename")) {
	filename = header.split("=")[1].trim();
	String[] innerSplit = filename.split("''");
	if (innerSplit.length > 1) {
		filename = java.net.URLDecoder.decode(innerSplit[1], innerSplit[0]);
	}
	if (filename != null && filename.startsWith("\"") && filename.endsWith("\"")) {
		filename = filename.replaceAll("^\"|\"$", "");
	}
	break;
}
```

**Comment by igorspasic** [comment]
Nice, nice nice! Two things:

+ can you use Jodds `StringUtil.split` as it is non regexp
+ the same for the `replaceAll` - we have `split` function that is non-regexp.

I will add them, no worries - but if you have like a 5 min, it would be very helpful if you can try that, as you can test it immediately :)

**Comment by igorspasic** [comment]
And we have http://jodd.org/api/jodd/util/URLDecoder.html :)))

**Comment by fpompermaier** [comment]
I also had to add the following:

```java
if (header.contains("filename")) {
	header = javax.mail.internet.MimeUtility.decodeText(header);
	filename = header.split("=")[1].trim();
```

as a workaround for filenames like 

```
Content-Disposition: attachment; filename="Carta =?utf-8?Q?d'Identita=CC=80.pdf?="
```

**Comment by fpompermaier** [comment]
FYK, this is my final workaround. It works for all the following cases:

-  filename*=utf-8''XXXX and
- filename="Carta =?utf-8?Q?d'Identita=CC=80.pdf?="
- Content-Disposition: attachment;
 filename*0*=iso-8859-15''%63%61%72%74%61%20%69%64%65%6E%74%69%74%E0%20%4D;
 filename*1*=%41%53%53%49%4D%4F%20%50%41%4E%54%49%2E%70%64%66

```java	
private String getFileName(Part part) throws MessagingException, UnsupportedEncodingException {
	if (!(part instanceof MimeBodyPart)) {
		return part.getFileName();
	}
	String contentType = part.getContentType();
	String ret = null;
	try {
		ret = javax.mail.internet.MimeUtility.decodeText(part.getFileName());
	}
	catch (NullPointerException ex) {
		String[] contentId = part.getHeader("Content-ID");
		if (contentId != null && contentId.length > 0) {
			ret = contentId[0];
		}
		if (contentId == null) {
			ret = "no-name";
		}
		ret += "."	+ contentType.substring(contentType.lastIndexOf("/") + 1,contentType.length());
	}
	return ret == null ? "" : ret;
}
```

**Comment by igorspasic** [comment]
Nice! Is the NullPointerException because part can be `null`?

**Comment by igorspasic** [comment]
Also, @fpompermaier  - should we replace other `part.getFileName()` in the same class? It looks like we can.

Thank you for support! I especially liked that we ended with `MimeUtil` - i even think we are using it in Attachment class.

**Comment by fpompermaier** [comment]
Thanks @igorspasic for the support! I don't know wheter we should do the same for other part.getFileName(), for all other ~5k mail I parsed I didn't have other problems. The filename was null in one of my samples: there was an image inside the mail content without the filename or name attribute (I think this can happen when using gmail drag and drop for example).

**Comment by igorspasic** [comment]
Thanx @fpompermaier  a lot! Can you check the commit Ive made - the only difference is that I checked for `null` explicitly rather to catch NPE; just for better performances.
