### ISSUE TITLE
Jodd Mail - multiple mails not displayed

### ISSUE THREAD

**Issue by dlangerenken** [oblac/jodd#302]
I would like to attach multiple 'contents' to my mail and expect to see these different contents in my mail client (thunderbird, gmail, ..)

However, I only see the last email in thunderbird, and no content at all in gmail.

If I look into the source of the mail, I see the following (note the same part 4 ids):
>Received: from my-computer (/ip)
	by default (Some Gateway v4.0)
	with ESMTP ; Fri, 04 Mar 2016 11:36:53 -0800
Date: Fri, 4 Mar 2016 11:36:27 -0800 (PST)
From: sender@address.com
To: receiver@address.com
Message-ID: <123456789.5.123456789@address.com>
Subject: [Action Required] Some title
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_3_1234567890.1234567890"

>------=_Part_3_1512667467.1457120187311
Content-Type: multipart/alternative; 
	boundary="----=_Part_4_1072018543.1457120187311"

>------=_Part_4_1072018543.1457120187311
Content-Type: text/html;charset=UTF-8
Content-Transfer-Encoding: 7bit

><html> blub blub blub</html>
------=_Part_4_1072018543.1457120187311
Content-Type: text/html;charset=UTF-8
Content-Transfer-Encoding: 7bit

><html> Hello world</html>
------=_Part_4_1072018543.1457120187311
Content-Type: text/html;charset=UTF-8
Content-Transfer-Encoding: 7bit

>Just <b>Text</b>
------=_Part_4_1072018543.1457120187311--

>------=_Part_3_1512667467.1457120187311--

This is my code:

        email.addHtml("<html> blub blub blub</html>");
        email.addHtml("<html> Hello world</html>");
        email.addHtml("Just <b>Text</b>");

And my output in Thunderbird is: Just **Text**

Is this default behaviour or am I doing something wrong?

**Comment by igorspasic** [comment]
Hm, looking from the source, it looks like you have valid email with 4 contents.

Now, the problem might be that email clients simply does not show this correctly? This is not a common thing... What I suggest is to e.g. go to gmail or thunderbird and save the content (as EML or text file) and check how it looks like.

For example: http://stackoverflow.com/questions/24787908/multipart-mixed-content-type-ignored

According to [this](http://stackoverflow.com/questions/3902455/smtp-multipart-alternative-vs-multipart-mixed) post, there might be a way that works in gmail.

So I guess each client has it's own way how it deals with this kind of messages... We here can try different combinations and check if some works better.

**Comment by Dalanie** [comment]
Thanks for the quick response.
Both links are interesting, but I thought that jodd mail is abstracting from it.  In my example. the order should not matter as I have the same content type text/html for all three parts. What should I do there instead?

**Comment by igorspasic** [comment]
Yeah, Jodd Mail is abstracting it, just simply the clients are not capable of showing it. I mean, with email you can create some very complex and weird structures :)))

Now, when I said the order, I meant: this:

```
mixed
    alternative
        text
        ...
```

In other words: let me find out what really works in gmail, and then we can proceed with fixing/tuning in Jodd.

**Comment by igorspasic** [comment]
This is simply the behavior of the clients. I just sent an email to Google and it shows only the last message. When I click 'show original' to get the raw format of the message, I get this:

```
Return-Path: <igor.spasic@gmail.com>
Received: from suprasurf.cable.vektor.net ([5.134.107.10])
        by smtp.gmail.com with ESMTPSA id 84sm12306880ljf.33.2016.10.20.06.22.17
        for <igor.spasic@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 20 Oct 2016 06:22:17 -0700 (PDT)
From: igor.spasic@gmail.com
X-Google-Original-From: igor@jodd.org
Date: Thu, 20 Oct 2016 15:22:17 +0200 (CEST)
To: igor.spasic@gmail.com
Message-ID: <1376400422.2.1476969737758@smtp.gmail.com>
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----=_Part_0_828441346.1476969737320"

------=_Part_0_828441346.1476969737320
Content-Type: multipart/alternative; boundary="----=_Part_1_717386707.1476969737326"

------=_Part_1_717386707.1476969737326
Content-Type: text/html;charset=UTF-8
Content-Transfer-Encoding: 7bit

<html>blub blub blub</html>
------=_Part_1_717386707.1476969737326
Content-Type: text/html;charset=UTF-8
Content-Transfer-Encoding: 7bit

<html>Hello world</html>
------=_Part_1_717386707.1476969737326
Content-Type: text/html;charset=UTF-8
Content-Transfer-Encoding: 7bit

Just <b>Text</b>
------=_Part_1_717386707.1476969737326--
------=_Part_0_828441346.1476969737320--
```

As you can see, everything has been sent correctly. Again, it's on client to read to display it.

**Comment by igorspasic** [comment]
Closing as it is library issue :)
