### ISSUE TITLE
REceivedEmail parseMessage doens't read receivedDate

### ISSUE THREAD

**Issue by fpompermaier** [oblac/jodd#304]
I found that my email are read as javax.mail.internet.MimeMessage that implements  getReceivedDate() with a simple return null. Thus, in ReceivedEmail the parseMessage() returns always the current date.
```java
Date recvDate = msg.getReceivedDate();
if (recvDate == null) {
	recvDate = new Date();
}
setReceiveDate(recvDate);
```
I think that's wrong and it would be better to have it null.
A good heuristic could be to try to read it from the 'Date' header if msg.getReceivedDate() is null.. and then try to parse it using a set of patterns (maybe joda library could help here). What do you think?

Best,
Flavio

**Comment by igorspasic** [comment]
Make sense! Leaving `null` is fine, and also getting the date from header is even better... Putting on todo!

:)

**Comment by fpompermaier** [comment]
I saw that Date filed could be a pain to parse..the only method that works with my dates is:
```java
MailDateFormat format = new MailDateFormat();
Date d = format.parse(dateStr);
```
Unfortunately MailDateFormat is not thread safe and with the current constructor of Rceived Mail it is not possibile to pass it as a paramter :(

**Comment by fpompermaier** [comment]
My current solution is 

```java
       final String[] dateHeader = msg.getHeader("Date");
		if (dateHeader != null) {
			if (dateHeader.length > 1) {
				System.out.println();
			}
			try {
				setReceiveDate(new MailDateFormat().parse(dateHeader[0]));
			}
			catch (ParseException e) {
				// e.printStackTrace();
			}
		}
		else {
			System.out.println();
		}
```

but I'd like to use a constant for Date (I don't know wheter it exists or not) and to not create a MailDateformat every time..Could we pass it in the constructor?

**Comment by fpompermaier** [comment]
Maybe it will make senso to make a method public Date getReceiveDate(Message msg) that is called within the parseMessage so one can override it if needed..

**Comment by fpompermaier** [comment]
Actually looking at the MimeMessage code the Date header can be retrieved by the getSentDate() method...I think we can solve this just calling such method!
See http://www.docjar.com/html/api/javax/mail/internet/MimeMessage$RecipientType.java.html
