### ISSUE TITLE
About batch update on database

### ISSUE THREAD

**Issue by youyoubaba** [oblac/jodd#305]
Hello, Could you show me how to do batch update, but just commit once.

**Comment by igorspasic** [comment]
Hey @youyoubaba, do you mean on how to make a transaction over several updates? Like:

+ start transaction
+ update
+ update
+ ...
+ commit

?

**Comment by youyoubaba** [comment]
Yes you are right, i have 100000+ records,i code like below. but unfortunately, the performance is very low.

for (int i=0; i<list.size(); i++) {
    update; 
    commit;
}

**Comment by igorspasic** [comment]
Wait, its not the same :)))) you are executing both update and commit.
Do you maybe want to try to execute all updates in one transaction?

Jodd still does not have support for JDBC batch queries... but soon.

**Comment by moh-sushi** [comment]
Hi Igor,

why is this issue closed?
Enchancement has been added?
Feature will not be added...?

Thank you!

Bye,
Sascha

**Comment by igr** [comment]
@moh-sushi I doubt I will be able to work on this soon and 2 years have been passed since original request...
