### ISSUE TITLE
Java SDK 1.8 and Tomcat use JDK 1.8 is error

### ISSUE THREAD

**Issue by ShrCheng** [oblac/jodd#308]
hello, this is a error:

1. org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class jodd.madvoc.MadvocContextListener
2. Unsupported major.minor version 52.0
3. jodd.madvoc.Madvoc.createWebApplication(Madvoc.java:305)

My environment is

- Mac Eclipse 4.5.2
- Tomcat 8.0.24
- System CentOS release 6.6 (Final)
- Mac and Server JDK is 1.8

I upload package into a war to tomcat webapp directory and start the tomcat server errors

**Comment by igorspasic** [comment]
Hey @ShrCheng Are you sure you are running on JDK 8? 52.0 is the version for java8, and it looks like you compiled your classes on it, but running on eg JDK 7? Jodd itself is build on 7, so the error would be different (the number would be 51.0). Can you please double check that?

**Comment by igorspasic** [comment]
This also can happens if you use gradle in your IDE with JDK7.

**Comment by igorspasic** [comment]
Closing as this is configuration thing :)
