### ISSUE TITLE
Entity parsing is broken for RCDATA

### ISSUE THREAD

**Issue by fuwjax** [oblac/jodd#309]
Parsing the following input:

    <head><title>Peanut Butter & Jelly</title>it's yummy & delicious

should give

    <head><title>Peanut Butter &amp; Jelly</title>it's yummy &amp; delicious</head>

but instead doubles the `&amp;` in the title tag 

    <head><title>Peanut Butter &amp;&amp; Jelly</title>it's yummy &amp; delicious</head>

The fix is easy, it's just missing a continue in the RCDATA bit of the parser.

**Comment by igorspasic** [comment]
Fixed, as you said - you were right, should `continue`.

Thank you!

**Comment by fuwjax** [comment]
Thank you, sir. I appreciate the quite turn around. Any idea when this will be hitting maven central?

**Comment by igorspasic** [comment]
Since this seems urgent, I will try either end of this week, or beginning of the next.
Is that soon enough?

**Comment by fuwjax** [comment]
Yessir, plenty soon enough. I just needed to answer the question for people up the food chain. I'm using a hand-built jar and folks would like something more official.

**Comment by fuwjax** [comment]
Is there anything I can do to help with the release?

**Comment by igorspasic** [comment]
3.7.1 released @fuwjax - just :)
