### ISSUE TITLE
Jodd Http content type is multipart/form-data Chinese error

### ISSUE THREAD

**Issue by rmbzlib** [oblac/jodd#315]
If the content type is multipart / form-data, Received Chinese parameters is '?????'

**Comment by igorspasic** [comment]
Hey @rmbzlib can you please provide the example? So far we didn't have any issue with encodings, i.e. it was read correctly. Which methods do you use for getting the content?

**Comment by rmbzlib** [comment]
```java
HttpRequest.post("http://requestb.in/1lxouwe1")
                .form(
                        "zh_cn", "中文 中文 中文",
                        "file", new File("/Users/qufenqi-xun/Desktop/中文中文中文.txt"))
                .send().bodyText();
```

[http://requestb.in/1lxouwe1?inspect](http://requestb.in/1lxouwe1?inspect)

**Comment by slandelle** [comment]
@rmbzlib As per HTML5 spec, default encoding for `multipart/form-data` is `UTF-8`. This default applies as you have specified a different one (typically in the `Content-Type` header or part header). My best guess is that your file is actually encoded in `GB-2312`.

**Comment by rmbzlib** [comment]
@slandelle `file` and `parameters` encoding is `UTF-8`,if use `Postman` not the problem,I have set the encoding.
```java
HttpRequest.post("http://requestb.in/1lxouwe1")
                .form(
                        "zh_cn", "中文 中文 中文",
                        "file", new File("/Users/qufenqi-xun/Desktop/中文中文中文.txt"))
                .charset("UTF-8")
                .send().bodyText();
```

**Comment by rmbzlib** [comment]
It's settled
update 3.7.1 
thanks
@igorspasic @slandelle
