### ISSUE TITLE
ThreadUtils methods should re-interupt the thread

### ISSUE THREAD

**Issue by jgangemi** [oblac/jodd#317]
i was looking to use one of the `ThreadUtils` methods tonight rather then re-spin a while and i see that they don't really follow good practice when catching an `InteruptedException`. 

if you're going to swallow it, you should at least re-interrupt the thread in the event something else cares.

for reference: http://www.ibm.com/developerworks/library/j-jtp05236/

unfortunately i don't have the time to put together a pull request for what will probably be a 2 minute change.

**Comment by igorspasic** [comment]
Hey @jgangemi totally right! no need to send PR it is really even 1 minute change :)

Will do over the weekend.

Thank you! Stay tuned!
