### ISSUE TITLE
Authorization basic null safety

### ISSUE THREAD

**Issue by Opalo** [oblac/jodd#319]
Hey,

First of all, thanks for a fantastic, easy-to-use library.

In [`basicAuthentication`](https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpRequest.java#L530) both `username` and `password` can be passed as null and it fails with `NullPointerException`. I suggest it should be failing/ignored silently or throwing an `IllegalArgumentException`. Note that I mean `null` values only - user should be allowed to pass empty strings.

I may issue a PR if you agree with me, what do you think?

**Comment by igorspasic** [comment]
Hey @Opalo totally! Thank you for catching this one!

**Comment by Opalo** [comment]
So which option do you choose:
- failing with exception
- ingoring silently

?

**Comment by igorspasic** [comment]
Sorry, i just started to edit my answer :)))

I believe it would be good just to ignore - sometimes these values come from some settings, so passing `null` can happens; and its more in the spirit of the library.

wdyt?

**Comment by Opalo** [comment]
I think it makes sense, however it would be great to notify user that the value passed was just ignored. Do you have any logging configured to output info there?

**Comment by igorspasic** [comment]
Yeah, there is `jodd-log` module that is used in Jodd: http://jodd.org/doc/logging-jodd.html...  So far it is not used in `jodd-http`; so I would not add it just for this line. But... let me added it all over the module! I will create new issue for this one, ok?

**Comment by Opalo** [comment]
Sure, I'll fix the "bug" with ignoring null values silently and issue a PR.
