### ISSUE TITLE
Jerry.text() does not HTML-decode the text

### ISSUE THREAD

**Issue by ferbar** [oblac/jodd#321]
The description:
  Text is HTML decoded for text nodes.

looks as if this does not happen:

Node.java:
```
public void appendTextContent(Appendable appendable) {
  ....
  appendable.append(nodeValue);
```

Text.java:
```
/**
 * Returns encoded HTML text.
 */
@Override
public void getTextContent() {
```

Test code:
```
htmlData="<head><title>test &amp; blah</title><body><h1>test &amp; blah<b>bold</b></h1></body>";

Jerry doc = jerry(htmlData);
Jerry title = doc.$("title");
```

compare
`title.eq(0).html()`
and
`title.eq(0).text()`

**Comment by igorspasic** [comment]
Thanx! You are right! The fix is rather easy, however, need to be somewhat careful, since `appendTextContent` is overriden in `Text` node, as well as `getTextContent`.

**Comment by ferbar** [comment]
thx a lot, works!

maybe you want to add the following code to test321() in jodd-lagarto/src/test/java/jodd/jerry/JerryMiscTest.java

```
               Jerry h1 = doc.$("h1");
               assertEquals("test &amp; blah<b>bold</b>", h1.eq(0).html());
               assertEquals("test & blahbold", h1.eq(0).text());
```

**Comment by igorspasic** [comment]
yap! Just did it @ferbar :)

Thanx!
