### ISSUE TITLE
jodd.paramo.Paramo leaks stream

### ISSUE THREAD

**Issue by JoonasVali** [oblac/jodd#324]
at jodd.util.ClassLoaderUtil.getClassAsStream(ClassLoaderUtil.java:472)
at jodd.paramo.Paramo.resolveParameters(Paramo.java:49)

Stream is opened, but never closed. ClassReader also doesn't close it, because it passes the parameter 'close' as false from this constructor

https://github.com/oblac/jodd/blob/master/jodd-proxetta/src/main/java/jodd/asm5/ClassReader.java
https://github.com/oblac/jodd/blob/master/jodd-proxetta/src/main/java/jodd/paramo/Paramo.java

**Comment by igorspasic** [comment]
Hey @JoonasVali good catch! Streams are always better when they are closed after use :)))

Thank you!
