### ISSUE TITLE
How to add scheduled task?

### ISSUE THREAD

**Issue by titanseason** [oblac/jodd#326]
How to add scheduled task? Such as auto run a tast at 02:00 AM every day?

**Comment by igorspasic** [comment]
Hey @titanseason! Jodd does not have any scheduling component, as this is easy to add with help of some 3rd party lib. There are many cron implementations in java; [quartz](http://www.quartz-scheduler.org/) was quite good one in the time I was using it.

**Comment by igorspasic** [comment]
One example how you can add it, if you are using `Petite`:

+ create `PetiteBean`
+ initialize quartz in constructor, init method or on lazy call
+ schedule invocation
