### ISSUE TITLE
jodd.jerry.Jerry.form(...) throws NPE when input node does not have type attribute

### ISSUE THREAD

**Issue by Funtic** [oblac/jodd#335]
According to https://www.w3.org/TR/html-markup/input.html :

> An input element with no type attribute specified represents the same thing as an input element with its type attribute set to "text".

jodd.jerry.Jerry.form(...) throws NPE when type attribute of input node is omitted.

 					String type = $inputTag.attr("type"); // <-- returns NULL

					boolean isCheckbox = type.equals("checkbox"); <-- throws NPE
					boolean isRadio = type.equals("radio");

**Comment by igorspasic** [comment]
Hey @Funtic! But jQuery does not return the "text":

    <input id="x">
    alert($('#x').attr("type"));

is `undefined`. Technically, the attribute is not set, in the markdown.

**Comment by igorspasic** [comment]
I believe the key is in the word "_represent_". So, attribute _is_ `null`, however, browser will represent this undefined value as `text`. But you are right, `form()` breaks!

**Comment by igorspasic** [comment]
Hey @Funtic, fixed! Thank you soooo much!
