### ISSUE TITLE
Jodd Joy Authentication

### ISSUE THREAD

**Issue by vilmospapp** [oblac/jodd#338]
Hi @igorspasic 

I'm trying to implement authentication with Jodd Joy (3.7.1), but I have no luck with it. I've tried to implement it the way Uphea has it and even with the documentation as well. There's no 

```
<j:form>
```

 tag for example. 
There's no

```
AuthUtil.isSessionActive(session)
```

 method, there's no  

```
IdRequestInjectorInterceptor.class, 
PrepareInterceptor.class
```

There's no:

```
DispatcherUtil.getActionPath(...)
```

So I'm completely stuck with it.

Is there a chance to have a minimal working example in the Github repo? With one public, one proteceted page with simple AuthenticationInterceptor and AuthorizationInterceptor? 

Regards,
Vilmos

**Comment by igorspasic** [comment]
Hey @vilmospapp 

I feel your pain! Unfortunately, our examples are bit old. I will start updating, starting from October 1st. Its Jodds comeback day!

Please, for now, just continue your work, so later you will be able to implement this with just adding annotations.

Sorry again!

**Comment by vilmospapp** [comment]
NP :) 
Just a quick question:
If you have an index.jsp, login.jsp, protected.jsp with IndexAction, LoginAction, ProtectedAction and AuthenticationInterceptor implementation and AuthorizationInterceptor implementation what is the planned behaviour when guest user tries to access protected.jsp?

**Comment by igorspasic** [comment]
It should go to `login` action - it is an alias for Login action.

**Comment by igr** [comment]
This have been refactored with the Auth in the Joy.

We now support token base auth, too. It's also simplified.

It's still work in progress, just wanted to close it as we gonna have the example :)
