### ISSUE TITLE
Create an empty folder

### ISSUE THREAD

**Issue by carlosthe19916** [oblac/jodd#341]
Hello, i was using ZipBuilder and it is an amazing library....now i'd like to add an EMPTY FOLDER to a zip file like this: 

> byte[] bytes = ZipBuilder.createZipInMemory().addFolder("myEmptyFolder").toBytes();

But when i write that bytes like:

> File zipFile = new File("/home/admin/Documents", "test.zip");
> FileUtil.writeBytes(zipFile, zip);

Then the result doesn't have the empty folder.

How can i add an empty folder?

**Comment by igorspasic** [comment]
Hey @carlosthe19916 !  I just tried your example, and the final zip does have the empty folder :) See yourself:

[test.zip](https://github.com/oblac/jodd/files/531370/test.zip)

And the content:

![image](https://cloud.githubusercontent.com/assets/2280001/19412904/1b870620-9320-11e6-8353-e25fb9032b22.png)

I know that some zip viewers and un-zipping tools may omit empty folders. Maybe you can send your zip and check it out again with different tool?

I tried this on latest jvm8.

**Comment by igorspasic** [comment]
I will close this issue now, as it works here. Thanx!

**Comment by igorspasic** [comment]
See related testcase.
