### ISSUE TITLE
Add footer tag for decora

### ISSUE THREAD

**Issue by vilmospapp** [oblac/jodd#346]
Hey @igorspasic,

It's common best practice to add javascript file loading to the bottom of a page, to avoid blocking the page load. In case, when some pages need some additional javascript files to load, but they depend on some of the commonly loaded ones form the main.jsp's body bottom, then they won't do their job because the dependent libraries will be loaded later.

So I would suggest, that we could add a tag like : 
```
<decora:footer>
    <script src="${CTX}/js/jquery.placepicker.min.js"></scrip
    <script src="${CTX}/js/gmaps.js"></script>
</decora:footer>
```
These libraries are depend on jQurey and if jQuery is loaded on the main.jsp's bottom, they will be broken.

What do you think? Is it reasonable?

**Comment by igorspasic** [comment]
Absolutely!

**Comment by igorspasic** [comment]
Actually, this is already doable :) See added example in the test: c73eda3

Please let me know if this is what you mean. I used the div and the ID approach, but you could use the `<footer>` tag as well, if you are not using it for something else (or even `footer` with some `if`).

**Comment by vilmospapp** [comment]
For first sight it seems to be good :)

**Comment by igorspasic** [comment]
Closing this one then :)
