### ISSUE TITLE
Merge EmailAddress and MailAddress

### ISSUE THREAD

**Issue by igorspasic** [oblac/jodd#348]
No need to have it both. OR?

+ `EmailAddress` is kind of 'utility' class, that does parsing, which can be heavy (hello regular expressions ;)
+ `MailAddress` was meant to be a simple bean, so you can collect address without any parsing.

When I tried to merge these two, it was not so trivial as I wanted to keep that simple feature of 'collecting' the email address in a bean, and not parsing. Also, `MailAddress` should be the one that is developer friendly, and does all the encoding thing; `EmailAddress` is raw class, that implements RFCs and its not important to be developer friendly.

The plan was not to have ppl using `EmailAddress`, but `MailAddress`.

In this light maybe the merge is not what we need, but to have `EmailAddress` the class that creates `MailAddress`... Maybe some renaming should be done.

I will see this today.

**Comment by neroux** [comment]
That pretty much summarises it (plus my concerns and my futile attempt to merge them ;-) ).

> Maybe some renaming should be done.

I'd also vote for a rename, in particular of `EmailAddress`. Maybe something of the sort of `RFC2822Validator` or `RFC2822Parser`. It might sound a bit clumsy though and has a certain Star Wars connotation :). Also, it seems to implement not only 2822 but `RFCMailAddressParser` might be even more off 8-)
