### ISSUE TITLE
badge.fury.io - integration broken?

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#350]
Hi jodd-Team,

is the badge.fury.io - integration broken?
Icon shows "version 3.7.1".

![jodd-badge-fury-integration-icon](https://cloud.githubusercontent.com/assets/1374474/19723108/1b23792c-9b7a-11e6-918e-9915c362846c.png)
Yesterday jodd 3.8 was released...

Greetz
Sascha

**Comment by igorspasic** [comment]
No worries, its not integration; just this `fury.io` service is not able to read the latest tag. I still don't know why, maybe its because of semver versioning; I've just added `3.8.0` tag, so lets see if it will picki it up.

**Comment by igorspasic** [comment]
Thanx moh-sushi for this, I haven't noticed ;)))

**Comment by igorspasic** [comment]
Fixed, by removing fury.io.

**Comment by moh-sushi** [comment]
> Fixed, by removing fury.io.

Well, also a kind of solution :-)
