### ISSUE TITLE
outdated site http://jodd.org/

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#351]
your site http://jodd.org/ is outdated -> latest version is 3.7 on this site.

Do you have any plans for updating site content?

Thank you!

**Comment by moh-sushi** [comment]
I have seen on your twitter account that updating docs is an on-doing task (see [this tweet](https://twitter.com/joddorg/status/791233845735677952))

Therefore i'll close this issue :-)

**Comment by igorspasic** [comment]
Yes :) I had some internet issue at home, but now we are back online :)
