### ISSUE TITLE
ArraysUtil -> idea of usage of StringBand

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#353]
Hi,

idea : what about usage of jodd's StringBand in (generated) ArraysUtil instaed of StringBuilder?

>  // now
> StringBuilder sb = new StringBuilder();

>  // new
> // with value for initial capacity;  
> StringBand sb = new StringBand(array.length + 1);

Bye,
Sascha

**Comment by igorspasic** [comment]
Thanx, just did it :) Sorry for somewhat longer response; i've added the JMH performance scopes to gradle for benchmarks and that took some time.

Btw, the bands size is `2 * array.length - 1` :)
