### ISSUE TITLE
Different Mb sizes on several pages/docs ...

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#354]
Hi,

> Jodd = tools + ioc + mvc + db + aop + tx + json + html < **1.6 Mb**

the Mb value is different at following places:

+ [x] https://github.com/oblac/jodd (1.6 Mb)
+ [x] https://twitter.com/joddorg (1.7 Mb)
+ [x] http://jodd.org/about/ (1 Mb)
+ [x] http://joddframework.org/ (1.5 Mb)
+ [x] http://oblac.github.io/jodd/ (1.2 MB)

The mentioned Mb value should be equals at all places ;-)

Maybe, this issue can be solved with the upcoming task "update documentation" ;-)

**Comment by igorspasic** [comment]
Ah, yes, I have this pending long time now :))

**Comment by igorspasic** [comment]
Btw @moh-sushi you should join the Jodd team :))) This issue proves it :)

**Comment by igorspasic** [comment]
I hope you don't mind, Ive edited the issue to make a checklist and have added missing places that also have to be fixed.

btw we are going with **1.7** MB.

**Comment by moh-sushi** [comment]
> I hope you don't mind

no problem :-))
btw: checklist is a good idea!

**Comment by igorspasic** [comment]
Done! Even added a variable for site :)
