### ISSUE TITLE
Source files are without license headers

### ISSUE THREAD

**Issue by puntogil** [oblac/jodd#358]
Hi

The following source files are without license headers:

./buildSrc/src/main/groovy/CoverallsReporter.groovy
./buildSrc/src/main/groovy/Report.groovy
./buildSrc/src/main/groovy/SourceReport.groovy

./etc/gfx/colors.cs

./jodd-core/src/main/java/jodd/util/CommandLine.java
./jodd-core/src/main/python/ArraysUtil.py
./jodd-core/src/main/python/ConvertBean.py
./jodd-core/src/main/python/FastBuffer.py
./jodd-core/src/main/python/fastbuffer.sh
./jodd-core/src/main/python/PrimitiveArrayConverter.py
./jodd-core/src/main/python/PrimitiveArrayLists.py
./jodd-core/src/main/python/Printf.py

./jodd-lagarto/src/main/flex/jodd/csselly/csselly.sh

./jodd-petite/src/main/java/jodd/petite/proxetta/ProxettaBeanDefinition.java
./jodd-petite/src/test/java/jodd/petite/prox/Logged.java
./jodd-petite/src/test/java/jodd/petite/prox/LogProxyAdvice.java
./jodd-petite/src/test/java/jodd/petite/prox/MixedScope343Test.java
./jodd-petite/src/test/java/jodd/petite/prox/PetiteHelper.java
./jodd-petite/src/test/java/jodd/petite/prox/example1/ExternalBean.java
./jodd-petite/src/test/java/jodd/petite/prox/example1/IMainPetiteBean.java
./jodd-petite/src/test/java/jodd/petite/prox/example1/ISubPetiteBean.java
./jodd-petite/src/test/java/jodd/petite/prox/example1/impl/MainPetiteBean.java
./jodd-petite/src/test/java/jodd/petite/prox/example1/impl/SubPetiteBean.java

./jodd-vtor/src/main/java/jodd/vtor/constraint/ValidURL.java
./jodd-vtor/src/main/java/jodd/vtor/constraint/ValidURLConstraint.java
./jodd-vtor/src/main/python/jodd/vtor/constraint/apply.py
./jodd-vtor/src/test/java/jodd/vtor/constraint/ValidURLConstraintTest.java

./src/main/javadoc/jodd.css
./src/main/javadoc/jodd-old.css
./src/main/python/package2package-info.py

Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by igorspasic** [comment]
Thanx! @puntogil, did it!

I didn't change the `cs` file as it is a binary, and not a source.
