### ISSUE TITLE
PLEASE ADD JAR DOWNLOAD LINK TO THE MAIN PAGE

### ISSUE THREAD

**Issue by restmad** [oblac/jodd#362]
Please add jar download link to the main page.

This will very comfortable for me.

Thank you.

**Comment by restmad** [comment]
I could download 3.7 version by single click. don't know why push me to use maven or gradle staff.

**Comment by igorspasic** [comment]
No worries @restmad ! We actually already do provide the "single-click-bundle" version, we just forgot to put in the documentation :) Its updated now, so please take a look:

http://jodd.org/download/#one-in-all-bundle

It basically links to these:

https://repo1.maven.org/maven2/org/jodd/jodd-all/3.8.0/

We just host the jars on maven, its easier for us, and you still have "one-click" experience :)

Hope this works for you!

**Comment by restmad** [comment]
great, thanks.
