### ISSUE TITLE
In some circumstances execution of .sh files on Linux is not possible

### ISSUE THREAD

**Issue by vilmospapp** [oblac/jodd#363]
In rare cases if the Linux installation's SH implementation cannot process the .sh file (probably as it is not fully SH compatible but e.g.: BASH compatible) the execution will fail with **Bad substitution** error.

To handle this situation CommandLine should be modified to read the Shebang from the .sh file before execution and use the defined interpreter to execute it.

So from `#!/bin/bash` it have to use `/bin/bash` instead of `sh` to execute the .sh file.

I'll do the fix once I have time for that and send a PR to you @igorspasic

**Comment by igorspasic** [comment]
There is also a case when shebang line is:

    #!/usr/bin/env bash

when bash path is evaluated.

**Comment by neroux** [comment]
This only seems to be an issue though when `newShell` is true. What would be the purpose of that flag in the first place?

**Comment by igorspasic** [comment]
Heya @neroux! `newShell` indicates if the command is executed with the shell, eg.:

    ls

vs

    bash ls

I second case, the new shell is created.

**Comment by igorspasic** [comment]
Btw, this has been fixed by @vilmospapp PR :)

**Comment by neroux** [comment]
@igorspasic Thanks Igor, but what I'd be curious is about what the purpose of that feature would be in the first place. What advantage would it offer compared to the a regular native process invocation via ProcessBuilder?

**Comment by igorspasic** [comment]
@neroux `ProcessBuilder` is used in the background ;) So you get the following benefits:

+ first, you get the output streams collected correctly; ive seen few times people miss to do this right, and resulting string may having missing lines
+ some syntax sugar is there, like with environment vars
+ and finally, ability to spawn new shell; for example, one that is specified in shebang line of your script.

**Comment by neroux** [comment]
Thanks @igorspasic, I did notice that `ProcessBuilder`is used anyway, but I was simply wondering why there'd be a flag for an additional layer at all

1. Do you mean `Process.getOutputStream()` would not return the proper output stream in some cases? Could you elaborate on that?

1. axa

 

*

**Comment by neroux** [comment]
Thanks @igorspasic, I did notice that `ProcessBuilder`is used anyway, but I was simply wondering why there'd be a flag for an additional layer at all

1. Do you mean `Process.getOutputStream()` would not return the proper output stream in some cases? Could you elaborate on that?
1. In what way is that not there with a regular invocation?
1. Unless I am mistaken, the shebang directive should be however evaluted by the system call issued by `ProcessBuilder` anyhow.

I hope I was able to clarify why I wonder about the newShell flag :)

**Comment by igorspasic** [comment]
1. `OutputStream` is fine, but when you want to collect it all to a e.g. a String... well, i saw few time the output that was missing some number of last chars.
2. Agree, this one is not super important here.
3. This is the right question... Hey @vilmospapp why do we need this? I remember now that last time when `CommandLine` was removed, this was the reasoning. Can you elaborate why we need to call the shell explicitly, when `ProcessBuilder` does that for us?

**Comment by neroux** [comment]
Thanks for the clarification @igorspasic.

I just ran a test to be on the safe side and `ProcessBuilder` does execute a shell script correctly (**with the interpreter specified in the shebang**) and does return the full output. So unless there is a good reason I'd vote for removing the entire newShell handling.

The only reason I could possibly think of to have that feature is if you want to force the execution of shell scripts without an execution permission. But that would only apply to Unix platforms (hence the Windows part can be removed in any case) and I'd argue the `CommandLine` class would be the wrong place for such an exception handling.

I hope @vilmospapp could shed some light on why that would be there.

**Comment by igorspasic** [comment]
Thanx @neroux ! This is exactly what I wanted to test. If we remove the `newShell`, then the whole class might be removed (and eventually replaced with a util method that collects the output). Once i did remove it because of that reason, but I have forget it :)

**Comment by igorspasic** [comment]
I will open new issue to track this
