### ISSUE TITLE
release plan for 3.8.1

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#366]
Hi,

any release plan for 3.8.1 in 2016?

maybe as christmas edition? :-)

Greetz

**Comment by igorspasic** [comment]
![image](https://cloud.githubusercontent.com/assets/2280001/21203209/bbf88cd6-c251-11e6-8461-1b4d455a76fd.png)

**Comment by igorspasic** [comment]
Aaaaaaaaand...
done :)
