### ISSUE TITLE
serialize a bean to JSON

### ISSUE THREAD

**Issue by TahorSuiJurisBenYAH** [oblac/jodd#368]
Hello, can your Jodd help me accomplish:

jsf managed bean accessing MySQL remote database - how to create JSON array to feed

http://stackoverflow.com/questions/41142802/jsf-managed-bean-accessing-mysql-remote-database-how-to-create-json-array-to-f

Any suggestions greatly appreciated.

Jon

**Comment by igorspasic** [comment]
Jodd does have bean serialization to JSON :)

**Comment by igorspasic** [comment]
Sorry, I am not quite sure what are you asking me. Please be more concrete how we can help.  Thanx!

**Comment by TahorSuiJurisBenYAH** [comment]
Excellent, thank you.  Igorspasic.

I believe I may have found a possible solution

**Comment by TahorSuiJurisBenYAH** [comment]
[https://www.mkyong.com/java/jackson-2-convert-java-object-to-from-json/](url)

in

3. POJO (Plain Old Java Object)
A simple pojo Staff object for testing.

4. Java Object to JSON
Convert a Staff object into a JSON formatted string.

**Comment by TahorSuiJurisBenYAH** [comment]
I am trying to discover what the jquery object / component would require from the JSON conversion from the bean, as in [http://paramquery.com/demos/grid_json](url) but the example is a static data set.  Any suggestions greatly appreciated.

Thank you.

**Comment by TahorSuiJurisBenYAH** [comment]
Please may I have a link that demonstrates how I can usse JODD to accomplish the JAVA OBJECT bean to JSON ?

**Comment by igorspasic** [comment]
Hey @TahorSuiJurisBenYAH see this: http://jodd.org/doc/json/

It should give you all the answers :)

**Comment by TahorSuiJurisBenYAH** [comment]
thank you
