### ISSUE TITLE
CommandLine vs ProcessBuilder

### ISSUE THREAD

**Issue by igorspasic** [oblac/jodd#370]
What is the purpose of running `CommandLine` with `newShell`?
Because `ProcessBuilder` can run scripts directly, no need to spawn new shell?
@vilmospapp @neroux

Test JAR (had to zipit):

[runsh.jar.zip](https://github.com/oblac/jodd/files/675653/runsh.jar.zip)

Usage:

    java -jar runsh.jar hello.sh

Testing on Java 8 and:

+ [x] Windows 10
+ [x] MacOS
+ [x] Ubuntu 14 (vangrant)
+ [x] Debian 7

**Comment by neroux** [comment]
I've already prepared a fork which does not include newShell anymore, but I'd like to wait a bit until we can get some feedback as to why it was there in the first place.

**Comment by igorspasic** [comment]
Agree @neroux!

**Comment by neroux** [comment]
@igorspasic

I have preliminary opened #371. Lets merge it if there is no objection.

**Comment by neroux** [comment]
In addition to my previous statement

> The only reason I could possibly think of to have that feature is if you want to force the execution of shell scripts without an execution permission. But that would only apply to Unix platforms (hence the Windows part can be removed in any case) and I'd argue the `CommandLine` class would be the wrong place for such an exception handling.

I believe I now understood what you meant by

> some syntax sugar is there, like with environment vars

You were referring to the fact that one could incorporate environment variables in the passed command string, right? That is correct (*ProcessBuilder does not seem to support that*), however that would be OS dependent (**%VAR% vs $VAR**). Hence I reckon two viable options

1. We keep `CommandLine` and support for forcible execution of non-executable shell scripts as is and spice up the class with an OS-independent environment variable expansion.
1. We drop the class altogether and provide a convenience method to collect the output (like StreamGobbler) as you suggested.

Personally I'd opt for option 2 too.

**Comment by igorspasic** [comment]
Hey @neroux, option /2 is also what I have in mind. Simple utility to collect the process output (as it is now) would be enough. Running non-executable scripts is not that huge, at the end, you can always run a 'runner' script that `source` the target script.

There is also an issue 1) with different shells and 2) with evaluation of shebang line.

**Comment by igorspasic** [comment]
Hey @neroux do you have by any chance a source of your example of `ProcessBuilder` that executes a shell script? I have just talked to @vilmospapp and he said that once (before) he was not able to run script on all linuxes (or maybe windows).

If not not a big deal, I will code by myself, its 5 lines anyway :)

**Comment by igorspasic** [comment]
The idea is to test it on various linuxes now. @vilmospapp has access to some number of linuxes they have in the company, so we can all test it and report here.

**Comment by neroux** [comment]
I dont have it here right now, but could get back to you later today.

However it was really a relatively straight forward example of the sort of
`new ProcessBuilder("/path/to/script").start()`

Could he provide a reproducible version of it? Of course running it on Windows wont work, but that wont work with newShell either :)

**Comment by igorspasic** [comment]
@neroux no need, made it ;)

**Comment by igorspasic** [comment]
@neroux Ive made small jar for test. Can you send me your OS name where did you test it?

**Comment by neroux** [comment]
I ran it on a Debian 7 setup.

Additional remark: To test the shebang config as well, I symlinked /bin/bash and specified that link in the script.

**Comment by neroux** [comment]
- [ ]

**Comment by igorspasic** [comment]
Hey @neroux, Ive merged your PR. Moreover, Ive added some more features to `CommandLine`, so I believe now it has its own purpose :)

Feel free to review the code - especially the method names, I really am not good at that ;))))

Thank you for spotting this!
