### ISSUE TITLE
EmailAddress does not accept non-latin names

### ISSUE THREAD

**Issue by neroux** [oblac/jodd#374]
The regular expressions used in `EmailAddress` do not seem to be configured for non-latin characters.

`new EmailAddress("Vladimir <v@example.com>");` will successfully parse the address
`new EmailAddress("Влади́мир <v@example.com>");` will not (presumably due to the regular expression not accepting the Unicode characters)

`EmailAddressTest` should probably have some non-latin cases for the personal part as well.

**Comment by igorspasic** [comment]
Wow! Thanx @neroux , this one is very important!

**Comment by neroux** [comment]
I am not surprised anymore that it does not accept Unicode names. After digging through RFCs (particularly 5335, 6531 and 2047) and getting dizzy :) it appears it behaves fully standards compliant as the name does not get passed in its encoded form. I havent verified yet what isValid() returns but I am pretty confident it will be `false`.

The question is now should the class handle the encoding itself or expect the value in its encoded form? If the latter we can close this issue.

**Comment by igorspasic** [comment]
Yeah, those RFCs are really crazy. Like for email message, it can get really weird :)

Our class should be developer friendly, like you said!, so it should encode things correctly. Let me see...

**Comment by neroux** [comment]
Closing the issue as - after clarification - `EmailAddress` works as intended.

**Comment by igorspasic** [comment]
Thanx @neroux !!!
