### ISSUE TITLE
NaturalComparator does not follows the contract in certain cases.

### ISSUE THREAD

**Issue by igorspasic** [oblac/jodd#381]
According to [this](http://stackoverflow.com/questions/41634643/why-does-this-code-throw-exception-comparison-method-violates-its-general-cont) `Natural` comparator fails the contract in certain cases.

**Comment by neroux** [comment]
Are we sure this is a Jodd issue and not related to TimSort? The latter class appears to be OpenJDK specific and does not exist in Sun's JDK.

Unfortunately the OP hasnt provided a reproducible code snippet yet.

**Comment by neroux** [comment]
One *potential* problem in the class could be `charAt()`. If it is call on a string's position which incidentally contains an ascii 0 character, it will wrongly report the end of the string. Cannot tell yet though if this is in any way related to the reported exception.

**Comment by igorspasic** [comment]
`TimSort` exist only in Java8 JDK, so I guess that is why this happens to this guy: he uses java7 locally, where default sorting algorithm was `MergeSort` which has been replaced with `TimSort`. I've already throw some random strings to this class, but so far the reflection (`a == b`, therefore `b == a`) works. Will check the `charAt`! Thank you @neroux !

**Comment by neroux** [comment]
Sorry, my bad. I couldnt find any reference to `java.util.TimSort` in the Java's javadoc and hence assumed it would be specific to one JDK. I just checked rt.jar and it actually does include that class. Apologies.

As for `charAt`, I cant tell yet whether that could be related in any way. I just spotted the edge case with ASCII 0 and wanted to mention it :)

**Comment by igorspasic** [comment]
No worries @neroux :) I am still not able to see a case where this comparison fails. I am doing test like this:

			int one = comparator.compare(s1, s2);
			int two = comparator.compare(s2, s1);

			if (one == 0) {
				assertEquals(0, two);
			} else if (one < 0) {
				assertTrue(two > 0);
			} else {
				assertTrue(two < 0);
			}

to test reflection feature. However, It seems I should test transitivity as well.

**Comment by igorspasic** [comment]
Found it:) The following input would not be transitive:

		String s1 = "0N";
		String s2 = "Aa";
		String s3 = "4M";

**Comment by igorspasic** [comment]
It's like you said @neroux, string starting with `0` will break it... good catch! I guess I can ignore 0 only if the complete string is digits only.

**Comment by igorspasic** [comment]
Fixed by 93f4ac149a53cf869ba26617be790ba1bfd3c2b4

**Comment by neroux** [comment]
Thanks @igorspasic but I believe we misunderstood each other. You are referring to the 0 character (ASCII 48), right? I was referring to the NUL character (ASCII 0).

**Comment by igorspasic** [comment]
Riiiiiight! That is true, also, I do use 0 as a `special` char/flag. I should remove that!

Although even I got it wrong, it helped me to find the issue with the Comparator contract - thank you !!!

**Comment by neroux** [comment]
I am glad I unwittingly could assist in find the issue :)

The 0 only becomes an issue when a string contains that character.
