### ISSUE TITLE
Create a TodoBackend implementation showcasing Jodd

### ISSUE THREAD

**Issue by moredip** [oblac/jodd#383]
Hi,

I'm a curator for [todobackend.com](http://todobackend.com), a community resource showing examples of how to build the same simple HTTP API using different frameworks. We'd love to get a Jodd implementation contributed - in fact we have an [issue filed](https://github.com/TodoBackend/todo-backend-site/issues/117) for it!

Creating a todobackend implementation usually only takes a hour or two for someone experienced in the framework they're using. There's lots more information about how to do it on the todobackend site [here](http://todobackend.com/contribute.html).

**Comment by igorspasic** [comment]
Sure, why not :)

**Comment by igr** [comment]
@moredip soon we are going to release Jodd 4, and my todo example is already made :)

**Comment by igr** [comment]
https://github.com/oblac/todo-backend-jodd
