### ISSUE TITLE
Add better support for accents and foreign chars in NaturalComparator

### ISSUE THREAD

**Issue by igr** [oblac/jodd#384]
Currently, special chars that are resolved as two-letter chars are ignored, e.g.:

    Æ -> AE

Add support for this kind of special chars, but without replacing them in the strings...

**Comment by neroux** [comment]
Pardon my possible ignorance, but what exactly is `NaturalComparator` supposed to do?

I would understand it is to sort strings based on a locale, but wouldnt that require the locale to be specified and isnt that also covered by `java.text.Collator`?

**Comment by igorspasic** [comment]
Correct @neroux, that is one more thing that a more powerful `NaturalComparator` would do. Currently, the `NaturalComparator` is more english-only, with knowing some accents. But that is not the only thing natural comparison does :) There is a feature when number parts of the strings are compared separately, please check the: https://github.com/oblac/jodd/blob/master/jodd-core/src/test/java/jodd/util/NaturalOrderComparatorTest.java. Also, zeros get ignored (sometimes) as well as all white spaces.

Just check the test, the arrays there are sorted in natural way, so you will see it:

https://github.com/oblac/jodd/blob/master/jodd-core/src/test/java/jodd/util/NaturalOrderComparatorTest.java#L76
https://github.com/oblac/jodd/blob/master/jodd-core/src/test/java/jodd/util/NaturalOrderComparatorTest.java#L301
https://github.com/oblac/jodd/blob/master/jodd-core/src/test/java/jodd/util/NaturalOrderComparatorTest.java#L289

**Comment by neroux** [comment]
Thanks for the clarification. So its purpose is to ignore whitespace and leading zeros in numbers for sorting, right?

**Comment by igorspasic** [comment]
Yes @neroux, it ignores all whitespaces, but also deals with leading zeros - not simply ignoring, but in most cases yes. And then, when we recognize the number parts of the string, we compare them separately, as they are real numbers.

This is quite convenient when listing e.g. files in a folder; more human the output is :)

**Comment by neroux** [comment]
Sounds fair enough, thanks again for the clarification.

As for accented characters and the issue here, what is your opinion on keeping that functionality out of `NaturalComparator`'s scope and instead rely on `java.text.Collator` (either implicitely by extending `java.text.RuleBasedCollator` or explicitely by the user using both classes in combination)?

**Comment by igorspasic** [comment]
Hm, agree @neroux. I am not sure if I know how to write such class properly atm; recent work was done just to solve contract issues with java8 sorting. Priority now is the overall migration to java8 and more fluent developer-friednly interface where possible.

**Comment by igr** [comment]
This is a 'good-to-go' class for natural sorting, that focuses mainly on whitespaces and various numbering schemes. It tackles accent, but, of course, does not give 100% solution for it. Using `Collator` or `RuleBasedCollator` - its just out of our possibilities, atm
