### ISSUE TITLE
How to serialize entities to xml?

### ISSUE THREAD

**Issue by titanseason** [oblac/jodd#386]
Is there a serializer which can serialize entities to xml like `jodd.json.JsonSerializer` ?

**Comment by titanseason** [comment]
And is there a parser which parses xml to entities like `jodd.json.JsonParser` ?

**Comment by moh-sushi** [comment]
As far as i know there is no "jodd xml" - module

Therefore you need something else like [xstream](http://x-stream.github.io/) or [jaxb](https://docs.oracle.com/javase/tutorial/jaxb/index.html) / [jaxp](https://docs.oracle.com/javase/tutorial/jaxp/index.html )

HTH

**Comment by igorspasic** [comment]
Yes, there is no serialization to XML. Instead, you can serialize in JSON using `jodd-json` library. 

For parsing things are bit different: you can parse XML (with our HTML/XML parser, which is very nice:), but you don't have data binding - you just get the tree from your XML and that is it.

Jumping into XML might be too much for us at the moment. Would it be option for you to use JSON instead?

**Comment by igorspasic** [comment]
Closing this, as this is answered :)

**Comment by titanseason** [comment]
@igorspasic Thank you, but I must use xml instead of json in some cases.
Do you have any plan to add jodd-xml module?
If not, I would try to use xstream or jaxb / jaxp.

**Comment by igorspasic** [comment]
We might :) But not any time soon, I guess.
