### ISSUE TITLE
Unify the constructor and build method names for all builders

### ISSUE THREAD

**Issue by igorspasic** [oblac/jodd#387]
We use a lot of builders in Jodd. They are created using the `new` keyword:

    new FooBuilder().setAaa(a).setBbb(b).build();

Let's add a method that replaces the constructor and to unify the build method, eg.:

    FooBuilder.newFoo().setAaa(a).setBbb(b).build();

In other words:

+ constructor method would be called `new<Name>` (e.g. `newThreadFactory`) - similar to what one would be written (`new ThreadFactory`).
+ builder method (the last one) is just `build`

@neroux @moh-sushi wdyt?

**Comment by neroux** [comment]
Now, we deeply delve into design patterns :)

From what I understand you'd like to replace the instantiation of a new builder object with a static method, right? At the first glance I would have "yelled" Factory :) and I actually had to refresh my memory on that subject and found http://stackoverflow.com/questions/757743/what-is-the-difference-between-builder-design-pattern-and-factory-design-pattern, which suggests a builder class should actually use instantiation versus the factory's common static method approach.
Do you have a particular reason in mind why you'd like to introduce that change?

On a different but related subject, are we sure we need builders/factories in all that cases anyhow or would a regular class instantiation maybe suffice? Chaining setters would be still possible with the latter anyhow.

As for `build()`, I believe I missed something here. Both examples above refer to a zero-parameter method.

**Comment by igorspasic** [comment]
Here is the background story - it is really not much, neither a big change, it's more about proper and unify naming, which I always personally have problem with :)

In Jodd we are already using Builder pattern on several places, in order to simplify complex creation of some objects, and to make it more visual and clear to user-developer. Factories are not used much (if any), as we don't provide different implementations of the same things, hence no reason to have them in the first place.

Factories, where needed, will be inside the interface, as an interface static method. As a library, we don't need to provide more then that... as factories are easy to build, and yet everyone see it configured differently, depending on the needs on the projects.

Builders, on the other side, goes well with making things developer-friendly. I love when code gives users hints on how it something has to be used. For now we use them in Jodd on several places to make object creation simpler.

This issue is all about naming the builders. We have two types of builders:

+ 'real' builders, like `ThreadFactoryBuilder` - that simply creates `ThreadFactory` in an fluent way. It has `newThreadFactory()` static method for creating the builder and finally `build()` method to construct the `ThreadFactory` and returns it.
+ 'bean' builders, like `Email` - where we just need to create and populate a bean. It has `create()` static method for creating the the bean - that might be called `createEmail()`.

All I want is to have the unified naming across libraries :)

**Comment by neroux** [comment]
`ThreadFactoryBuilder` is a good example, as I grepped earlier today for *Builder* and came across it. I am not quite sure why there are two build methods. The instance method is calling the static method and passes `this` (which basically also happens on a compiler level with the instance method anyhow). If the static method wasnt private I could even imagine some other use case, but in that way I cant and would really feel tempted to unify/simplify that particular class (unless of course you have an objection).

My question about the purpose of builder classes was mostly because I dont think it would be necessary to have additional classes to achieve something that can be easily done with a constructor. There'd be virtually no difference between

`Dummy dummy = new DummyBuilder().setString('').setInt(123).setBoolean(true).build();`
and
`Dummy dummy = new Dummy().setString('').setInt(123).setBoolean(true);`

If I blatantly missed something please let me know.

But as for a unified naming schema, that's definitely something desirable 👍

**Comment by igorspasic** [comment]
Absolutely! This is that second example I was talking about :) Let me use your example and add all the variants that i have in mind:

**/A** with constructor, default usage:

    Dummy dummy = new Dummy().setString('').setInt(123).setBoolean(true);

**/B** with static construction method (i like this as in the future you can change the way how class is created, i.e. we might prepopulate etc):

    Dummy dummy = Dummy.create().setString('').setInt(123).setBoolean(true);

or:

    Dummy dummy = newDummy().setString('').setInt(123).setBoolean(true); // with static import

**/C** Finally, there is a third case of builders for objects that we dont control, like ThreadFactoryBuilder:

    Mummy mummy = new MummyBuilder().setString('').setInt(123).build();

or:

    Mummy mummy = newMummyBuilder().setString('').setInt(123).build(); // with static import

--

Questions:

+ case B & C: should static constructor method can be called `create()` - which is ugly with static import; OR `newDummy()`/`newMummyBuilder()`?
+ case C: should terminal method be called `build()`?

**Comment by neroux** [comment]
I would dismiss B in general. There is little point in emulating a constructor via a static method.

As for C and the builder context, I'd still go for the constructor and I guess `build` would be a fitting name (and seems to be pretty standard) for the method eventually doing the hard work.

**Comment by igorspasic** [comment]
Nice, thanx for sharing thoughts, make sense!

**Comment by moh-sushi** [comment]
I would also prefer C with its final method name `build`.

Additional remark:
What do you think about naming the methods with prefix `with` and name of property?

example:
`Mummy mummy = newMummyBuilder().withLabel('jodd').withAge(123).build();`

**Comment by igorspasic** [comment]
@moh-sushi Yes, `with` is today commonly used for builders. The only thing with this is that when we have a bean (with `get` & `set`), we will use setters to return `this` so a bean becomes fluent.

Closing this one as resolved
