### ISSUE TITLE
jodd HttpRequest class inputstream encoding

### ISSUE THREAD

**Issue by restmad** [oblac/jodd#391]
I will very happy if you can take "ISO-8859-1" encoding type chang to a class field, not a hardcode way.

> BufferedReader reader;
        try {
            reader = new BufferedReader(new InputStreamReader(in, "ISO-8859-1"));
        } catch (UnsupportedEncodingException var6) {
            return null;
        }

**Comment by igorspasic** [comment]
Sure, we can do that - but isnt this a standard?

**Comment by restmad** [comment]
there are many APIs here, server side using utf-8 or gbk/gb2312 to receive and send data.
I need set inputstream and outputstream encoding .

**Comment by igorspasic** [comment]
Hey @restmad , Ive added optional argument, as this method is a static method.

Does this works for you?

**Comment by restmad** [comment]
Thanks alot.
