### ISSUE TITLE
Unencoded URL with whitespace breaking HttpRequest

### ISSUE THREAD

**Issue by neroux** [oblac/jodd#394]
A non-URL-encoded URL with a whitespace will break the request.

It appears `HttpRequest.set()` (which is called from [`get()`](https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpRequest.java#L214)) checks for a single space and - if present - assumes the first part to be the desired HTTP method. This will break all URLs which were not properly encoded

    HttpRequest.get("https://jodd.org/random link").send();

While Jodd's current behaviour is not exactly incorrect (after all a URL is supposed to be properly encoded), it could potentially lead to some confusion as to why the error message suddenly refers to a completely different host (the part after the blank will be considered as URL, even though improperly formatted in that case too).

**Comment by igorspasic** [comment]
Added better message - now it shows the complete url.
Also took a chance to improve parsing, to recognize HTTP method.
