### ISSUE TITLE
Cookie Constructor error with cookie value ends with ";"

### ISSUE THREAD

**Issue by wfd0807** [oblac/jodd#395]
If the response cookie value ends with ";", the Cookie constructor will override name and value with ”“ and null.

**Comment by neroux** [comment]
Would you have some sample code?

**Comment by wfd0807** [comment]
i am using jodd http to login a web site. a response header like this:
`Set-Cookie: p_skey=UIJeeZgODkPQgiVcwHJBhq9mYrZC9JdpYF6SCZ3fNfY_; PATH=/; DOMAIN=mail.qq.com; ;`
commit [911952b](https://github.com/oblac/jodd/commit/911952b0ba18fe306d50268acb509e7f0d709783) did not fix all situations.

**Comment by neroux** [comment]
I'd still like to point out that this is originally not a problem with Jodd but that site, as that cookie line is not a valid one. There should not be trailing semicolons (let alone two).

That being said, of course it would be nice if Jodd was lenient enough to still accept such headers as well (after all browsers accept <a href=http://mylink> tags :-) )

**Comment by igorspasic** [comment]
Fixed here 4b53534fccf21b0404680b612b14326aef171a03

Like @neroux said, it's site fault; but again, lets make Jodd eat all the cookies :)))

**Comment by neroux** [comment]
@igorspasic For clarification, shouldnt https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/Cookie.java#L115 be rather this.name?

**Comment by igorspasic** [comment]
@neroux  that is a good question! my idea was: "_overwrite the name/value if exist_". what you say is "_only the first name/value is used_". Frankly, I do not have idea which of these two is better approach :) I used how this worked before, just added a blank-check. Not sure what to do.

Maybe we can check how chrome deals with it and follow the same pattern

**Comment by neroux** [comment]
@igorspasic Well, the name has to be at the very first position and should not be overwritten by anything (again, the aforementioned syntax is just invalid).

Also, cases like `new Cookie("=value");` should be handled too. That code would assign an empty name for that cookie, which is syntactically also invalid.

**Comment by igorspasic** [comment]
Got it @neroux, let me just write here behavior of chrome, maybe that will help us.

**Comment by neroux** [comment]
@igorspasic Understand, though personally I wouldnt stick too much to Chrome's behaviour but rather the RFC - Chrome is known to do some things on its own :)

**Comment by igorspasic** [comment]
identical:

    document.cookie = "username=John Doe"
    document.cookie = "username=John Doe;"

only first name is set (`a==b` is ignored):

    document.cookie = "username=John Doe;a=b";
    document.cookie = "username=John Doe;a=b;";

Empty value, works.

    document.cookie = "username=";

Empty name - ignored:

    document.cookie = "=John Doe";

### some helpers

Delete cookie

    document.cookie = "username=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";

**Comment by neroux** [comment]
> identical:

I'd have assumed that behaviour, even though it is not standard compliant it's a minor thing to ignore and fine in Jodd too I guess :)

> only first name is set

a is presumably ignored because it's an unofficial attribute

> Empty name - ignored:

In Jodd's case I'd argue for the constructor to throw an exception though, which then should be handled appropriately in `HttpResponse.cookies()` (meaning caught and "ignored")

**Comment by igorspasic** [comment]
According to [this](https://tools.ietf.org/html/rfc6265#section-4.1.1) cookie name must be an existing `token`.

But now I tried the following in empty session:

    document.cookie = "=John Doe"

and surprisingly, this is equals to 

    document.cookie = "John Doe"

I would not throw exception for this, just would like to define the behavior for the special cases :)

**Comment by neroux** [comment]
I just checked it in Firefox and Chrome and both actually seem to take the value as name if no name is present. I'd call this utterly wrong.

An additional semicolon is one thing (don't we all know the dilemma when we concatenate strings :) ), a name completely missing IMHO another. Personally I'd still vote for an exception in the constructor and for HttpResponse to skip cookies with an exception :).

**Comment by igorspasic** [comment]
I agree its wrong :) Usually in this kind of 'shady' situation we try to go as much with the conventions, if we have something to compare with (like FF&Chrome here). This is also case with HTML parsing, for example, where we throw exception only when we are out of ideas what to do:)

Just  committed the fix, please see; sorry for not seeing your PR, I just went ahead to fix this while my work project was running tests :)))

Also: http://stackoverflow.com/questions/42531198/cookie-without-a-name

**Comment by neroux** [comment]
> HttpResponse to skip cookies with an exception

On a related note, `Cookie.setName()` already throws an IllegalArgument exception, which however is not caught by `HttpResponse.cookies()`, so it will abort upon an invalid cookie name.

PS: Just because I am an old nitpicker :-D .... "neurox" will be surprised that he is suddenly mentioned in this context

**Comment by igorspasic** [comment]
Aaaaa, fixing it asap :)

**Comment by igorspasic** [comment]
Btw @neroux what you think we should do in `HttpResponse`:

			Cookie cookie = new Cookie(cookieValue);
			cookies[i] = cookie;

We iterate the cookies. I would like to skip the invalid cookie, but since array is already initialized, should we set this to `null` OR... should we use list and return array with only valid cookies?

**Comment by igorspasic** [comment]
Fixed by returning list of only valid cookies :) Yay!

**Comment by neroux** [comment]
@igorspasic Thats a very good point.

* Including null values would provide the user a good indicator that certain cookies were not valid, however negligent users might run into a NullPointer exception and it would not indicate which of the set-cookie headers it was.
* Returning only valid cookies would avoid NullPointers but wouldnt provide feedback (logging something to std out or err might be an option, not sure how good of one though).

I'd _probably_ go for the second option and really skip those cookies in the response class. A possible alternative might be to simply store all set-cookie headers in individual `Cookie` instances and have the constructor set an additional flag when the string could be successfully parsed into its parts (sort of `isValidCookie()`).

**Comment by igorspasic** [comment]
Or list of `Optional<Cookie>` :) For now lets have just a list, as it used to be.

**Comment by neroux** [comment]
> For now lets have just a list, as it used to be.

I guess thats good enough.

> Or list of `Optional<Cookie>`  :)

Or that :). Though I have to admit I never really grasped its full purpose to be honest. Except for the Optional-aware functional methods in Java we simply swap `!=null` checks for `i?Present()` calls and `NullPointerException` for `NoSuchElementException`.

**Comment by igorspasic** [comment]
In this case, `Optional` would not make much sense. In fact, as I see it, it works well only when the rest of the code is functional, and when you can chain methods and so on. Returning just `Optional` without using it 'properly' make not much sense imho. But this is now different subject ;)))

**Comment by neroux** [comment]
[Qt had that issue five years ago](https://bugreports.qt.io/browse/QTBUG-21987)

And [5.2 of RFC 6265 actually addresses that issue](https://tools.ietf.org/html/rfc6265#section-5.2)
> 5.  If the name string is empty, ignore the set-cookie-string entirely.

**Comment by igorspasic** [comment]
Right, nice catch, so now we can simply skip setting of name/value. Great!
