### ISSUE TITLE
HttpRequest Charset

### ISSUE THREAD

**Issue by ifnoelse** [oblac/jodd#397]
https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpResponse.java#L178

why the charset is not utf-8 ？when i use HttpRequst get the html content
the chinese character cannot demonstrate normally
``` java
HttpResponse response = HttpRequest.get("https://book.douban.com/subject/26593175/").send();
System.out.println(response.body());
```

**Comment by neroux** [comment]
#391 related?

**Comment by igorspasic** [comment]
Did you try to use `bodyText()` to get body that is converted in charset specified with the response?

**Comment by igorspasic** [comment]
The reason why we read in default encoding is because body can be binary as well, or different encoding, so we read raw, and convert to target encoding in different method

**Comment by ifnoelse** [comment]
Thinks, bodyText() works properly，Jodd is practical and powerful framework, i love it !

**Comment by igorspasic** [comment]
Thank you @ifnoelse for kind words! Glad this worked :)
