### ISSUE TITLE
Custom Mapping causes postgresql exception

### ISSUE THREAD

**Issue by paujla** [oblac/jodd#399]
Hi, I am using Kotlin with Jodd's DbOom and when using a Custom Mapping to convert an enum to a value for SQL I get the following error:

```jodd.db.DbSqlException: Invalid SQL parameter with index: 3
Query: insert into SOME_TABLE (ID, MSID, STATUS, UPDATED_ON, VERSION) values (?, ?, ?, ?, ?); <--- org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of com.springer.transfersPortal.editorialManager.storage.EmExport$Status. Use setObject() with an explicit Types value to specify the type to use.
	at jodd.db.DbQuery.throwSetParamError(DbQuery.java:154) ~[jodd-db-3.8.1.jar:3.8.1]
	at jodd.db.DbQuery.setObject(DbQuery.java:990) ~[jodd-db-3.8.1.jar:3.8.1]
	at jodd.db.DbQuery.setObject(DbQuery.java:1008) ~[jodd-db-3.8.1.jar:3.8.1]
	at jodd.db.oom.DbOomQuery.prepareQuery(DbOomQuery.java:161) ~[jodd-db-3.8.1.jar:3.8.1]
	at jodd.db.DbQueryBase.init(DbQueryBase.java:194) ~[jodd-db-3.8.1.jar:3.8.1]
	at jodd.db.DbQueryBase.executeUpdate(DbQueryBase.java:680) ~[jodd-db-3.8.1.jar:3.8.1]
	at jodd.db.DbQueryBase.executeUpdate(DbQueryBase.java:670) ~[jodd-db-3.8.1.jar:3.8.1]
	at jodd.db.DbQuery.executeUpdate(DbQuery.java:72) ~[jodd-db-3.8.1.jar:3.8.1]
```

I have followed the documentation on http://jodd.org/doc/db/mapping.html#custom-mappings. I first tried to use the enum in my model without defining a Custom Mapping as the documentation suggests it should work http://jodd.org/doc/db/mapping.html#enum-mappings. My enum has no extra values and is simply being used instead of a String.

**Comment by igr** [comment]
Hey @paujla - can you share also your custom mapping implementation? Because this always should work, as it directly says underlaying layer how to convert to/from database types.

Is your enum defined in Kotlin? Can you just please give a small example how did you defined, just in case Kotlin compiles it in something else?

**Comment by paujla** [comment]
Hi igr, 

The Enum is the following:

```kotlin 
enum class Status {
        NEW, PARTIAL, FAILED, SELECTED, UPLOADED
    }
```


And the custom mapping is:

```kotlin
class StatusSqlType : SqlType<Status>() {
    override fun get(rs: ResultSet, index: Int, dbSqlType: Int) = Status.valueOf(rs.getString(index))
    override fun set(st: PreparedStatement, index: Int, value: Status?, dbSqlType: Int) = st.setString(index, value.toString())
}
```

```kotlin
SqlTypeManager.register(Status::class.java, StatusSqlType::class.java)
```

**Comment by igr** [comment]
Heya, I just conduct similar example in Java, and using custom `SqlType` should work. According to your error, it looks like class name under which the enum sql type is registered is not the same as class name used in your target bean.

I will now try to make the similar in Kotlin. However, if you are here now, it would be super helpful if you can put a breakpoint in line 981 of `DbQuery`:

    sqlType = SqlTypeManager.lookup(value.getClass());

this value is the value that comes from your bean you are using to update the table.

I assume that this class is not the same as class used for sql type registration.

**Comment by igr** [comment]
Can you please check my test case mentioned above? It worked here.

Please let me know how to reproduce the issues. I understand your problem, but DbOom is quite simple: for a value, 1) it gets its class, 2) perform lookup for sql type and 3) use it.

For you it fails either 1 or 2 since sql type can not be found.

**Comment by igr** [comment]
(Btw, I will check whats going on with enums and native support)

**Comment by paujla** [comment]
Hi @igr,

We used the debugger and found that the value of SqlType was the min value of Java int. Which caused the exception to occur.

We have managed to get it to work by doing the following hack, however it's not clear why the library thinks it is an unknown type.

```kotlin
DbOomManager.getInstance().lookupType(MyClass::class.java).findByColumnName("status").updateDbSqlType(42)
```

The 42 is just any arbitrary number we chose.

**Comment by igr** [comment]
@paujla really weird... can you send me definition of your target bean and/or piece of code that is actually executing the query? Which version of postgress driver are you using?

Please check how I tried to replicate it:

https://github.com/oblac/jodd/blob/master/jodd-db/src/testInt/java/jodd/db/oom/Kotlin399Test.java
https://github.com/oblac/jodd/blob/master/jodd-db/src/testInt/kotlin/jodd.db.oom.fixtures/Tester33.kt

except this worked...

**Comment by paujla** [comment]
Hi @igr,

I am using the following to insert the bean, I do not have any annotations on the bean.

```kotlin
DbEntitySql.insert(thing).query(session).executeUpdate()
```

**Comment by igr** [comment]
And just to check @paujla - the bean is Kotlin `data class`?

**Comment by paujla** [comment]
Hi @igr,

Yes sorry I did not mention that the bean is a Kotlin data class.

**Comment by paujla** [comment]
Also i'm using the following version of postures driver 9.4.1208

**Comment by igr** [comment]
One question: is your data bean named upon your table name? Since you dont use annotations, are you sure that if you have table:

    SOME_TABLE

that your bean is named:

    SomeTable

Can you please give me similar names of bean and table that you are using? That might be one of the reasons why this fails - naming convention.

**Comment by paujla** [comment]
Hi @igr,

The table name is some_table and the bean name is SomeTable. The table name is not upper cased.

**Comment by igr** [comment]
One last question please: if you put annotations like this:

    @DbTable("tester")
    data class Tester33(@DbId val id: Long, @DbColumn val name: Status33, @DbColumn val value: Int)

where you put explicit table name in `@DbTable` and mark other values with `@DbColumn` - would it work in that case?

This is just to test if naming convention is an issue...

**Comment by igr** [comment]
In other words, this is what I do for postgres before I use it:

      DbOomManager.getInstance().getTableNames().setLowercase(true);
      DbOomManager.getInstance().getColumnNames().setLowercase(true);

**Comment by paujla** [comment]
Hi @igr,

The following code:

```java
DbOomManager.getInstance().getTableNames().setLowercase(true);
DbOomManager.getInstance().getColumnNames().setLowercase(true);
```

has fixed everything.

Thank you for mentioning that important piece of configuration setup knowledge.

**Comment by igr** [comment]
Great, glad it worked @paujla !!!

This is common issue and it is not easy for users to figure what is going on... My plan is to have this pre-defined for different database so they are set automatically by default, depending on detected DB.


Thank you again!

**Comment by igr** [comment]
Just FYI: after #401 you can say:

    DbDetector.detectDatabaseAndConfigureDbOom(connectionProvider)

and it will tweak these little changes to match database.
