### ISSUE TITLE
jodd-mail AutoClosable SendMailSession

### ISSUE THREAD

**Issue by JensPiegsa** [oblac/jodd#402]
The documentation states:

> Since opening session and sending emails may produce EmailException, it is necessary to wrap methods in try-catch block and closing the session in the finally block.

So I end up with:

```
SendMailSession session = null;
String messageId = null;

try {
    session = smtpServer.createSession();

    session.open();

    messageId = session.sendMail(email);

} catch (final MailException e) {
    // process exception
} finally {
    if (session != null) {
        try {
            session.close();
        } catch (MailException e) {
            // process exception
        }
    }
}
```

I wonder whether there is a way to make `SendMailSession` implement `java.lang.AutoCloseable` to simplify the code to:

```
String messageId = null;

try (SendMailSession session = smtpServer.createSession()) {
    messageId = session.sendMail(email);
} catch (final MailException e) {
    // process exception
}
```

Is this possible and what is your opinion?

**Comment by igr** [comment]
You are right.
Just one note: you don't need the last `try`/`catch`, for `close()` as it does not throw.

Doing right now.

**Comment by igr** [comment]
Closed by 77d62f34d06981ec2e842afb803761c38351710c

**Comment by igr** [comment]
Thank you @JensPiegsa !!!!

**Comment by JensPiegsa** [comment]
@igr Great. Thank you. :-)
