### ISSUE TITLE
ClassUtil invoke methods are mess

### ISSUE THREAD

**Issue by igr** [oblac/jodd#403]
There are too many variants, its hard to track. Replace with a simple fluent builder.

**Comment by neroux** [comment]
From what I can tell it appears they are shorthand methods for their `Method` equivalents and don't add own logic or abstraction.

Could they be possibly removed altogether and their use in `ProxettaAsmUtil.visitElementValue()`, `WebRunner.runWebApp()`, and `ObjectUtil.clone()` being replaced with direct `Method` calls?

**Comment by igr** [comment]
That is very good point @neroux!

Let me check again; I am sure there are some other similar 'dummy' utilities that make no sense to exist and really does not help much.
