### ISSUE TITLE
Jodd.http block problem

### ISSUE THREAD

**Issue by account4matt** [oblac/jodd#405]
Hi,
When I request url with Jodd.http, sometimes it will blocked at the send method.
```
HttpRequest request = HttpRequest.get("http://api.sssssss.com/aaa.json").connectionTimeout(2000);
            HttpResponse response = request.send();
```

jstack info: 
the thread has been blocked  2 days:
```
"pool-2-thread-3" #48 prio=5 os_prio=0 tid=0x000000005afad800 nid=0x1d18 runnable [0x000000005f93e000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:150)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x00000000daf4ec58> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	- locked <0x00000000daf4ec58> (a java.io.InputStreamReader)
	at jodd.io.StreamUtil.copy(StreamUtil.java:170)
	at jodd.http.HttpBase.readBody(HttpBase.java:895)
	at jodd.http.HttpResponse.readFrom(HttpResponse.java:223)
	at jodd.http.HttpRequest._send(HttpRequest.java:759)
	at jodd.http.HttpRequest.send(HttpRequest.java:742)

```

**Comment by igr** [comment]
Hey @account4matt! Thank you for this report, lets see what we can do. Jodd HTTP just uses underlying Java socket engine, so it can't do much. You might trying using also `timeout()`, but I don't expect any difference. Maybe the server holds the connection and sends packets to client from time to time for 2 days -> so client thinks he is still active?

The only way we can do is to add the third timeout, i.e. `clientTimeout` with our custom connection monitoring. I am willing to add that, of course; just want to be sure what is the reason why the reading is locked and not time-outed....

**Comment by neroux** [comment]
@igr 👍 

Without further details it is impossible to say what the problem could be and if there is one at all. It seems to be stuck at reading the response body and that might be easily server-side related.

**Comment by igr** [comment]
Some random notes on subject...

> One of the major shortcomings of the classic blocking I/O model is that the network socket can react to I/O events only when blocked in an I/O operation. When a connection is released back to the manager, it can be kept alive however it is unable to monitor the status of the socket and react to any I/O events. If the connection gets closed on the server side, the client side connection is unable to detect the change in the connection state (and react appropriately by closing the socket on its end).

> The only feasible solution that does not involve a one thread per socket model for idle connections is a dedicated monitor thread used to evict connections that are considered expired due to a long period of inactivity. The monitor thread can periodically call `closeExpiredConnections()` method to close all expired connections and evict closed connections from the pool...

Using non-blocking API is also a solution, so no thread will be blocked. Still, idle connection has to be "cleared".

**Comment by neroux** [comment]
@igr As I understand that paragraph it refers to open but unused/idle connections, where neither a read nor a write is taking place. In that case that scenario wouldnt even be specific to blocking operations, but would apply to asynchronous code too.

**Comment by igr** [comment]
@neroux that is true. just wanted to put some 'relevant' information here, in case we get more info. Async connection would block, but no thread would be used to wait for it...

Now thinking (off topic), maybe we can add non-blocking send&receive that works with `CompletableFuture`...

**Comment by neroux** [comment]
Correct me if I missed something, but in a synchronous context a thread wouldnt block either, simply because it is not waiting for anything. If it is it is most likely reading and in that case the regular timeout would come into play.

**Comment by igr** [comment]
@neroux but isn't the thread that was using the http client blocked, in case of synchronous context? The users thread waits until the read is done; and in above case it never ends (as reported); hence the user thread is blocked?

Lets see if we get more info :))))))))

**Comment by neroux** [comment]
True, but in that case there is a blocking IO operation going on, to which `timeout()´ will apply.

The paragraph was referring to open connections without any communication

> One of the major shortcomings of the classic blocking I/O model is that the network socket can react to I/O events only when blocked in an I/O operation. When a connection is released back to the manager, it can be kept alive however it is unable to monitor the status of the socket and react to any I/O events. If the connection gets closed on the server side, the client side connection is unable to detect the change in the connection state (and react appropriately by closing the socket on its end).

In @account4matt's case I **believe** it might be simply either because there is no timeout set in the first place or because - as you mentioned - there are regularly bytes dripping in from the server. Believe in bold, because without further information it is all just speculation :)

**Comment by igr** [comment]
True true @neroux :)

**Comment by igr** [comment]
Closing this; not sure what we can do about it; its all in the underlying layers.
