### ISSUE TITLE
how to send email with certificate

### ISSUE THREAD

**Issue by archer-christ** [oblac/jodd#406]
```
jodd.mail.MailException: Failed to connect; <--- javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at jodd.mail.SendMailSession.open(SendMailSession.java:78)
```

the mail server needs certificate to ssl , how to config certificate with SmtpSslServer I cannot found the doc ?

**Comment by igr** [comment]
Heya @archer-christ !

Are you sure you talk to correct HTTPS port? This error may occur if you are talking to an HTTP server, not an HTTPS server; i.e. if you are not talking to right port.

Also, check `plaintextOverTLS` and `startTlsRequired` methods of `SmtpSslServer`.

It would be superb if you can send more info; try private email if some data are sensitive :)

**Comment by igr** [comment]
Heya @archer-christ , any update on this?

**Comment by igr** [comment]
Closing - not having enough information. Please reopen if you find this issue still relevant. Thanx!
