### ISSUE TITLE
Jodd-mail: consider returning empty arrays or collections instead of null

### ISSUE THREAD

**Issue by PascalSchumacher** [oblac/jodd#414]
As suggested in Effective Java: "Return empty arrays or collections, not nulls".

In my opinion this would make the great jodd-mail API even more convenient to use.

By the way: Thanks for providing jodd! :+1:

**Comment by igr** [comment]
You are right. I prefer that as well, don't know why I am returning `null` anyways :) I will try to fix this accross the libaries.

**Comment by PascalSchumacher** [comment]
Thank you very much!

**Comment by igr** [comment]
No problem :) Thank you for reporting this!
