### ISSUE TITLE
Written and built with java8 can not be used on android

### ISSUE THREAD

**Issue by kwf2030** [oblac/jodd#415]

**Comment by igr** [comment]
True. Also, there are some usages of JDK that do not exist in Android (ah, Google :).

However, I am not sure how can I support Android. I would love to, but it is too much work to maintain two parallel set of libraries.

Only if I find a VC who would love to invest 💰 in Jodd :)))

**Comment by kwf2030** [comment]
I tried to replace all java8 features and compiles with java7 for core and mail, used it on android, no problems so far.

**Comment by igr** [comment]
You might be right... the `core`, `mail`, `json` may be rather easy to backport...

**Comment by kwf2030** [comment]
thanks very much for your perfect jodd

**Comment by restmad** [comment]
is plugin 'me.tatarka.retrolambda' gonna help?

**Comment by igr** [comment]
@restmad @kwf2030 if something like that retrofiting tool helps, I would be super happy :) Because we simply do not have resources to maintain android at the moment

**Comment by neroux** [comment]
Starting with Android Studio 3 Java 8's features should be mostly supported, particularly Lambdas

https://developer.android.com/studio/write/java8-support.html

**Comment by igr** [comment]
Great news @neroux !

(it was about the time;)
