### ISSUE TITLE
Lagarto performance optimisation

### ISSUE THREAD

**Issue by ljwagerfield** [oblac/jodd#419]
Lagarto currently creates an internal text buffer (`char[]`) for building up text that gets sent to the `text(text: CharSequence)` callback.

It would be great to avoid uneccessary memory allocation / copying with something like the following:

Have the option to _disable_ this internal buffer so that _no array copying / creation_ ever occurs, and to provide a `text(position: Int, length: Int)` just like you do for `Tag`.

Would this be possible?

Great project guys, keep it up! 😄

**Comment by igr** [comment]
First of all, sorry for a terrible late response :) It happened that we are doing exactly what you said, so I forgot to answer :))) Let me explain:

[This method](https://github.com/oblac/jodd/blob/master/jodd-lagarto/src/main/java/jodd/lagarto/Scanner.java#L146) is responsible for emitting the `CharSequence`. As you can see, there is a flag `emitStrings` that controls if real strings are created or not.

When you know that your code will not use that much strings, or you don't have much visitors, you may turn off this flag to `false` (by default is `true`). When you do that, string will not be created, but the `CharBuffer.wrap()` will be used instead. This returns a `CharBuffer` that does not allocate new `char[]`. 

I remember I had tests, so when using just Lagarto, this made a significant difference. However, if you use LagartoDOM, when everything is stored as a string, this flag simply didn't work, in fact, I believe the results would be even worst. Hence, it depends on a usage.

Now, I guess we could even get more speed with custom and simpler implementation of the `CharSequence`. So let me first write a performance test :)))

**Comment by igr** [comment]
Hm seems that Java8 really get Strings right:

```
EmitStringsBenchmark.lagartoDomBuilder    thrpt   10  5248.513 ± 184.445  ops/s
EmitStringsBenchmark.lagarto_emitStrings  thrpt   10  9330.331 ± 371.662  ops/s
EmitStringsBenchmark.lagarto_noStrings    thrpt   10  9314.819 ± 331.035  ops/s
```

The flag I was talking about now really has no influence.

**Comment by slandelle** [comment]
Beware that Java9's new String implementation might really be a game changer when it comes to parsers.

**Comment by igr** [comment]
@slandelle yeah, you just got me while thinking to even remove this optimization...

I will try now tests with super-lightweight `CharSequence` implementation...

**Comment by igr** [comment]
Wow, the best what I could come with is the:

```
Benchmark                                  Mode  Cnt     Score     Error  Units
EmitStringsBenchmark.lagarto_emitStrings  thrpt   10  8937.081 ± 352.528  ops/s
EmitStringsBenchmark.lagarto_noStrings    thrpt   10  8807.884 ± 234.362  ops/s
```

In other words: nothing. Even though the string is created, it seems there is no need for this kind of optimization anymore.

(I am almost 100% sure this was not the case back then, on Java7 - hence I added the flag)

**Comment by igr** [comment]
It even seems that emitting strings is faster.

```
EmitStringsBenchmark.lagartoDomBuilder    thrpt   10  5084.617 ± 226.569  ops/s
EmitStringsBenchmark.lagarto_emitStrings  thrpt   10  9591.559 ± 336.948  ops/s
EmitStringsBenchmark.lagarto_noStrings    thrpt   10  9054.000 ± 394.457  ops/s
```

### Resolution

Remove `emitString` and always emit strings. Performance tests does not show any difference - in fact, results are even somewhat better with emitting strings.

**Comment by igr** [comment]
I removed this changed from the Milestone, but I will add it right after the next version is released.

**Comment by igr** [comment]
However:

```
CharSequenceBenchmark.createCharBuffer      32  avgt    5     8.437 ±   0.446  ns/op
CharSequenceBenchmark.createCharBuffer     128  avgt    5     8.344 ±   0.144  ns/op
CharSequenceBenchmark.createCharBuffer    1024  avgt    5     8.410 ±   0.617  ns/op
CharSequenceBenchmark.createCharBuffer   32768  avgt    5     8.328 ±   0.306  ns/op
CharSequenceBenchmark.createString          32  avgt    5    14.787 ±   0.767  ns/op
CharSequenceBenchmark.createString         128  avgt    5    27.355 ±   3.289  ns/op
CharSequenceBenchmark.createString        1024  avgt    5   184.647 ±  16.658  ns/op
CharSequenceBenchmark.createString       32768  avgt    5  5929.545 ± 560.461  ns/op
```
so something has to be done here, although tests using lagarto does not reflect this big change - maybe because all the strings are small.

Hey @ljwagerfield do you think using `CharBuffer` would make sense? Since it is a class that does not allocate anything, its just a 'window' in the char array.

**Comment by igr** [comment]
I will close this and not resolve. The flag `emitString` should be enough here:

+ when set to `false`, Lagarto emits `CharBuffer`, which operates on original array
+ when set to `true`, Lagarto emits `String`.

**Comment by ljwagerfield** [comment]
Sorry for the late reply.

Yes, I think that would make sense.

If nothing more, it's consistent with how the rest of the Lagarto methods work.

When you're processing many files in parallel, over a long period of time, I'd expect the gains to be noticeable.
