### ISSUE TITLE
HttpRequest can not handle url contain space

### ISSUE THREAD

**Issue by wenerme** [oblac/jodd#422]
`HttpRequest.get("http://localhost?name=a  b")` will failed, path may contain space, too .`HttpRequest.get("http://localhost/a b/?name=a  b")`

**Comment by neroux** [comment]
#394
A space is not a valid character and needs to be encoded

**Comment by wenerme** [comment]
But how ? Browser can handle this, why not jodd, is jodd for things like this ?

I manually get the query string, then `HttpUtil.parseQuery`, `HttpUtil.buildQuery` to rewrite the url.

The url is get from html a href by Jerry

**Comment by neroux** [comment]
The browser handles it by additionally encoding such characters.

Could you post a sample code? `buildQuery` should actually handle that fine.

**Comment by wenerme** [comment]
This only handle query string contain space

```
  public String spaceInQueryString(String url) {
    int i = url.indexOf('?');
    if (i > 0) {
      String qs = HttpUtil.buildQuery(HttpUtil.parseQuery(url.substring(i + 1), false), "UTF-8");
      return url.substring(0, i + 1) + qs;
    }
    return url;
  }
```

**Comment by neroux** [comment]
You'd need to post sample code where you encounter the issue. The code you posted is not space-related and actually handles them fine.

Which version are you using?

**Comment by neroux** [comment]
Yo need to make sure to pass a valid URL properly, especially when you use Unicode characters.

**Comment by wenerme** [comment]
This should be fixed in latest version by checking the http method. 👍
