### ISSUE TITLE
HttpBase leaking its header object

### ISSUE THREAD

**Issue by neroux** [oblac/jodd#426]
Shouldn't [`HttpBase.headers()`](https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpBase.java#L195) return a clone of `headers` instead of the actual object?

**Comment by igr** [comment]
I might even start to think not to have that one at all, especially after latest changes. I think I will remove it.

In general, the approach in Jodd is that sometimes we do allow to 'leak' internal structures, for the sake of performances. We are expecting that users will be aware of what they are doing, i.e. not trying to make everything fool-proof. Maybe we should document this more :)

Anyhow, in this place, I think we can even remove headers, and even make `HeaderTuple` package-level class, so not to be seen and used outside of the Http package.

wdyt?

**Comment by igr** [comment]
Added `headerNames()`. Didn't like the exposure of `HeaderTuple` :))
