### ISSUE TITLE
Automate travis integration tests and publishing code coverage to Coveralls

### ISSUE THREAD

**Issue by igr** [oblac/jodd#429]

**Comment by igr** [comment]
Done. However, coveralls shows rubbish:

https://github.com/lemurheavy/coveralls-public/issues/1011

**Comment by igr** [comment]
bye coveralls, hi codecov

https://github.com/oblac/jodd/pull/430

**Comment by MacHu-GWU** [comment]
Does that mean coveralls (python) are not supported anymore? but using codecov instead?

**Comment by igr** [comment]
Hey @MacHu-GWU, I can't speak for the Coveralls, but my decision was made because of the following:

+ Coveralls was not showing results for my latest master change for long time
+ The source information on Coveralls was some python files, totally not Jodd
+ Codecov on the other hand was super easy to install: it worked from the very first moment!
+ Like codecov ui better.

SO, from now on, Jodd is fully tested (including the integration tests) and you can see code coverage on Codecov: https://codecov.io/gh/oblac/jodd

Yeah, need to tweak results a bit, but it worked very smooth.
