### ISSUE TITLE
Proxetta has problems with return value 'List<Map<String, Object>>'

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#431]
Hi,

there is a huge issue with proxetta and returning `List<Map<String, Object>>` in current jodd version 3.9 .

current situation:
deploying application in Apache TomEE , call jsp page, execute sql statement (example select 1).
with version 3.8.6 - no error occurs.

with version 3.9 following exception is logged:

> javax.ejb.EJBException: The bean encountered a non-application exception; nested exception is: 
> 	java.lang.NoClassDefFoundError: java/util/List>
> 	at org.apache.openejb.core.ivm.BaseEjbProxyHandler.convertException(BaseEjbProxyHandler.java:427) ~[openejb-core-4.7.4.jar:4.7.4]
> 	at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:329) ~[openejb-core-4.7.4.jar:4.7.4]
> 	at com.sun.proxy.$Proxy169.select(Unknown Source) ~[na:na]
> 	at de.xxx.web.servlet.SqlServlet.perform(SqlServlet.java:145) [classes/:na]
> 	at de.xxx.web.servlet.SqlServlet.doGet(SqlServlet.java:75) [classes/:na]
> 	at de.xxx.web.servlet.SqlServlet.doPost(SqlServlet.java:64) [classes/:na]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650) [servlet-api.jar:na]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) [servlet-api.jar:na]
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.68]
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.68]
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.68]
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.68]
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.68]
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.68]
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.68]
> 	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44) [tomee-catalina-1.7.4.jar:1.7.4]
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) [catalina.jar:7.0.68]
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) [catalina.jar:7.0.68]
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.68]
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) [catalina.jar:7.0.68]
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.68]
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436) [catalina.jar:7.0.68]
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078) [tomcat-coyote.jar:7.0.68]
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625) [tomcat-coyote.jar:7.0.68]
> 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318) [tomcat-coyote.jar:7.0.68]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.68]
> 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
> Caused by: java.lang.NoClassDefFoundError: java/util/List>
> 	at de.xxx.system.systemservice.dao.impl.SystemServiceDAO$$Proxetta.select$1(Unknown Source) ~[na:na]
> 	at de.xxx.system.systemservice.dao.impl.SystemServiceDAO$$Proxetta.select(Unknown Source) ~[na:na]
> 	at de.xxx.system.systemservice.service.impl.SystemServiceService.select(SystemServiceService.java:44) ~[classes/:na]

I think this issue is linked to issue #418 and the cause is the case if more than one generic is given back.

Can you reproduce it?

Bye,
Sascha

**Comment by moh-sushi** [comment]
Further investigation:

Exception occurs if the method has a custom `ProxyAdvice`.

Well, my custom `ProxyAdvice` is following one:

```
public class PerformanceMeasureProxyAdvice implements ProxyAdvice {

    @Override
    public Object execute() throws Exception {
        ProxyTargetInfo proxyTargetInfo = ProxyTarget.info();
        final long start = System.currentTimeMillis();

        PerformanceData.Builder builder = PerformanceData.newBuilder();

        builder
                .withBegin(start)
                .withTargetClazz(proxyTargetInfo.targetClass)
                .withTargetMethodName(proxyTargetInfo.targetMethodName)
                .withArgumentsClasses(proxyTargetInfo.argumentsClasses);

        try {
            return ProxyTarget.invoke();
        } catch (Exception e) {
            throw e;
        } finally {
            final long end = System.currentTimeMillis();
            builder.withEnd(end);
            PerformanceLoggingUtil.log(builder.build());
        }
    }
}
```

I have read in changelog that MethodInfo has been breaking changes.
Are these changes relevant?!

**Comment by igr** [comment]
Damn, will take a look!

**Comment by igr** [comment]
At least the refactored code looks beautiful :)))

No worries, I will take a look ASAP.

**Comment by moh-sushi** [comment]
> @moh-sushi would you be so kind to check if the fix really fixes?

I will try to test current snapshot version tomorrow und give feedback.

Thanx for this really quick fix :-)

**Comment by igr** [comment]
Hey, no worries, take you for your time! Its was really stupid bug (i hope).

**Comment by moh-sushi** [comment]
Test with snapshot-version was successful :-)
fyi : snapshot - version was based on commit [b258ff3](https://github.com/oblac/jodd/commit/b258ff32f9056c966e1fbd1d7029482a647cae0f).

**Comment by igr** [comment]
Awesome @moh-sushi!
I will release the patch over the weekend, just to add one more little fix.
