### ISSUE TITLE
I used jodd-http   post data and did not get body.  Thank you

### ISSUE THREAD

**Issue by esionchiu** [oblac/jodd#433]
Hello,I am having a problem,tossing for two days without finding the answer, please give help. Thank you
I used jodd-http   post data and did not get body.
the web ajax Code:

function GetCaptcha () {
         $ .ajax ({
             url: "/ Account / Captcha",
             data: {CaptchaError: "False"},
             type: 'POST',
             success: function (data) {
                 $ ("# captch"). html (data);
                 $ ("# captchRefresh"). hide ();
             },
             error: function () {
                 $ ("# captchaloading"). text ("Verification code failed");
                 $ ("# captchRefresh"). show ();
             }
         });
     }

How can I use jodd-http to solve this problem? Thank you.

and my Email  250013000@qq.com  ,Thank you.

**Comment by restmad** [comment]
jodd post不是java后端请求么？你这放个javascript代码做什么呢？
如果是jodd-post来代替请求验证码的话，你得看下Header信息是否需要其他额外的东西，在jodd-post的时候赋值一下。

**Comment by igr** [comment]
Hey @esionchiu this looks like javascript to me? How did you use the jodd-http?

**Comment by esionchiu** [comment]
@restmad 是这样的,我用jodd-http模拟登陆的时候需要获取一个验证码,但是是异步post,每次提交完数据后,只得到了response的headers,而body则是null. 
下面是我的部分代码,
`private void test() {
        HttpRequest request = HttpRequest.get(LogonPane.PANE.getUrl()).charset("utf-8");
        browser.sendRequest(request);

        request.path("/Account/Login/").method("GET");
        //  request = HttpRequest.get(this.url_host + "/Account/Login/");
        browser.sendRequest(request);

        request.path("/Account/Captcha").method("POST").body("{CaptchaError:'False'}")
                .accept("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
                .header("X-Requested-With", "XMLHttpRequest");

        browser.sendRequest(request);

        System.out.println(browser.getPage());
    
        //System.exit(0);
    }`

谢谢

**Comment by esionchiu** [comment]
@igr 
对不起我昨天没有表达清楚,我用jodd-http POST 数据,只得到了response headers,并没有得到body,或者是因为异步POST?
我的代码:
'private void test() {
        HttpRequest request = HttpRequest.get(LogonPane.PANE.getUrl()).charset("utf-8");
        browser.sendRequest(request);

        request.path("/Account/Login/").method("GET");
        //  request = HttpRequest.get(this.url_host + "/Account/Login/");
        browser.sendRequest(request);

        request.path("/Account/Captcha").method("POST").body("{CaptchaError:'False'}")
                .accept("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
                .header("X-Requested-With", "XMLHttpRequest");

        browser.sendRequest(request);

        System.out.println(browser.getPage());
    
        //System.exit(0);
    }'

**Comment by esionchiu** [comment]
@igr 
Sorry i did not express it yesterday, i used jodd-http POST data, got only the response headers, did not get body, or because of asynchronous POST?
My code:
'private void test () {
         HttpRequest request = HttpRequest.get (LogonPane.PANE.getUrl ()). Charset ("utf-8");
         browser.sendRequest (request);

         request.path ("/ Account / Login /") method ("GET");
         // request = HttpRequest.get (this.url_host + "/ Account / Login /");
         browser.sendRequest (request);

         request.path ("/ Account / Captcha"). method ("POST"). body ("{CaptchaError: 'False'}")
                 .accept ("text / html, application / xhtml + xml, application / xml; q = 0.9, * / *; q = 0.8")
                 .header ("X-Requested-With", "XMLHttpRequest");

         browser.sendRequest (request);

         System.out.println (browser.getPage ());
    
         //System.exit(0);
     } '

**Comment by restmad** [comment]
抓包看下对方服务器还需要哪些头信息，一般服务器端都会做过滤的。

**Comment by esionchiu** [comment]
@restmad 我把所有的网页头都填写上了.还是取不到body

**Comment by esionchiu** [comment]
@restmad 请问这个是因为异步提交的原因吗?我实在查不出来哪里出了问题.或者您方便的话,能否加一下我QQ?  250013000 .谢谢

**Comment by neroux** [comment]
@esionchiu English might get you better responses ;)

**Comment by esionchiu** [comment]
@neroux Thank you for my friend, this problem I have not been resolved. I would like to get this URL verification code ('https://oebet.cc/'), but I tried for a long time, always get no body. I do not know where the problem is in my code .
`HttpRequest request = HttpRequest.get(url);
        browser.sendRequest(request);

        request.path("/Account/Login/").method("GET").acceptEncoding("gzip, deflate, br")
                .header("Upgrade-Insecure-Requests", "1");

        browser.sendRequest(request);

        request.path("/Account/Captcha")
                .method("POST")
                .accept("*/*")
                .body("CaptchaError=False")
                .contentType("application/x-www-form-urlencoded", "UTF-8")
                .acceptEncoding("gzip,deflate,br")
                .header("X-Requested-With", "XMLHttpRequest");

        browser.sendRequest(request);
        
        System.out.println(browser.getHttpResponse());`

**Comment by neroux** [comment]
If you want to submit a form you can use `form()` to add the parameters without doing it manually.

What do you mean by you dont get a body? What does the response contain? I'd print out the request object to check whether it is in the expected format and work from there.

**Comment by igr** [comment]
@esionchiu Response looks like this:

```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Accept
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store
Connection: close
Content-Length: 0
Date: Tue, 19 Sep 2017 12:05:08 GMT
Expires: Tue, 19 Sep 2017 12:05:07 GMT
Server: Microsoft-IIS/6.0
Set-Cookie: .ASPXBrowserOverride=; expires=Mon, 18-Sep-2017 12:05:08 GMT; path=/
```

As you can see, there is simply NO body in the response - the `content-length` is zero.

This doesn't look as the issue of `jodd-http`. I will check the javascript code to see if the behavior is the same.

**Comment by esionchiu** [comment]
@neroux
@igr
thanks, i got the same result.

**Comment by igr** [comment]
Ok, you have to be careful when you want to repeat the browser behavior. Delete all the cookies and the cache. Call a page, and you will see this:

<img width="344" alt="all-calls" src="https://user-images.githubusercontent.com/2280001/30598773-fad4e942-9d5a-11e7-80c5-58623583bef6.png">

So there are more than two requests. Also, note that:

+ you are not using `form()`, as @neroux said
+ you are not using `HttpBrowser` with a new request every time.

This works:

```java
		HttpBrowser browser = new HttpBrowser();

		browser.sendRequest(HttpRequest
			.get("https://www.oebet.cc")
			.path("/Account/Login/"));

		browser.sendRequest(HttpRequest
			.get("https://www.oebet.cc")
			.path("/Account/Login/")
			.header("referer", "https://www.oebet.cc/login.php"));

		browser.sendRequest(HttpRequest
			.post("https://www.oebet.cc")
			.path("/Account/Captcha")
			.form("CaptchaError", "False")
			.acceptEncoding("gzip,deflate,br")
			.header("referer", "https://www.oebet.cc/Account/Login/"));

		System.out.println(browser.getHttpResponse().getHttpRequest().toString(true));
		System.out.println("---------------------------------");
		System.out.println(browser.getHttpResponse().unzip());
```

**Comment by igr** [comment]
No Jodd issue here, closing the comment.

**Comment by igr** [comment]
p.s. maybe sending 'referer' was not needed, just check by yourself the rest ;)

**Comment by esionchiu** [comment]
@igr Thank you my friend,I got it!!!

**Comment by igr** [comment]
No worries - just tell everyone how Jodd is a cool project :)

**Comment by esionchiu** [comment]
是的，我最近一直在学习使用它，它确实很酷！谢谢

**Comment by esionchiu** [comment]
Yes, I've been learning to use it recently, it's really cool! Thank you

**Comment by restmad** [comment]
@esionchiu 哥们，搞菠菜风险有点高，建议早点远离。
