### ISSUE TITLE
SuperUtil class

### ISSUE THREAD

**Issue by igr** [oblac/jodd#434]
Separating utilities in different *Util classes is somewhat ugly. I was thinking of adding one, single, **Super** util class that user can simply import statically and that's it - all methods are there. signatures and method names would be enough...

Just thinking...

**Comment by restmad** [comment]
i don't think this is a good idea.
i will create a util class for a project, using part of jodd.
i think it's unnecessary to create a super all in one util class in jodd.

**Comment by neroux** [comment]
I'd tend to side with @restmad on this. It certainly depends a lot on what should be merged but I'd avoid smashing together helper functions from different areas just because they might be a _helper_ function.

Would you have some examples of what you wanted to merge @igr?

**Comment by igr** [comment]
I feel like you guys, more-less. But from time to time I get the same idea all over again:

There are many little simple java utilities in `jodd-core`. For example, if I write code that has to deal with array and to convert it to e.g. `List` - should I use: `ArrayUtil` or `CollectionUtil`? Then, I have to convert a String to some type. Should I call `StringUtil` or that `Convert...` (forgot the name atm:)

I thought of an inverse approach. Instead of learning which `*Util` class user has to import, we can provide one class, `JavaJodd` or `JavaFix` or `Java`, that only contains static methods. Once when you import static all methods, you can simply start typing in your IDE _what you need_. In other words, method names would be descriptive and tuned for fast autocomplete.

More important is that same method name may be used in different context _in the same way_:

    sub(String, 1, 3);
    sub(array, 1, 3);

so we could have same methods, same behavior, same tweaks, same names for different contexts. You no longer don't care what the real class name, you just need to call a function, i.e. a static method.

This util class would be **only** for Java related utilities - it would merge e.g. `StringUtil`, `ArrayUtil`, `ClassUtil` and similar, low-level utilities, all from `jodd-core`.

And then, I do not see any big drawback in having one such big class?

WDYT?

**Comment by neroux** [comment]
As for the naming part, I'd usually go for the place of origin. If I want to convert an array, I'd go for "_ArrayUtil_".

That being said, your reverse approach doesnt sound bad either. Maybe I wouldnt stuff everything into one giant class but have several different _helper_ classes with static-only members, based on their primary use (e.g. `ConvertUtil` for all sorts of conversion, `MergeUtil` for merging, etc.).

These are just ideas of course and it will come down to real-life examples.

As these classes are _Jodd's little helpers_ I'd propose for a package name `jodd.elves.*` :grinning:

**Comment by igr** [comment]
One question: how do you guys usually call static util methods:

1. Using class name, e.g. `StringUtil.substring()`.
2. Using statically imported method name: `substring()`

**Comment by neroux** [comment]
I usually prefer the class name over static imports.

**Comment by restmad** [comment]
className.methodName(args...)

**Comment by igr** [comment]
Thanx guys!

I am sometimes over-obsessed with having more and more efficient dev environment
