### ISSUE TITLE
Got a weird exception: java.lang.NumberFormatException: For input string: "0;"

### ISSUE THREAD

**Issue by binarywang** [oblac/jodd#435]
Hello, everyone ,
I am using the latest version of jodd-http 3.9.1.
It has bean working well all the time until I sent a request to some url, but got this exception:
```
"java.lang.NumberFormatException: For input string: "0;"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at jodd.http.HttpBase.readBody(HttpBase.java:892)
	at jodd.http.HttpResponse.readFrom(HttpResponse.java:227)
	at jodd.http.HttpRequest._send(HttpRequest.java:831)
	at jodd.http.HttpRequest.send(HttpRequest.java:814)
```
When I debug the code , I found that's because of `Content-Length: 0;` in the response below:
```
HTTP/1.1 307 Temporary Redirect
Cache-Control: no-cache
Connection: Close
Content-Length: 0;
Content-Type: text/html; charset=UTF-8;
Pragma: no-cache
Set-Cookie: SESSIONID=ahyuotdnzrsrpclw
```
Any idea on how to fix this?

**Comment by restmad** [comment]
is 307 redirect response header have Location?
if there's location value, maybe you can use status code to solve this redirect problem.
`HttpRequest request = HttpRequest
        .get("http://localhost:8080/test_hello_javaweb/Hello2");
		request.form("auth", "ac9fc9f7-d1bb-4525-85a4-e105d54dbd5d");
		HttpResponse response = request.send();
		System.out.println(response);
		System.out.println("url: " + request.url());
		final int MAX_REQUEST_TIMES = 10;
		int index = 0;
		URL url = null;
		try {
			url = new URL(request.url());
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		if(url != null) {
			while((response.statusCode() == 302 || response.statusCode() == 307) && (index++) < MAX_REQUEST_TIMES) {
				String newLocation = response.header("Location");
				if(!newLocation.startsWith("http")) {
					newLocation = url.getProtocol() + "://" + url.getHost().toString() + ":" + url.getPort() + "/" + newLocation;
				}
				System.out.println("new location: " + newLocation);
				response = request.post(newLocation).send();
			}
			
			System.out.println(response);
		}`

`HTTP/1.1 307 Temporary Redirect
Connection: close
Content-Length: 0
Date: Tue, 19 Sep 2017 02:37:25 GMT
Location: Hello
Server: Apache-Coyote/1.1


url: http://localhost:8080/test_hello_javaweb/Hello2
new location: http://localhost:8080/Hello
HTTP/1.1 404 Not Found
Connection: close
Content-Language: en
Content-Length: 1004
Content-Type: text/html;charset=utf-8
Date: Tue, 19 Sep 2017 02:37:25 GMT
Server: Apache-Coyote/1.1

<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.46 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /Hello</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/Hello</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.0.46</h3></body></html>
`

**Comment by binarywang** [comment]
Thanks @restmad , but no, there is no location, the whole information is above.
I can not even get the status code because the exception is thrown `at jodd.http.HttpRequest.send(HttpRequest.java:814)`, so I don't have the chance.

**Comment by neroux** [comment]
The response contains an invalid content length. It has to contain digits only. Who sends that response?

**Comment by binarywang** [comment]
it's someone else's, belonging to a third party which provides some service, so I can't manipulate it.

**Comment by neroux** [comment]
I'd still file it as a bug report with them. That syntax is plain invalid.

Until they fix it you could monkey patch [`HttpBase`](https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpBase.java#L892). Jodd is handling as it is supposed to though.

**Comment by binarywang** [comment]
Thanks @neroux .
I agree with you that the response is invalid. 
But what do you mean by saying "monkey patch" ?

**Comment by neroux** [comment]
https://en.wikipedia.org/wiki/Monkey_patch

You add a local version of HttpBase where you (hopefully) temporarily change the code in question. Once they fixed their code you can remove that code again.

**Comment by binarywang** [comment]
Okay, gotcha.
Thank you so much.

**Comment by igr** [comment]
Thanx @neroux for solving this! I would add at least a better exception message, so will do that now. Do you maybe think we should fix this special case? Somehow believe that this kind of issue may re-appear.

**Comment by neroux** [comment]
@igr Personally I think it should stay the way it is :). Why? Of course you can check and throw a more meaningful exception and of course you can strip out non-digits. But where would this exception handling stop? The RFC is pretty clear about the content of this field and Jodd handles it in the right way.

Babysitting external input should only go that far :)

**Comment by igr** [comment]
I agree, @neroux, you are right.

Well, at least a better message in the exception would not hurt :)

**Comment by igr** [comment]
Meanwhile, @binarywang just override the `contentLength()` method and filter out the `;` from the string. That should do it.

**Comment by binarywang** [comment]
That works for me, thank you @igr
