### ISSUE TITLE
Invalid javadoc bundle

### ISSUE THREAD

**Issue by FilipJirsak** [oblac/jodd#436]
All-in-one javadoc bundle (`jodd-all-3.9.1-javadoc.jar`) has invalid structure. There is every file name 18 times in the root of the jar file. For example there is 18 files named `index.html`, probably one file for one submodule. When you unpack javadoc jar file, all duplicite files are overwriten with one of them.

**Comment by igr** [comment]
Sorry @FilipJirsak for that :( We have migrated to Gradle 4.x recently and I guess some things changed. Will fix it!

You can see the javadoc api here: http://oblac.github.io/jodd-site/javadoc/ (if that helps somehow)
