### ISSUE TITLE
how to use jodd to download a .mp4 file or a .zip file throgh http or https

### ISSUE THREAD

**Issue by restmad** [oblac/jodd#437]
how to use jodd to download a .mp4 file or a .zip file throgh http or https

**Comment by moh-sushi** [comment]
Hi,

see [code snippet jodd #437](https://gist.github.com/moh-sushi/87655152f4f61d410a154c08159109dd) for small howto.

HTH,
Sascha

**Comment by restmad** [comment]
@moh-sushi good. thank you.

**Comment by igr** [comment]
Sorry @restmad for late response, I wanted to document this question to new FAQ page: https://jodd.org/http/faq.html

Using `bytes[]` would be a common way.

Please note that `sendTo()` sends the whole request, not just the body!

@moh-sushi thank you for jumping in and helping with the question!

**Comment by restmad** [comment]
@igr i know to use the bytes data. but I'm not sure if that's right, because the GFW block connection and i'm not sure it's a good idea to store all response data to byte[] data, because some mp4 movie file is big.
anyway, thanks a lot, and jodd is very useful.

**Comment by igr** [comment]
@restmad got it. I was just thinking today about that: to add a `bodyHandler()` that is going to receive data as it comes; so you can store it to some file.

e.g.:
```
.send(new BodyHandler() { })?
```
(of course, it would be a functional interface).

**Comment by igr** [comment]
However, that mix the request and response. Maybe it can be an option in `request` to produce a `response` that does not store anything in memory:

```
Response response = request.get()...sendAndReceive();

response.onHttpHeaders(...)
response.onBodyStart(...)
response.onBody()
response.onEnd();
```

i.e. to add callbacks for the events as they come. Need to find the right approach.

**Comment by restmad** [comment]
it will need read byte[] from connection inputstrea, then the callback handle it.
i think there may have some features as download.
1, it can pause or continue download file if previous connection broke.
2, multi thread download gonna help for big file? 
3, download manager class, useful, but maybe too much.

**Comment by igr** [comment]
Got it @restmad. Maybe then the `.download()` would be a nice new method to use instead of send() that will support all that. Like a small download manager.

**Comment by moh-sushi** [comment]
An option for `.download()` would be a nice feature.
Downloading files (regardless of type & size) is a case that the jodd http module should support in memory friendly manner :-)
