### ISSUE TITLE
Make some inter-module dependencies mandatory

### ISSUE THREAD

**Issue by igr** [oblac/jodd#444]
Some dependencies between Jodd modules are currently optional.

It happens in practices that ppl are really not using them as much separately, so to avoid additional optional configuration of modules, make them mandatory.

For example: madvoc and pettite with proxetta.

**Comment by igr** [comment]
Hey @moh-sushi one thing I need to review with someone.

Some modules have additional 'servlet'-related addons. For example, HTML parser has a JSP tag. So far, the servlet dependency of the servlet is optional. In other words:

    jodd-lagarto   ---depends_on-->     servlet (optional)

This happens for 3 jodd modules.

I would like to turn around this dependency. Therefore, I would move all servlet dependend code to the `jodd-servlet` library, making jodd modules optional instead. In other words:

    jodd-servlet   ---depends_on-->    jodd-lagarto (optional)

This way 3 libraries become "clean" without optional dependencies, and only one library, the servlet one, has optional dependencies.

wdyt?

**Comment by moh-sushi** [comment]
Hi @igr ,

as far as i understand you properly:

my concerns are that the jodd servlet module contains code that contains actual to another module because it is domain / module specific (e.g. jodd-lagarto).
In other words : the jodd-servlet module recieves code from "foreign" domains / modules.

**Comment by moh-sushi** [comment]
> `jodd-servlet   ---depends_on-->    jodd-lagarto (optional)`

Proper direction?
While reading your comment , my thought is :

` jodd-lagarto (optional)  ---depends_on-->   jodd-servlet`

**Comment by igr** [comment]
There is no need to depend on `jodd-servlet`, since it is not used. `jodd-lagarto` optionally depends only on servlets. You are right about the domain/module specific concerns, I share the same.

I just wanted to remove optional dependency, but the only proper way would be to add an additional module (e.g. jodd-lagarto-servlet) which I am not sure if I would add it right now (unless we split jodd into several pieces :)

**Comment by moh-sushi** [comment]
> You are right about the domain/module specific concerns, I share the same.

Glad to see that we are having the same concerns in this topic. 

If you really want to remove optional deps, i am okay with "jodd-lagarto-servlet" and similar modules.

Well, a short lock to e.g. spring-tx module.
It has [optional deps ](https://github.com/spring-projects/spring-framework/blob/master/spring-tx/spring-tx.gradle), too. 
If the optional deps are documented well, it is up to the user to ensure that these optional deps are available on classpath.

**Comment by igr** [comment]
Good. Thank you for sharing your thoughts, just need a sanity check :))
