### ISSUE TITLE
Replace all IOExceptions with UncheckedIOExceptions

### ISSUE THREAD

**Issue by igr** [oblac/jodd#446]
Simple change, but needs to be done on many methods (`FileUtil`...)

With Java8 there is `UncheckedIOException` I wish to use instead.

**Comment by moh-sushi** [comment]
What are your reasons for closing this issue?

Too much impact on API?

**Comment by igr** [comment]
Hey @moh-sushi !

The API impact is not the issue, as version 4 is already having a lot of changes anyway.  It is easy to implement as well.

I believe this change would be a good thing, but i really need here a second opinion :)

**Comment by igr** [comment]
Especially since v4 is almost ready to be released...

**Comment by igr** [comment]
Just figured that [Paths](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Paths.html) are throwing unchecked exceptions.

**Comment by igr** [comment]
Not true, false alarm. Let's leave it like it was.
