### ISSUE TITLE
Task 'jacocoReport' not found in root project

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#447]
Hi,

the instruction `gradlew jacocoReport ` from https://github.com/oblac/jodd/blob/master/CODE_COVERAGE.md procudes an error - see output from command line:
> > Configure project :
> 
>   Jodd 3.10-20171016
>   [snapshot]
> 
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Task 'jacocoReport' not found in root project 'jodd'.
> 
> * Try:
> Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s

**Comment by igr** [comment]
Thank you! That was old information, so now its updated. Also added atask to build coverage report for single module.
