### ISSUE TITLE
jodd-email linked on JavaMail - API - Third-Party Products

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#448]
Hi,
there is a page related to [ThirdPartyLibs](https://javaee.github.io/javamail/ThirdPartyProducts) based on JavaMail-API.

For now, you cannot find jodd-mail on this page :-(

Adding can be done through writing an email to javamail_ww@oracle.com.

Bye,
Sascha

**Comment by igr** [comment]
Thanx @moh-sushi, email sent!

**Comment by igr** [comment]
Unfortunately :(((

```
Final-Recipient: rfc822;<shreedhar.ganapathy@oracle.com>
Diagnostic-Code: 550 Requested action not taken: mailbox unavailable
Action: failed
Status: 5.0.0
```

**Comment by igr** [comment]
I've sent more emails; now Im a professional spammer ;)

https://javaee.github.io/javamail/ThirdPartyProducts

**Comment by moh-sushi** [comment]
> now Im a professional spammer

Good to know :-)))

jodd email is listed on top of the third party libs - yeah :-)
