### ISSUE TITLE
Streamline new runtimes and defaults

### ISSUE THREAD

**Issue by igr** [oblac/jodd#475]
Runtimes have static method `get()` to return an instance defined in module's runtimes.

+ [x] jodd-bean
+ [x] jodd-core
+ [ ] jodd-db
+ [x] jodd-decora
+ [x] jodd-htmlstapler
+ [x] jodd-http
+ [x] jodd-joy
+ [x] jodd-json
+ [x] jodd-jtx
+ [x] jodd-lagarto
+ [x] jodd-log
+ [x] jodd-madvoc
+ [x] jodd-mail
+ [x] jodd-petite
+ [x] jodd-props
+ [x] jodd-proxetta
+ [x] jodd-servlet
+ [x] jodd-upload
+ [x] jodd-vtor

**Comment by moh-sushi** [comment]
The check mark on jodd-db is still missing :wink:

**Comment by igr** [comment]
That one got away :))))
