### ISSUE TITLE
Stickers. Seriously.

### ISSUE THREAD

**Issue by igr** [oblac/jodd#486]
![jodd-sticker](https://user-images.githubusercontent.com/2280001/32368562-62f0f860-c086-11e7-9973-da474359f56d.jpg)

Dear contributors and supporters,

I would really like to **thank you** for your time that you invested in Jodd. Therefore, we have some Jodd stickers for you :) If you want some, just send an email to _info@jodd.org_ with your address (personal, business, relatives... whatever works for you:) and we will ship them during the next week!

## You are invited!

+ [x] @moh-sushi 
+ [ ] @neroux 
+ [ ] @zqq90 
+ [x] @slandelle 
+ [X] @vilmospapp 
+ [x] @pawelantczak 
+ [x] Ken Fogel
+ [ ] Philippe M.
+ [x] @raphw
+ [x] styx_hcr

(_the order of the list is not important_)

If you are not on the list and you know you should be: please excuse me and just ping me - it's really hard to track everything.

## Wanna a sticker or two?

If you are using Jodd in your project and want to get a cool sticker - just share with us how it is used and we will send the stickers right away :)

![jodd-sticers](https://user-images.githubusercontent.com/2280001/32404910-aa39817c-c15a-11e7-8dd1-72248cb2e37e.jpg)

## Note

_The number of stickers is limited._

**Comment by neroux** [comment]
Thanks a lot Igor, thats a kind offer.

:+1:

**Comment by pmouawad** [comment]
Thanks for the offer Igor ! Very nice. Although I am not sure to deserve it compared to other contributors.

**Comment by igr** [comment]
No worries @pmouawad... just by being there means a lot. It's super hard to code something not knowing if it really helps ppl, if it really brings value to their dev lives - because that is all that Jodd wants to achieve - to actually help.

Just send some address and we will be happy to send few stickers :)
