### ISSUE TITLE
how to get the response after multi redirect?

### ISSUE THREAD

**Issue by genericyzh** [oblac/jodd#487]
e.g. 
I send a request to A_url, A_url return 301/302 with B_url, and if send B_url then return 301/302 with C_url;
I just want to get the C_url response, how can I do?
It's a stupid way to get:
```
            HttpRequest httpRequest = HttpRequest.get(A_url);
            HttpResponse resp = httpRequest.send();
            HttpResponse resp2 = HttpRequest.get(resp.header("Location")).send();
            ...again and again
```

**Comment by igr** [comment]
You may use `HttpBrowser`:

https://jodd.org/http/faq.html#how-to-follow-multi-redirects

I will add a flag as well.

**Comment by igr** [comment]
See: https://github.com/oblac/jodd/commit/9c4c3a7182d215b6bae6ef548f0c9014e85be768
