### ISSUE TITLE
class JoddDbRuntime used?!

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#495]
Hi,

Is class `jodd.db.JoddDbRuntime` used?

Class is empty and i have not found any reference within code.

If class is not used anymore , it should be deleted.
If class is used, i suggest some javadoc :-)

Bye,
Sascha

**Comment by igr** [comment]
Will be removed! Just need to finish one refactoring on Petite!

Thank you for finding and reporting!!!
