### ISSUE TITLE
DbUtil#setPreparedStatementObject if value is null

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#505]
Hi,

i have a question regarding the method in `jodd.db.DbUtil#setPreparedStatementObject` if the value is `null`:
Shouldn't there be a return statement included?

```
if (value == null) {
	preparedStatement.setNull(index, Types.NULL);
	// added
	return;
}
```

Bye,
Sascha

**Comment by igr** [comment]
Oh, yeah, it has to be there! Thanx!
