### ISSUE TITLE
correct pattern letters used in JDateTime#.DEFAULT_FORMAT?

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#512]
Hi,

does the current default format pattern (`jodd.datetime.JDateTime.DEFAULT_FORMAT`) use the correct pattern letters?

small code snippet

```
final long time = new JDateTime(2011, 11, 1, 9, 10, 12, 567).getTimeInMillis();

System.out.println("format Date with JDateTime#Default_Format -> " + new SimpleDateFormat(JDateTime.DEFAULT_FORMAT).format(new Date(time)));
System.out.println("format Date with slightly changed format -> " + new SimpleDateFormat("yyyy-mm-dd hh:mm:ss.mss").format(new Date(time)));
```

The Output is:

```
format Date with JDateTime#Default_Format -> 2011-11-305 09:10:12.1012
format Date with slightly changed format -> 2011-10-01 09:10:12.1012
```

In my opinion the default format pattern should be : `yyyy-mm-dd hh:mm:ss.mss`.

WDYT?

Bye,
Sascha

**Comment by moh-sushi** [comment]
note:

code snippet with java.time.LocalDateTime and its Formatter
```
LocalDateTime localDateTime = LocalDateTime.of(2011, 11, 1, 9, 10, 12, 567);

System.out.println("format with slighty changed pattern -> " + localDateTime.format(DateTimeFormatter.ofPattern("yyyy-mm-dd hh:mm:ss.mss")));
System.out.println("format with JDateTime#Default_Format -> " + localDateTime.format(DateTimeFormatter.ofPattern(JDateTime.DEFAULT_FORMAT)));
```

outpout:

```
format with slighty changed pattern -> 2011-10-01 09:10:12.1012

java.time.DateTimeException: Field DayOfYear cannot be printed as the value 305 exceeds the maximum print width of 2
```

**Comment by igr** [comment]
If the format is `yyyy-mm-dd hh:mm:ss.mss`, how to distinguish months and minutes?

`JDateTime` uses the [ISO standard](https://en.wikipedia.org/wiki/ISO_8601) plus some additions (see `Iso8601JdtFormatter`) that are not specified by the standard.

[SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) uses some mix of capital and lower letters, and it was released much after the `JDateTime` :)))

Are you suggesting to make compatible patterns to `SimpleDateFormat`?

We can provide additional `SimpleDateFormatter` that would make formatting by using the `SimpleDateFormatter` and to make `DEFAULT_FORMAT` to be configurable (not `final`).

**Comment by moh-sushi** [comment]
Ups - i am mixing two different domains - my fault!

Well, let us wait until someone needs a `SimpleDateFormatter`.

Thanx for clarification!
