### ISSUE TITLE
Use `charAt` insteadOf `toCharrArray()`

### ISSUE THREAD

**Issue by igr** [oblac/jodd#528]
According to [this beanchmark](https://github.com/igr/java-benchmarks/blob/master/src/main/java/com/oblac/jmh/lang/ToCharArrayVsCharAtBenchmark.java) it seems that we should use `charAt` all the time, and actually wrap the `char[]` usages.

Up to now, we used the opposite approach: converting Strings to `char[]` and then operating on it.

Any thoughts @slandelle, @moh-sushi ?

**Comment by slandelle** [comment]
I guess you're talking about parsing.
Then, your benchmark is invalid. If you want to get things right, you need to take decoding into account. In most cases, you'll be parsing from IO so your input is bytes, not chars.
I'm not sure about your JSON parser, but Lagarto uses Unsafe when available and running on Java 8 to steal the char[] from the String implementation without additional array copy (which is the overhead you're seeing in your benchmark as you use String#toCharArray).

I'm pretty sure (meaning, if my own benchmarks are not flawed) that this strategy is a win on Java 8 w/ Unsafe.

Then, it's obviously a loss on Java 9 as String is no longer implemented on top if a char array.
As Java 9 is out now, if you can push a branch with CharSequence#charAt based parsers (I'm not familiar with the parser generator you use), I'll gladly lend a hand.

**Comment by igr** [comment]
True, the use of `unsafe` would be best in Java8, as no additional char array is created...

The thing is that I have an issue with Java9 and I really, really can have only the one, single codebase. So now I am thinking what would be the best "common ground". So far it looks like wrapping the input `char[]` with some `CharArrayWrapper`; which would separate the code from the direct use of `char[]` and would work with java8 unsafe and java9 w/o unsafe.

**Comment by slandelle** [comment]
I’d say to aim for long term and go with charAt. Introducing an indirection layer will probably hurt both cases (to be verified of course).

**Comment by igr** [comment]
Thanx, it seems so...
