### ISSUE TITLE
Use final for method parameters

### ISSUE THREAD

**Issue by jhult** [oblac/jodd#545]
```Final``` keyword should be used (where possible) for method parameters. 

[Why?](https://stackoverflow.com/a/10380512/423351)

[How-to in IntelliJ](https://stackoverflow.com/a/42346149/423351)

**Comment by igr** [comment]
Thanx! I totally agree, wish I started using `final` much sooner.

Great tip for the IntelliJ, I will try to apply on the whole codebase.
