### ISSUE TITLE
Email: is embed attachment always supposed to be inline?

### ISSUE THREAD

**Issue by jhult** [oblac/jodd#546]
The [```Email#embed(EmailAttachmentBuilder)```](https://github.com/oblac/jodd/blob/master/jodd-mail/src/main/java/jodd/mail/Email.java) method sets inline to ```true```. Is this correct and why?

**Comment by moh-sushi** [comment]
Is [this comment](https://github.com/oblac/jodd/issues/404#issuecomment-297011351) useful for your answer?


HTH,
Sascha

**Comment by jhult** [comment]
That is good background. Thanks for the link.

I think having a definition for embedded vs inline would help me.

1. Just to confirm I read correctly, the ```embed``` attachment method should always ensure ```inline``` is set to ```true```?

2. Is an attachment that is ```inline``` always ```embedded```? If yes, then it would seem to make sense to merge the fields/methods for ```inline```/```embed```.

**Comment by igr** [comment]
Yap, this is something that is tricky :)

+ yes, the `embed()` makes `inline` to be `true` - at least, this is what I have found that work the best.
+ the `inline` is not `embedded`. Inline is a flag, and embedded is a new message part.

There is a difference. As far as I remember, in case when user sends a HTML message (for example) in one case the images that are part of the HTML message appears inline in the text; but if you want to add an attachment that is a real attachment and does not appear as a text, it might be a different type.

I am sorry, I forgot at the moment the difference - but I will test it as soon as possible and put into the documentation!

**Comment by igr** [comment]
Added to the mail [FAQ](https://jodd.org/email/faq.html#is-embed-attachment-always-supposed-to-be-inline).
