### ISSUE TITLE
proxetta produces java.lang.NoClassDefFoundError for multiple generic data types and ProxyAdvices

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#555]
## I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  (Please search GitHub for a similar issue or PR before submitting)
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here.
```

## Current behavior

following method signatures throw an exception from type _java.lang.NoClassDefFoundError_ with custom ProxyAdvices:

```
// example 1
Tupel<List<Integer>, Integer> search(List<Integer> param);
// example 2
Map<Map<Set<Integer>, Long>, Byte> request(List<Long> param);
```

example stacktrace

```
java.lang.NoClassDefFoundError: de/mohsushi/jodd/Tupel, java/lang/Integer>

	at de.mohsushi.jodd.generics.impl.SearchBean$$Proxetta.search$1(Unknown Source)
	at de.mohsushi.jodd.generics.impl.SearchBean$$Proxetta.search$0(Unknown Source)
	at de.mohsushi.jodd.generics.impl.SearchBean$$Proxetta.search(Unknown Source)
	at de.mohsushi.jodd.generics.impl.MainBean.startSearch(MainBean.java:27)
```

jodd version : 3.9.1

## Expected behavior
no exception will be thrown :-)

## Minimal reproduction of the problem with instructions

run test class `de.mohsushi.jodd.generics.TestForGenerics`
see attachment
[jodd petite proxetta - mixing scopes.zip](https://github.com/oblac/jodd/files/1618305/jodd.petite.proxetta.-.mixing.scopes.zip)

Greetz,
Sascha

**Comment by moh-sushi** [comment]
note : example project (attachment) is based on project from #343

**Comment by moh-sushi** [comment]
this issue may be a special case of #431

**Comment by moh-sushi** [comment]
Hi,

with current jodd version 4.0 (commit [afa64b10](https://github.com/oblac/jodd/commit/afa64b1054755f99b974af1a66b666e7755973ba)) the test cases still throw exceptions.

**Comment by igr** [comment]
Got it, this should be easy to fix. Had similar issue before, with the generics parsing!

Thank you so much, this is very helpful!!!!!!
