### ISSUE TITLE
Release notes for versions > 3.8.6 and <= 4.1

### ISSUE THREAD

**Issue by pmouawad** [oblac/jodd#559]
Hello,
I'm looking for release notes of those versions as we want to upgrade Jodd to 4.1 on upcoming Apache JMeter 4.0.
I don't find the release notes neither on website nor in milestones (there is only 1 for v4).

I think it would be nice to manage milestones in the future.

Thanks
Regards

**Comment by igr** [comment]
![open source dilemma](https://user-images.githubusercontent.com/2280001/35238568-ad9a9a54-ff62-11e7-89ab-1999d19f5e3d.png)

**Comment by igr** [comment]
Sorry for that :( It's not that we don't want to do that. But you know already our excuse: it's the time.

For v4 we had _a lot_ of changes, to summarize all the feedback from last few years. And the documentation was really not updated. So the decision was to invest time in docs and similar how-to-projects (have 2 for now).

If this helps: https://github.com/oblac/jodd/compare/v3.9.1...v4.1.0

I truly wish things are different and that we can provide everything that we know how... We are trying :)

**Comment by igr** [comment]
Check:

https://github.com/oblac/jodd/blob/master/CHANGELOG.md
https://github.com/oblac/jodd/blob/master/CHANGELOG_v3.md

**Comment by pmouawad** [comment]
Thanks for your answers.
I understand your issue, I have the same :-)

But from experience, frankly just managing milestone will make your life much easier.
