### ISSUE TITLE
util-classes : add private constructor

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#560]
Hi,

there are several Util-classes (like `jodd.util.StreamUtil` or `jodd.db.DbUtil`).
These util-classes are not to be designed to be instantiated - but you can do it by calling the public default constructor.

proposal:
add a private constructor to all util-classes to prevent initialization.
The ASM-classes would be excluded.

proposal -1-

```
	private DbUtil() {
		// prevent initialization
	}
```

proposal -2-

```
	private DbUtil() {
		throw new AssertionError();
	}
```
 
proposal from Effective Java (3rd) ; Item 4

I can do this and send a PR. 

WDYT?

Greetz,
Sascha

**Comment by igr** [comment]
To be honest, I would leave as they are - without any constructor:) All over the Jodd we kind of try to follow _common sense_ - we assume that developers will figure out this kind of things. There are so many ways how someone can use a library in a wrong way, and I would not introduce this kind of "dead" code that actually prevents that for what has to be an obvious case. I would put this kind of prevention only for business components.

**Comment by igr** [comment]
I would rather introduce the "bean" versions of some fluent interfaces.

For example, we do have `Email` with a fluent interface. I was thinking into adding a wrapper class, `EmailSomething` with get/set/add methods that operates on `Email` inside. `EmailBean` is a name which I don't like :) That would be maybe more valuable thing to add. So to summarize:

+ we have a fluent interface
+ a bean wrapper

This way everyone is happy :)

**Comment by igr** [comment]
Btw talking about `Util` classes, I am thinking into adding an _alternative_ name for example:

+ `ArrayUtil` -> `Arrayz` or `Arr`
+ `MapUtil` -> `Mapz`
+ `CollectionUtil` -> `Collectionz`

Why `z` suffix? To make a difference from Java classes.

So you can write:

```
    Arrayz.grow(....)
    Arrayz.of(....)
```

just would like to have nice names. again, thinking aloud.

Just to clarify, the old names still exist; new names are alternatives. WDYT? Maybe I am overthinking this :)

**Comment by igr** [comment]
Ok, let me close this one; I have the common-sense note in the [STYLEGUIDE](https://github.com/oblac/jodd/blob/master/STYLEGUIDE.md).

**Comment by moh-sushi** [comment]
> To be honest, I would leave as they are - without any constructor:) 

OK


> I would rather introduce the "bean" versions of some fluent interfaces. 

Well, i do not see any advantages for now with "the bean version" (e.g. `EmailSomething`).

> Btw talking about Util classes, I am thinking into adding an alternative name for example:

Nice idea so far...
Do the old classes delegate its methods to new classes?

**Comment by igr** [comment]
>> I would rather introduce the "bean" versions of some fluent interfaces.
> Well, i do not see any advantages for now with "the bean version" (e.g. EmailSomething).

You are right. Also, too much work :)

>> Btw talking about Util classes, I am thinking into adding an alternative name for example:
> Do the old classes delegate their methods to the new classes?

Not at all - just extend :) For example:

```
    public class ArrayUtil extends Arr {
          static methods
    }
```

It's simple, small, no coding involved. Just we need some nice naming.
