### ISSUE TITLE
Can't access MailServer#Builder method

### ISSUE THREAD

**Issue by Sudio** [oblac/jodd#561]
## Current behavior

When I use jodd-email-4.1.0,I find out the following example don't work.I can't access method ssl(),host()...

```
SmtpServer smtpServer = MailServer.create()
            .ssl(true)
            .host("smtp.gmail.com")
            .auth("user@gmail.com", "password")
            .buildSmtpMailServer();
```
## Steps to Reproduce the Problem
I think it's the access domain of MailServer#Builder cause this problem.MailServer#Builder's access domain is default.So the access domain is package.If one class the package is not jodd.mail,it won't have rights to use method ssl(),host().

**Comment by igr** [comment]
Fixed by #562

**Comment by igr** [comment]
Thank you for reporting... And terribly sorry for this.

The new release will be published in a couple of days - stay tuned!

**Comment by igr** [comment]
@Sudio v4.1.1 released! Enjoy :)
