### ISSUE TITLE
Can not access functions of MailServer.Builder.  

### ISSUE THREAD

**Issue by cooppor** [oblac/jodd#563]
## Current behavior

```
SmtpServer server = MailServer.create()
                .host("host.com")
                .auth("username","password")
                .buildSmtpMailServer();
```
Can not access functions of MailServer.Builder.

**Comment by moh-sushi** [comment]
Hi,

it is a known problem -dnd fix has been already done :-)

see #561

HTH

**Comment by igr** [comment]
Yes, the new version will be released either today or tomorrow (debugging some java9 issue).

**Comment by cooppor** [comment]
Sorry my bad, THANKS A LOT anyway.

**Comment by igr** [comment]
@cooppor 4.1.1. released :) Enjoy!

**Comment by cooppor** [comment]
@igr waitting for release in maven repo
