### ISSUE TITLE
I encountered a problem

### ISSUE THREAD

**Issue by zhangxiangfeng** [oblac/jodd#564]
Idea IDE compile is error

In Class  `MailServer.Builder`  Why  not public ?

**Comment by slandelle** [comment]
Duplicate of #561

**Comment by zhangxiangfeng** [comment]
ok
@slandelle

**Comment by zhangxiangfeng** [comment]
i used 3.9.1 is ok

**Comment by igr** [comment]
Sorry about that! Releasing new version now!

**Comment by igr** [comment]
@zhangxiangfeng 4.1.1. released!!!

**Comment by zhangxiangfeng** [comment]
ok
