### ISSUE TITLE
different gradle versions

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#566]
Hi,

there are two different gradle versions definied:
- `gradle/wrapper/gradle-wrapper.properties` with `4.5`
- `jodd-core-9/gradle/wrapper/gradle-wrapper.properties `with `4.3.1`

The version numbers should be the same, right?!

Note : The gradle-wrapper.jar files have to be updated to definied gradle version, too. Right?

Greetz,
Sascha

**Comment by igr** [comment]
`jodd-core-9` is a separate project inside of Jodd - it's not a module as I didn't know how to make java9 only module, and to cerate MR jars... so the version may be different :) nevertheless, lets unify it :)

**Comment by igr** [comment]
Done here: https://github.com/oblac/jodd/commit/d8a0dfbc4796f4f8bac4c91001c77f5abe9761d2
