### ISSUE TITLE
jodd db transaction manager not support Kotlin language?

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#568]
Hi, when I convert jodd 4.1.1 java project to kotlin project in jetbrain idea,there is no problem before I convert the service layer(with Transaction or ReadWriteTransaction annotation).

The code of TestService.java:
```@PetiteBean
public class TestService {
    @PetiteInject
    AppDao appDao;

    @Transaction
    public Member findMember(Long id){
        return appDao.findById(Member.class,id);
    }
}
```

after convert the java code of above to kotlin language
The code of TestService.kt:

```
@PetiteBean
class TestService {
    @PetiteInject
    var appDao: AppDao? = null

    @Transaction
    fun findMember(id: Long?): Member {
        return appDao!!.findById(Member::class.java, id!!)
    }
}
```

the jodd transaction manager throws DbSqlException 
```
jodd.db.DbSqlException: No transaction is in progress and DbSession can't be provided. It seems that transaction manager is not used to begin a transaction.
	at jodd.db.jtx.DbJtxSessionProvider.getDbSession(DbJtxSessionProvider.java:62)
	at jodd.db.DbQueryBase.initSession(DbQueryBase.java:220)
	at jodd.db.DbQuery.<init>(DbQuery.java:89)
	at jodd.db.DbQuery.<init>(DbQuery.java:99)
	at jodd.db.oom.DbOomQuery.<init>(DbOomQuery.java:113)
	at jodd.db.oom.DbOomQuery.query(DbOomQuery.java:117)
	at jodd.db.oom.dao.GenericDao.findById(GenericDao.java:195)
```

**Comment by igr** [comment]
Hey @jodder (nice nick, btw :)

Would you be so kind to copy/paste the full stacktrace of the error?

**Comment by igr** [comment]
Ah, ok, I see it now - it was bad formatting :)

Sure, I will try this. The issue might be with our AOP engine, as Kotlin classes are created differently.

**Comment by jodder** [comment]
Hi @igr, Maybe this tool helps to solve this problem！
https://github.com/borisf/classyshark-bytecode-viewer/
download from :
https://github.com/borisf/classyshark-bytecode-viewer/releases

**Comment by igr** [comment]
Thanx @yujinping I have the tools, but new one will not hurt :)

However, i need some dedicated time for this issue, to check if I can trick Kotlin bytecode...

**Comment by igr** [comment]
The issue here is that the `jodd-proxetta` does not know how to play with Kotlin classes.

**Comment by igr** [comment]
Just use `open` Kotlin classes and methods. Either do that explicitly:


```kotlin
@PetiteBean
open class TestService {
    @PetiteInject
    var appDao: AppDao? = null

    @Transaction
    open fun findMember(id: Long?): Member {
        return appDao!!.findById(Member::class.java, id!!)
    }
}
```

or use `open-all` maven or gradle compiler plugin.

The test: https://github.com/oblac/jodd/blob/master/jodd-proxetta/src/test/java/jodd/proxetta/KotlinTest.java

Read more: https://blog.frankel.ch/open-your-classes-and-methods-in-kotlin/
