### ISSUE TITLE
will Petite  provide value injection like spring @Value

### ISSUE THREAD

**Issue by jscrapy** [oblac/jodd#569]
will Petite  provide value injection like spring @Value

```java
public class SomeClass{
    @Value("${db.mysql.url}")
    private String dbUrl;

  ...
}



```

**Comment by moh-sushi** [comment]
Hi,

as far as i know (and short reading of petite doc) there is no support of "spring value annotation".

workaround :

```
public class SomeClass{
    @PetiteInject
    IPropertyService propertyService;  //  your own small service for getting properties

    private String dbUrl;  // as u wanted to use a (system) property

   // initialization method
   @PetiteInitMethod
   public void init() {
        dbUrl = propertyService.getProperty("db.mysql.url");
   }
}
```
Maybe this workaround may help you...


HTH,
Sascha

**Comment by moh-sushi** [comment]
We may think about this as a new feature for petite.

**Comment by igr** [comment]
Hey @jscrapy !

if `db.mysql.url` is a property, then - tada - this already exists in Jodd!

See: https://jodd.org/petite/parameters.html

If you use just `Petite`, then basically you just need to load properties into the `Petite` with `defineParameters(Map)` and pass your `Properties` object and that's it. No special annotation needed. Or you pass the Jodd-Props instead (https://jodd.org/props/index.html). The only thing here is that the name must match the bean names.

If you use `Joy`, then just put the `joy.props` in the root of the resources. It will be loaded automatically.

However, if `db.mysql.url` comes from the other bean (named `db`) then we do not have that.

Here is what we gonna do:

+ have auto-injection as a flag.
+ Add annotation for value.

My question to you (and @moh-sushi :)

+ Would it make sense that `@PetiteValue` read values not only from properties, but from other beans? Basically to simulate what @moh-sushi wrote 2 notes up?

**Comment by igr** [comment]
Actually, the next commit solves it :)))

**Comment by jscrapy** [comment]
Thanks ^_*

**Comment by moh-sushi** [comment]
> Would it make sense that @PetiteValue read values not only from properties, but from other beans? 

I think , @PetiteValue with reading from props is sufficient.

Thank, @igr !
