### ISSUE TITLE
Fix of publish jodd-all

### ISSUE THREAD

**Issue by igr** [oblac/jodd#570]
There is a conflict between the POM file, that is a sum of dependencies and a fat jar, that has all of the dependencies.

Think about removing `jodd-all`.

**Comment by neroux** [comment]
This seems to lead us partially back to #388. Can that conflict be resolved? Personally I find a single library a bit more convenient than to juggle with several different files, which might even depend on each other. Also, Jodd should not lose is 1.7 MB argument :D

**Comment by igr** [comment]
True, true...

Ok, so the solution would be to provide a fat jar with correct pom. Will do that.
