### ISSUE TITLE
About the IntegerArrayConvert,how would that work ,would you help me out?

### ISSUE THREAD

**Issue by cs12110** [oblac/jodd#573]
https://github.com/oblac/jodd/blob/master/jodd-bean/src/main/java/jodd/typeconverter/impl/IntegerArrayConverter.java#L166

Hi,Guys,I found this code on IntegerArrayConverter.java
```java
 if (valueComponentType.isPrimitive()) {
    // convert primitive array to target array
    result = convertPrimitiveArrayToArray(value, valueComponentType);
} else {
    // convert object array to target array
    Object[] array = (Object[]) value;
    result = new int[array.length];

    for (int i = 0; i < array.length; i++) {
        result[i] = convertType(array[i]);
    }
}
```

If the `valueComponentType.isPrimitive()` work,how would this code work?
`IntegerArrayConverter::convertPrimitiveArrayToArray`
```java
if (primitiveComponentType == int[].class) {
    return (int[]) value;
}
```
Can you help me out?

BTW,I like jodd very much, thank you :")

**Comment by neroux** [comment]
I have to admit I am not familiar with that particular class but I am also not exactly sure what your question is. Could you elaborate or rephrase? Thanks.

**Comment by cs12110** [comment]
I'm not good at English,it's too embarrassed,sorry for that. :")

When I look at the method   `convertPrimitiveArrayToArray` of `IntegerArrayConverter.java`,I found this code:

```java
if (primitiveComponentType == int[].class) {
    return (int[]) value;
}
```

If we take a look, we can find:
```java
if (valueComponentType.isPrimitive()) {
    // convert primitive array to target array
    result = convertPrimitiveArrayToArray(value, valueComponentType);
}
```
As we can see ,` int[].class.isPrimitive()` is always being `false`.

So I thought the code should be like this or  it's unnecessary.
```java
if (primitiveComponentType == int.class) {
    return (int[]) value;
}
```

**Comment by igr** [comment]
You are right! Funny thing is that this code does not produce any problem because we have a `if` just before calling that method :)

Good catch @cs12110! Let me fix the dead code and this thing.

Thank you very much for reporting - and no worries about the English, as long as we speak bytecode we are good to go :)
