### ISSUE TITLE
generated pom.xml from module jodd-all is invalid

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#574]
Hi,

the generated `pom.xml` from module `jodd-all` is invalid - generation was changed by issue #570 .

I have executed `gradlew install  -x test  --stacktrace` and following stacktrace was displayed:

> Execution failed for task ':jodd-all:publishMavenJavaPublicationToMavenLocal'.
>  Failed to publish publication 'mavenJava' to repository 'mavenLocal'
>    Invalid publication 'mavenJava': POM file is invalid. Check any modifications you have made to the POM file.

snippet of the generated `pom.xml` looks like:

``` xml
 <developers>
    <developer>
      <id>igor</id>
      <name>Igor Spasić</name>
      <email>igor@jodd.org</email>
      <timezone>+1</timezone>
    </developer>
  </developers>
  <dependencies>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <optional>true</optional>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <dependencies>
    <dependency>
      <groupId>javax.servlet.jsp</groupId>
      <artifactId>javax.servlet.jsp-api</artifactId>
      <version>2.3.1</version>
      <optional>true</optional>
      <scope>provided</scope>
    </dependency>
  </dependencies>
```

Bye,
Sascha

**Comment by igr** [comment]
Sorry for that - Hope it works now :(

(I wish i got a dollar for every minute I worked with gradle:)
