### ISSUE TITLE
publish to local maven repo fails

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#576]
Hi,

there is a problem with publishing generated artefacts to a local maven repo.

following command was uased  : `install -x text --stacltrace`

snippet of the stacktrace:

> :jodd-all:javadocJar
> :jodd-all:sourcesJar
> :jodd-all:signArchives SKIPPED
> :jodd-all:publishMavenJavaPublicationToMavenLocal FAILED
> 
> FAILURE: Build failed with an exception.
> 
>  What went wrong:
> Execution failed for task ':jodd-all:publishMavenJavaPublicationToMavenLocal'.
> > Failed to publish publication 'mavenJava' to repository 'mavenLocal'
>    > Invalid publication 'mavenJava': artifact file does not exist: 'C:\Users\XXXXX\my-dev-projects\jodd-my-fork\jodd-all\build\libs\jodd-all-4.1.5-20180214.jar.asc'

Thank you!

Greetz,
Sascha

**Comment by igr** [comment]
I thought I fixed this - but now I tried on clean environment I see the issue :( fixing...

**Comment by igr** [comment]
Hey @moh-sushi can you check now? I tried on clean environment, and it seems it works.

Sorry for the trouble

**Comment by moh-sushi** [comment]
Hi @igr ,

it works :-)

Thx for fixing!
