### ISSUE TITLE
Global state gets clobbered if you connect to different DB servers in the same application

### ISSUE THREAD

**Issue by dhobbs** [oblac/jodd#581]
## Current behavior

If you connect to a Postgres database after connecting to a SQL Server database, the singleton value of SqlGenConfig is in an invalid state for Postgres. In particular, 'updateablePrimaryKey' is now false and inserts to Postgres will fail.

## Expected behavior

Postgres inserts should still work even after connecting and disconnecting from SQL Server.

## Steps to Reproduce the Problem

1. Connect to an MS SQL Server database, such that `DbDetector.detectDatabaseAndConfigureDbOom` is executed.
1. Connect to a Postgres database and try to insert an object with a DbId primary key column.
1. Because updatablePrimaryKey is now false, the insert statement won't include the id column and it will fail.

**Comment by dhobbs** [comment]
My bad - the docs say that what I'm trying to do isn't supported. Please close this issue with my apologies.

**Comment by igr** [comment]
@dhobbs no worries - this is one of the things that we want to change. Actually, it would not be so hard, just to figure how users would choose the database scope, i.e. which database to work with. How one piece of code can work with one database, and the other to work with other.

I had several options in mind:

+ package differentiation: you simply specify the root package for each database. Every database operation would check the class name and would figure wich database to use.

+ ThreadLocal storage, probably the implementation of above, where you can turn on manually in the code one database access.


So I am looking for the way that would be simple and clean for developers to specify one or the other target database. Implementation would not be a problem :)

Im going to reopen this as I do plan to work on it. Not in current sprint, but soon.

**Comment by igr** [comment]
I have added `DbOom` - it is now the central class for running all DbOom things.

You can use it if you have multiple DBs.
