### ISSUE TITLE
Provide an alias for $ in Jerry

### ISSUE THREAD

**Issue by helmbold** [oblac/jodd#590]
If Jerry is used with Kotlin, the `$` must be escaped with backticks:

```kotlin
jerry(document).`$`("h1")
```

It would be nice to have an alias for `$` like `select` 

```
jerry(document).select("h1")
```

In times of declining importance of jQuery (less programmers are familiar with it), it might be a good idea to have such an alias anyway.

**Comment by igr** [comment]
Make sense.

we are splitting this big monolith repo into smaller, stay tuned.

**Comment by neroux** [comment]
There already is such a method. Check out hte JavaDoc.

@igr As for splitting the library, I hope there'd still be one single distribution though, as this is IMHO one of the advantages of Jodd, not having to deal with a thousand JAR files but have all of Jodd's functionality in one handy file.

**Comment by igr** [comment]
@neroux you are right:

```
public Jerry $(final String cssSelector) {
	return find(cssSelector);
}
```

So it's `find()`... Maybe `select` is a better name?

**Comment by helmbold** [comment]
Since the parameter is named `...Selector`, the method name `select` would be a better fit. However, thanks for the hint -- I can live with `find`.

**Comment by igr** [comment]
@helmbold Just checked the jQuery API:

The `find` name is correct: https://api.jquery.com/find/ The argument is similar to jQueries one.

The `select` name is used for https://api.jquery.com/select/ which we don't support.

As Jerry should look like a jQuery there is no need to change anything :)

**Comment by helmbold** [comment]
The resemblance of the jQuery API is a value of its own. Without this aspect I would have liked `select` a bit more, but `find` is fine, too.
