### ISSUE TITLE
Does *.props file support load properties from other file?

### ISSUE THREAD

**Issue by titanseason** [oblac/jodd#593]
For example:
I have a file named: `jdbc.properties` and with content:
```
jdbc.username=root
```

In `joy.props`, I don't want to define jdbc.username again, and just write:
```
// some code to load jdbc.properties
dbpool.username=${jdbc.username}
```

Is this feature supported?

**Comment by igr** [comment]
Yes. `Props` object can be loaded from multiple sources, mixing `properties` and `props`.

If you use `Joy`, you can specify the props name pattern that would load all the props. In your case, you would specify: `*.prop*`.

However, I will add more feature to Joy regarding the props loading.

**Comment by igr** [comment]
Added methods for you. During the joy configuration you can specify now individual files (and patterns) to load.
