### ISSUE TITLE
HtmlStaplerBundlesManager : usage of DigestEngine

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#596]
Hi,

i have seen that class `jodd.htmlstapler.HtmlStaplerBundlesManager` uses direct call to `java.security.MessageDigest` (see method [createDigest](https://github.com/oblac/jodd/blob/0f989f1e35564d0daaadd61ae3ab5e211085d187/jodd-htmlstapler/src/main/java/jodd/htmlstapler/HtmlStaplerBundlesManager.java#L403)).

What about usage of jodd digest engine `jodd.util.crypt.DigestEngine` ?

Module `jodd-htmlstapler` has dependencies to `jodd-servlet `and this module to `jodd-core`...Threfore no new dependency should be added.

WDYT?

Bye,
Sascha

**Comment by igr** [comment]
Something like https://github.com/oblac/jodd/commit/348334f07ba02094ea1c4703cc0f9b4eb2809ef6? :)))

Good catch! `DigestEngine` was added recently, but not applied elsewhere.

**Comment by moh-sushi** [comment]
Yes, something like [348334f](https://github.com/oblac/jodd/commit/348334f07ba02094ea1c4703cc0f9b4eb2809ef6)  :grin:
