### ISSUE TITLE
FileUtil : usage of DigestEngine

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#597]
Hi,

Jodd Digest Engine the 2nd :-)

The class `jodd.io.FileUtil` uses direct calls to `java.security.MessageDigest`, too.

This jodd class should use calls to jodd.util.crypt.DigestEngine, shouldn't it !?

WDYT?

Bye,
Sascha

**Comment by igr** [comment]
I knew you will ask :)

This time it is not a trivial change - the methods are using the `DigestInputStream`, which is good as we don't need to load the whole file into the memory.

For that reason, we would need to extend the `DigestEngine` api...

**Comment by moh-sushi** [comment]
I see... hmm...

Well, what about expanding `DigestEngine` API with methd  `MessageDigest messageDigest() `.
The `MessageDigest-`instance will be used in method [digest](https://github.com/oblac/jodd/blob/497d19d577eb82f295aa942e4c05658a96acf67b/jodd-core/src/main/java/jodd/io/FileUtil.java#L1522) within class `FileUtil`.

conclusion : The DigestEngine API will be only used for resolving specific `MessageDigest`-instance.

Bye,
Sascha

**Comment by moh-sushi** [comment]
another way:

We leave it as it is for the moment...

**Comment by igr** [comment]
I thought the same at first - to add the method that returns the digest algorithm. but maybe better is to add a method digest(File) that can take advantage of streams. Or just digest(inputstream).

**Comment by moh-sushi** [comment]
Proposal method `digest(File)` sounds well.

**Comment by igr** [comment]
And... closed this one as well :)
