### ISSUE TITLE
Old Javadoc linked from https://jodd.org/documentation/

### ISSUE THREAD

**Issue by FilipJirsak** [oblac/jodd#598]
There is link on [Javadoc](http://oblac.github.io/jodd-site/javadoc/) on page [Documentation](https://jodd.org/documentation/). But this Javadoc is for old version of Jodd – version 4.1.5.

**Comment by igr** [comment]
Sorry for that, didnt update the javadocs.

Releasing a new version atm so I will update the docs, too.

Thank you!

**Comment by igr** [comment]
Strange. It was some caching on GitHub side... not quite sure what happened. Now it is updated!
