### ISSUE TITLE
Official JAR incompatible with JDK 9 and JDK 10 due to javac error (Multi-Release: true)

### ISSUE THREAD

**Issue by FilipJirsak** [oblac/jodd#599]
There is [bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8193802) in `javac` in JDK 9 and JDK 10 in handling JAR files on classpath. Official `jodd-core-4.3.0.jar` and `jodd-core-4.3.1.jar` from central Maven repository is affected with this bug so people can't compile sources with JDK 9 or JDK 10 `javac` when `jodd-core-4.3.*.jar` is on compile classpath.

The problem with jodd JAR files is there is `Multi-Release: true` in `MANIFEST.MF`, but there is no `versions` directory in `META-INF` (see [JEP-238](http://openjdk.java.net/jeps/238)). Probably there are missing files from `jodd-core-9` module in final JAR file.

There shouldn't be `Multi-Release: true` in `jodd-core.jar`, it should be only in `jodd-core-jre9.jar`.

**Comment by igr** [comment]
True! Thank you @FilipJirsak! I simply forgot to remove it:(
