### ISSUE TITLE
[Bug] Possible exception and character duplication in StringTemplateParser

### ISSUE THREAD

**Issue by sigustin** [oblac/jodd#601]
This issue has to do with the class `StringTemplateParser` in ` jodd/jodd-core/src/main/java/jodd/util/template/StringTemplateParser.java`. The fault was found using a desktop computer under Ubuntu 16.04 but should happen with any equipment. It was found in _Jodd 3.8.1_ but seems to still exist in _4.3.0_.

## Current behavior

I could find what seems to be two unexpected behaviors: one produces an `IndexOutOfBoundsException`, the other one duplicates some characters. I am opening only one issue because they both are a consequence of the same fault in the code.

### `IndexOutOfBoundsException`

Setting up the string template parser in the following way:
```java
StringTemplateParser stp = new StringTemplateParser();
stp.setReplaceMissingKey(false);
```
An `IndexOutOfBoundsException` is then thrown when executing any of the following lines:
```java
stp.parse("$foo", null));
stp.parse("$foo bar", null);
stp.parse("foo $bar", null);
stp.parse("$foo", (s) -> {throw new RuntimeException();});
```

### Duplicated characters

Setting up the string template parser in the same way, we get duplicated characters around the macro for each of the following lines:
```java
stp.parse("bar$foo baz", null); // returns "barr$foo  baz" (note the duplicated 'r' and spaces around "$foo")
stp.parse("bar$foo baz", (s) -> {throw new RuntimeException();}); // returns "barr$foo  baz"
```

## Expected behavior

For all the lines shown before, the logical behavior would be to return the template without any change.

## Explanation of the fault

Three conditions have to be met in order to trigger this fault:

- the macro resolver has to return `null` or throw an exception (line 267 or 269 sets `value` to `null`)
- `replaceMissingKey` has to be set to `false` (line 276 will be executed)
- a macro that uses non-strict syntax has to be present in the template (`$foo` rather than `${foo}`)

The issue comes from line 276 of `StringTemplateParser.java` in _Jodd 4.3.0_ (line 309 in _Jodd 3.8.1_).
Indeed, the parameters given to `substring()` use offsets that are fit for the strict syntax and not for the non-strict one. In other words, for macros using non-strict syntax, this line should be:
```java
value = template.substring(ndx1 - 1, ndx2);
```
rather than
```java
value = template.substring(ndx1 - startLen, ndx2 + 1);
```

Obviously, the fault is triggered only for very specific sets of parameters and shouldn't be a problem for the majority of usages.

**Comment by igr** [comment]
Wow @sigustin! Thank you very much for awesomely reported issue - it was really super useful and easy for me to fix!

**Comment by sigustin** [comment]
You're welcome!
