### ISSUE TITLE
I can

### ISSUE THREAD

**Issue by 92cuixuan** [oblac/jodd#602]

**Comment by slandelle** [comment]
![images](https://user-images.githubusercontent.com/849197/38554892-8c5dcd8a-3cc4-11e8-8658-c85013183a50.jpeg)

**Comment by igr** [comment]
![image](https://user-images.githubusercontent.com/2280001/38555009-eb954a62-3cc4-11e8-870f-0f1e88492519.png)

**Comment by igr** [comment]
(just kidding @92cuixuan; this is a beautiful opportunity to introduce little fun here :)

**Comment by 92cuixuan** [comment]
so humorous ,love you
