### ISSUE TITLE
I can not find Class of JDateTime,it has been removed?

### ISSUE THREAD

**Issue by 92cuixuan** [oblac/jodd#603]
See the title.

**Comment by igr** [comment]
Partially.

The calculation is here: https://github.com/oblac/jodd/blob/master/jodd-core/src/main/java/jodd/util/JulianDate.java It is very nice math code I didn't want to throw away :)

`JDateTime` was the most bashed class in the whole Jodd - without even looking any further ppl would discard Jodd. To be honest, Java8 comes with `java.time` package that is more complete; hence we don't need `JDateTime` any more.

Just use `LocalDateTime` instead and love Jodd :)

Hope you understand.

**Comment by jodder** [comment]
@igr Have one question,Jodd not support LocalDateTime,LocalDate,LocalTime  as default(JDateTIme is supported by default) ,Would you please add the json serialize convert and sqltype for these with JoddJoy,and regist theme as default?

**Comment by igr** [comment]
@jodder you are right. started working on that...

**Comment by igr** [comment]
@jodder just added 4b53fb989ebdbb11cf1e6351a1857bb678f39745
