### ISSUE TITLE
Null pointer exception when creating imap mail server 

### ISSUE THREAD

**Issue by KilianB** [oblac/jodd#604]
Trying to instantiate an ImapServer object fails with a null pointer exception 

With our without a builder  

```java
ImapServer imapServer = MailServer.create()
			.ssl(true)
		        .host("secureimap.t-online.de")
		        .port(993)
		        .auth(username, password)
		        .buildImapMailServer();

//Same result without a builder
ImapServer imapServer = new ImapSslServer("secureimap.t-online.de",993,new SimpleAuthenticator(username,password));


Exception in thread "main" java.lang.NullPointerException
	at jodd.mail.ImapSslServer.createSessionProperties(ImapSslServer.java:58)
	at jodd.mail.MailServer.<init>(MailServer.java:68)
	at jodd.mail.ImapServer.<init>(ImapServer.java:53)
	at jodd.mail.ImapSslServer.<init>(ImapSslServer.java:52)
	at jodd.mail.MailServer$Builder.buildImapMailServer(MailServer.java:220)
	at modules.mail.MailModule.<init>(MailModule.java:54)
```

I am able to connect to the output smtp server. 

### Example at https://jodd.org/email/
Additionally the example provided at Receiving emails using SSL -> (IMAP) won't compile. The i in `imapServer popServer` needs to be capitalized and popServer should be replaced by imapServer.

**Comment by igr** [comment]
Sorry for this @KilianB :( The bug is really stupid, and it was introduced in refactoring.

Please let me know if you have an urgent need for the fix, to release a new version.

**Comment by igr** [comment]
Ah, forgot to put a message in the commit https://github.com/oblac/jodd/commit/6bac2b9da4a5dfcc34dd635aa17e5ed4f5a73915

**Comment by igr** [comment]
Also, thanx for the documentation - will change it asap.

**Comment by KilianB** [comment]
That was a really quick response thank you. What is the usual timespan until you release a new version? +- a week are not critical for me at the moment but I would appreciate a fix live at the end of the month.

**Comment by igr** [comment]
@KilianB deal! Since this is a bug fix I will release it in next 7 days, targeting the weekend or Monday :)

**Comment by igr** [comment]
https://github.com/oblac/jodd/releases/tag/v4.3.2

Enjoy!
