### ISSUE TITLE
jodd-mail bug for milliseconds EmailFilter.filter().receivedDate 

### ISSUE THREAD

**Issue by kiaruzza** [oblac/jodd#608]
Hi,
I'm trying to use 

`EmailFilter.filter().receivedDate(EmailFilter.Operator.EQ, 1524575533757), `

and returns me an error:

> Integer number too large

This is the failed test: https://github.com/oblac/jodd/pull/607

**Comment by igr** [comment]
Yeah, you just need to send a `long` ;)

In Java, if you write a number it will be parsed as an `int`. You need to specify the `long` type by adding `L` or 'l' to it:

    EmailFilter.filter().receivedDate(EmailFilter.Operator.EQ, 1524575533757L),

It's not Jodd, it's just how Java works.

Enjoy!
