### ISSUE TITLE
Any plan to develope JoddBoot like SpringBoot?

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#614]
@igr Has any plan to dev jodd-boot, using undertow or jetty or tomcat?
Then in micro service scene,only run java -jar demo.jar to serve restfull web service .

**Comment by igr** [comment]
Yes :) This feature will come, but I need few steps...

Already have Tomcat and Jetty starters - using them in JoddJoy tests; but I still need Gradle to fetch the application server jars.

After this gets in and verified, I will work on actually building a boot engine.

So... it's planned! :) Just need little time

**Comment by igr** [comment]
https://github.com/oblac/joy-boot

**Comment by igr** [comment]
https://jodd.org/joy/#joy-boot
