### ISSUE TITLE
How do i send mail and save it in the folder of sent?

### ISSUE THREAD

**Issue by godpit** [oblac/jodd#615]
I didn't find a simple way to save mail, just like calling a method or setting the private property  to work it automatically.
It is better and simple way for setting the property automatically.

```
        SendMailSession sendsession = smtpServer.createSession();
        sendsession.open();
        Email mail = createEmail();
        String msgId = sendsession.sendMail(mail);
       .............//how to convert the mail to  the message?
       folder.appendMessages(new Message[]{message});
       folder.expunge();
````

Even if this is successfully saved， but it is difficult and complex.

**Comment by igr** [comment]
Sorry for late response, very busy with release5 :)

Just to check what you need: it would be a method in `SendMailSession` that would also allow to store a message to a folder? Something like:

   sensSession.saveMailToFolder("folderid")

Or you need a way to get `Message` from the `Email`?

**Comment by igr** [comment]
Duplicate of #619
