### ISSUE TITLE
Any possibility to move mail to target folder 

### ISSUE THREAD

**Issue by raffelino** [oblac/jodd#619]
## Current behavior

Currently it is not possible to move received mails to some folder after processing them.

## Expected behavior

Use a functionality like `receiveEmailAndMoveToFolder(myFilter, targetFolder)` to process the given emails. Even more useful would be to create some kind of builder to setup the target behaviour, like `session.actions().receive(myFilter).markSeen().moveToFolder(targetFolder).execute()`.

Keep up the good work!

**Comment by igr** [comment]
Nice idea - especially for the builder pattern! How come I didn't see it, it is so natural here ;)

Would you be so kind to check if the current fix works for you? Thank you!

p.s. it will be released very soon.

**Comment by raffelino** [comment]
Beautiful, though I do not manage to get it working to move and delete in a single `get()`.

I tried 
`ReceivedEmail[] mails = new ReceiverBuilder(session).fromFolder("tata").markDeleted().moveToFolder("test").get();
Assert.assertEquals(1, mails.length);`

as well as
`ReceivedEmail[] mails = new ReceiverBuilder(session).fromFolder("tata").moveToFolder("test").markDeleted().get();
Assert.assertEquals(1, mails.length);`

The emails from folder `tata` are still there. It is working for me to perform `moveToFolder("test").get()` and `markDeleted().get()` afterwards.

Thanks for the rapid development. Absolutely astonishing!

**Comment by igr** [comment]
Got it. Btw, once when you set `moveToFolder()` you don't need to specify the `markDelete` as that one is automatically set:

```
ReceivedEmail[] mails = new ReceiverBuilder(session)
    .fromFolder("tata")
    .moveToFolder("test")
    .get();
```

This code should be sufficient.

I will take a look, maybe I need to expunge or something.

**Comment by igr** [comment]
Heya @raffelino could you try to close the receiving session after receiving emails?

Something like:

```
ReceivedEmail[] mails = new ReceiverBuilder(session)
    .fromFolder("tata")
    .moveToFolder("test")
    .get();
    session.close();
```

The thing is that `expunge` of the folder only happens when a folder is closed.

After this operation, just open new session and check if emails are really deleted.

If this is true, I will close the folder after every received operation!

Thank you in advance!

**Comment by igr** [comment]
My bad, you can expunge just the folder.

Would you be so super kind to test now, pleeease?

**Comment by igr** [comment]
Hey @raffelino sorry for bugging, did you have time to check if current master works? I just want to publish 5.0.1 when possible :)

**Comment by raffelino** [comment]
Gave it a try, works as expected! 

Thanks once again!
