### ISSUE TITLE
console action path not math the really path

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#620]
@igr when I use jodd version 5 to create the kotlin demo.

The action ChildGoodsCategoryListAction.kt
```
package io.github.yujinping.mall.action.api.mall

import io.github.yujinping.mall.action.BaseAction
import jodd.madvoc.meta.Action
import jodd.madvoc.meta.MadvocAction
import jodd.madvoc.result.JsonResult

@MadvocAction
open class ChildGoodsCategoryListAction:BaseAction(){
    @Action
    open fun view():JsonResult{
        return json()
    }
}
```
and I found the console output the action mapping is  : 
```
-[Routes]-------------------------------------------------------------------------------------------
*       /api/adverts/list                                        i.g.y.m.a.a.adverts.ListAction#view
*       /api/home/hostGoodsList                            i.g.y.m.a.a.home.HostGoodsListAction#view
*       /api/mall/childGoodsCategoryLi            i.g.y.m.a.a.mall.ChildGoodsCategoryListAction#view

```

the 3rd line **/api/mall/childGoodsCategoryLi** should be **/api/mall/childGoodsCategoryList**

these output may be confused!Cause of when visit **/api/mall/childGoodsCategoryLi**   ,404 not found .The url **/api/mall/childGoodsCategoryList** is fine.

Maybe output the full path should be better for the  developer.

**Comment by igr** [comment]
Hey!

No worries, this time the output was simply truncated:) The correct path is `/api/mall/childGoodsCategoryList`, I just put the column size that is not enough.

I can fix this - but at one point there will be a long path that we would not be able to show.

What would be the best way to truncate in such cases? Maybe like this:

    *    ..../mail/someAction

wdyt?

**Comment by yujinping** [comment]
This is a good idea!Better than current solution.
