### ISSUE TITLE
DefaultResultSetMapper parseObjects(final Class... types) not support special table name

### ISSUE THREAD

**Issue by baishui2004** [oblac/jodd#621]
## Current behavior
**File:** https://github.com/oblac/jodd/blob/master/jodd-db/src/main/java/jodd/db/oom/mapper/DefaultResultSetMapper.java
**Line 404:** 			} else if (resultTableName.equals(tableName)) {

**Question:** 
If table name is group and config model Group.java  @DbTable("\`group\`"), then resultTableName is "\`GROUP\`" and tableName is "GROUP", resultTableName not equals tableName, but it should. As a result of this, GenericDao method findOneByProperty will return null value, which call DbOomQuery method find(final Class... types) .

## Expected behavior
Could modify this to make "\`GROUP\`" equals "GROUP"? Thanks.

**Comment by igr** [comment]
Thank you for the report!

I have also added two flags into the `ColumnNamingStrategy` and `TableNamingStrategy` so you can turn on quoting for **all** table and column names, so you don't have to write that by yourself in the annotations.

Enjoy!

**Comment by baishui2004** [comment]
@igr Thank you so much!
