### ISSUE TITLE
EMails are marked as SEEN when they shouldn't be

### ISSUE THREAD

**Issue by alturkovic** [oblac/jodd#622]
## Current behavior

Fetching unseen emails from GMail marks emails as seen when it shouldn't.

## Expected behavior

Fetch unseen emails without marking them as seen.

## Steps to Reproduce the Problem

```
try (ReceiveMailSession session = mailServer.createSession()) {
  session.open();
  final ReceivedEmail[] mails = session.receive()
      .filter(filter().flag(Flag.SEEN, false))
      .fromFolder("INBOX")
      .get();
  for (final ReceivedEmail mail : mails) {
    // do something
  }
}
```

I have not used `receiveEmailAndMarkSeen()` nor `markSeen()` but they are still marked as seen on GMail.

**Comment by igr** [comment]
(sorry for long reply, im in the middle of mu vacation, will be back on August 1st)

**Comment by igr** [comment]
You did everything correctly. I will check whats going on - I know that we do not set the flag. There is also a chance that Google simply works like that. Will let you know.

**Comment by igr** [comment]
Hey @alturkovic did you figure this one out?

**Comment by alturkovic** [comment]
No, sorry, I tried leaving a comment from my phone and missclicked. Couldn't get to laptop immediately, my bad.

I wanted to just leave a comment that I have been able to read mails with Spring without marking them, thought it might help you figure it out, their [documentation](https://docs.spring.io/spring-integration/reference/html/mail.html) has a lot of details on marking.
