### ISSUE TITLE
Cannot inject private field value on bean class

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#625]
PetiteInject cannot inject private field on bean class.
For example:
```
@PetiteBean
public class BaseDao<T> {
}
```
```
@PetiteBean
public class BaseService<T> {
    @PetiteInject
    private BaseDao<T> dao;
}
```
In the class BaseService, when use private before "dao" field, the "dao" field value will be null.
After remove "private" ,"dao" will be injected well.

But ,there is some difference on madvoc action.
 ```
@MadvocAction
public class IndexAction {
    @PetiteInject
    private UserService userService=null;

    @In
    private Integer index=null;

    @RestAction("/")
    public List<User> index(){
        List<User> users = userService.list(User.class);

        if(index!=null)
            throw new ServiceException(3,"ERROR");
        return users;
    }
}
```
In the IndexAction, field "userService" and "index" have  private access , but the value be injected all well here .

Should we have the same principle for all injection ? Just like spring framework, check the annotation on the private field ,not only on the current java class, but also the super class(Until the current class is Object)?

**Comment by yujinping** [comment]
@igr I change my UserService.java like this:
```
@PetiteBean
public class UserService extends BaseService<User>{
    private static final Logger logger = LoggerFactory.getLogger(UserService.class);

    @PetiteInject
    private BaseDao<User> baseDao;

    public void check(){
        logger.info("baseDao={}",baseDao);
    }
}

```
```
09:28:34.013 [qtp913190639-12] INFO  i.g.mall.api.service.UserService - baseDao=null
```
After I remove "private" from the front of "baseDao" field
```
09:35:33.017 [qtp913190639-12] INFO  i.g.mall.api.service.UserService - baseDao=io.github.mall.api.dao.BaseDao$$JoddProxy@2f5a7da
```
Not same with the action field inject role!Also not a bug , but if enhance it & be the same of action wold be better!

**Comment by yujinping** [comment]
Double checked!There is no problem with code. I think it might be better to allow private field to be injected.

**Comment by igr** [comment]
Thank you, will try to do that soon!

**Comment by igr** [comment]
Thank you, you were right!
