### ISSUE TITLE
NaturalOrderComparator violates transitivity rule

### ISSUE THREAD

**Issue by holgerl** [oblac/jodd#627]
## Current behavior

`jodd.util.NaturalOrderComparator` fails during sorting of some lists. This is because it violates the transitivity rule of `java.util.Comparator.compare()`

_From https://docs.oracle.com/javase/6/docs/api/java/util/Comparator.html#compare(T,%20T):_
> The implementor must also ensure that the relation is transitive: ((compare(x, y)>0) && (compare(y, z)>0)) implies compare(x, z)>0.

The result is that Java 8's sorting method `java.util.List.sort()` may throw

    java.lang.IllegalArgumentException: Comparison method violates its general contract!

## Expected behavior

Follow the Comparator specification in all cases

## Steps to Reproduce the Problem

Using org.jodd:jodd-core:5.0.3:

    String x = "1-79";
    String y = "0";
    String z = "00001";

    NaturalOrderComparator<String> comparator1 = new NaturalOrderComparator<>();

    System.out.println(comparator1.compare(x, y)); // 1
    System.out.println(comparator1.compare(y, z)); // 3
    System.out.println(comparator1.compare(x, z)); // -4

**Comment by igr** [comment]
Thank you for the report!

I was looking at this issue a lot, and - unfortunately - I realized that algorithm is not ok. In fact, there are so many use cases where current logic fails...

For example `0N' and `Aa`? If we ignore zeros (as we do), `Aa` comes before `N`. But if zeros are not ignored, `0N` comes before `Aa`, which is what I would expect.

To be honest, I am not sure how to proceed with this. I am afraid it would take a lot of time :( This leads me to the conclusion that this class should be removed, unfortunately...

**Comment by holgerl** [comment]
Java 8 has a natural order comparator in `Comparator.naturalOrder()`. Is it perhaps a decent replacement?

https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#naturalOrder--

**Comment by igr** [comment]
Unfortunately not, I have no idea whats Javas 8 natural order (from looking the code its really nothing inside). For example:

    System.out.println(new NaturalOrderComparator<String>().compare("a4.jpg", "a10.jpg"));  // -1
	System.out.println(Comparator.<String>naturalOrder().compare("a4.jpg", "a10.jpg"));  // 3
	System.out.println("a4.jpg".compareTo("a10.jpg"));  // 3

in Natural order, the `a4` should come before `a10` (i.e. the results should be negative).

**Comment by igr** [comment]
@neroux I will give it another shot. It's not that simple as my example, there are many cases. `0` can appear in the middle of the string and multiple times (eg. `file01-a00.jpg`) and so on. Many edge cases :)

**Comment by igr** [comment]
@neroux yes, that's what I am doing right now - making stricter rules, so to discard some edge cases that would give strange results.

Here is one case, writing it down here for the future references.

    "abc01xyz" < "abc001xyz"

because the first string has fewer zeros. But:

    "abc01xyz" > "abc001aaa"

i.e. the difference in zeros is only taken into account when the rest of the strings are equal.

**Comment by igr** [comment]
Hoping this fix helps @holgerl! It would be awesome if you can try it, I want to release Jodd soon.

@neroux I own you, man.

**Comment by holgerl** [comment]
Yes, the fix in v5.0.4 works! @igr 

The list I am sorting is 22,076 report ids entered by users, so it is a good test for the comparator.

**Comment by igr** [comment]
Awesome news!!! Especially since it is released, I was a bit worried :) Thank you for reporting!


(Thanx @neroux!)
