### ISSUE TITLE
using joy with gradle,reference jars not correct

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#630]
When I create gradle java project with idea,
gradle version : 4.9
jdk: java8
idea:2018.2.2

using the following build.gradle
```groovy
plugins {
    id 'java'
    id 'war'
    id "org.akhikhl.gretty" version "2.0.0"
}

group 'io.github.yu'
version '1.0'

sourceCompatibility = 1.8

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    compile 'org.jodd:jodd-all:5.0.4'
    compile 'org.jodd:jodd-joy:5.0.4'
    compile 'org.slf4j:slf4j-api:1.7.25'
    //compile 'ch.qos.logback:logback-core:1.2.3'
    //compile 'ch.qos.logback:logback-classic:1.2.3'
    runtime 'mysql:mysql-connector-java:8.0.12'
    //testCompile group: 'junit', name: 'junit', version: '4.12'
}
gretty {
    servletContainer='jetty9'
    httpPort = 8080
    contextPath = '/'
    contextConfigFile='jetty-env.xml'
}
```

after create war,I found much more jodd jar files were packed to the war file:
```
activation-1.1.jar
javax.mail-1.6.1.jar
javax.mail-api-1.6.1.jar
jodd-all-5.0.4.jar
jodd-bean-5.0.4.jar
jodd-core-5.0.4.jar
jodd-db-5.0.4.jar
jodd-decora-5.0.4.jar
jodd-http-5.0.4.jar
jodd-joy-5.0.4.jar
jodd-json-5.0.4.jar
jodd-jtx-5.0.4.jar
jodd-lagarto-5.0.4.jar
jodd-log-5.0.4.jar
jodd-madvoc-5.0.4.jar
jodd-mail-5.0.4.jar
jodd-petite-5.0.4.jar
jodd-props-5.0.4.jar
jodd-proxetta-5.0.4.jar
jodd-servlet-5.0.4.jar
jodd-vtor-5.0.4.jar
mysql-connector-java-8.0.12.jar
protobuf-java-2.6.0.jar
slf4j-api-1.7.25.jar
slf4j-nop-1.7.12.jar
```

This is not expect! Should be only have "jodd-all-5.0.4.jar" and "jodd-joy-5.0.4.jar" in the war!
What is wrong ?

**Comment by yujinping** [comment]
And the gradle code of the document at https://jodd.org/download/ maybe too old.
When using gradle 4.9,the following code is right:
```groovy
compile 'org.jodd:jodd-xxx:5.0.4'
```

**Comment by igr** [comment]
Hi!

The `all` bundle is a special one. It contains all Jodd libs except for the `joy` (for now).

But if you use `joy` - that would be enough! Don't use `all` at all. `Joy` depends on almost all other Jodd modules and you will get the same results.

So the solution for you is easy:

    compile 'org.jodd:jodd-joy:5.0.4'

Just use joy :)

**Comment by igr** [comment]
Thanx for the documentation note, I will update asap
