### ISSUE TITLE
Move modules into separate projects

### ISSUE THREAD

**Issue by igr** [oblac/jodd#634]
Should we separate Jodd tools into separate projects:

+ core
+ http
+ json
+ email

and let them have their own lifecycle and versioning? 

@neroux @slandelle @moh-sushi

**Comment by neroux** [comment]
This somewhat brings us back to #388 and #570. Is there a particular reason why you'd like to address this possibility now once more? Are there issues with the way it is currently packaged?

**Comment by moh-sushi** [comment]
What is the origin of this issue, @igr ?
Why did you create this issue?

With no information, I see it the way @neroux  does.

**Comment by moh-sushi** [comment]
Further question:
Why do you only want to separate these libraries?
What about Lagarto or (mini framework) Madvoc?

**Comment by igr** [comment]
What happened is that there is a contribution: Android version of Jodd-Http client. It would be cool if things like that stays together - in the same repo. Jodd repo would then just consist of git modules, for example.

I would not split everything, just tools. Frameworks maybe not. I dunno.

I would probably do that before, but never had time to invest in this...

**Comment by neroux** [comment]
> It was, but someone actually ported it :)

What did he port? I am using a version of it before the Java 8 migration on Android too :)

I am still a bit in the dark as to the reason why Jodd should be split though.

**Comment by neroux** [comment]
Personally, I do. I do my dependency "management" myself and add the necessary jar files manually. That's what always stood out for me when it comes to Jodd, quite a few libraries in one single small jar file.

As for the port, without a commit history it is difficult to tell what they changed, but when I adapted it for Android there wasn't that much to do, it was mostly the certificate validation. Admittedly, it was based on a previous code base, before the switch to Java 1.8.

**Comment by neroux** [comment]
But I guess if it is split into different libraries but still has an all-in-one package it shouldn't be that much of an issue and Jodd would still live up to its slogan :)

**Comment by igr** [comment]
> But I guess if it is split into different libraries but still has an all-in-one package it shouldn't be that much of an issue and Jodd would still live up to its slogan :)

That is true, I would not remove this :) The only difference is that the version of bundle jar would be a datestamp.

**Comment by neroux** [comment]
I guess everything should be fine then :)

My concern was Jodd would be split up into dozens of small libraries and you'd need to include each file separately. If you plan to keep the all-in-one library untouched in this regard, it shouldnt matter if the individual packages are all part of one project or scattered around.

Only my two cents :)

**Comment by igr** [comment]
> If you plan to keep the all-in-one library untouched in this regard

Yeah, this was never a question - the bundle would be there :)

**Comment by moh-sushi** [comment]
What about this case:

`jodd-json` : version 6.2.3 (with dep to jodd-core 5.3.9)
`jodd-mail` : version 5.4.5  (with dep to jodd-core 5.4.6)

The version of these libs may differ due to own versioning.
`jodd-json` and `jodd-mail` have dependencies to `jodd-core`.

if you add `jodd-json` and `jodd-mail` with its current version (see above) into the `pom.xml` there may be two different jodd-core jars (due to different versions) in the classpath.

correct?

**Comment by neroux** [comment]
You certainly open up Pandora's box of versioning if you split it, but thats a (somewhat) logical conclusion in that case.

**Comment by igr** [comment]
![giphy](https://user-images.githubusercontent.com/2280001/46197303-b397eb80-c309-11e8-83f0-435f52127511.gif)

**Comment by igr** [comment]
This is so I don't think about it ever again :)

**Comment by neroux** [comment]
> This is so I don't think about it ever again :)

I am seriously considering of adding https://github.com/oblac/ to every single blocking list out there I could think of 😆 

Igor, you do realise, the next time you suggest Jodd should be split I'll be longterm renting a digital billboard across from your very apartment and will have that animation played 24/7 😈

**Comment by igr** [comment]
Hahahaa, that would be a party !!!!!!
They say visual cues are the best, so I tried :)))

**Comment by neroux** [comment]
That cue is a sledgehammer though 😆
