### ISSUE TITLE
usage of annotation DisabledOnOs

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#648]
Hi,

there are few test classes in which an assumption due to linux/windows hsosts is used.
e.g. see [JsonSerializerTest](https://github.com/oblac/jodd/blob/b7d1df1b91ea0dc1e1aaeeae1a0c9433cc83dc56/jodd-json/src/test/java/jodd/json/JsonSerializerTest.java#L617).

since Junit 5.1 there is an annotation [DisabledOnOs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution).

Idea : replace the assumptions with the annoation DisabledOnOs.

WDYT?

i can do this refactoring...

**Comment by igr** [comment]
I am totally ok with it!

**Comment by igr** [comment]
It looks very nice with this
