### ISSUE TITLE
email filter not effect for gbk charset

### ISSUE THREAD

**Issue by hzn6426** [oblac/jodd#652]
HI,
  When i filter the email subject and from, it's no effect. debug the  from like String "=?GBK?B?SFJHcm91cA==?= <xxx@gmail.com>", how to deal it?

**Comment by neroux** [comment]
Is that supposed to be a quoted printable string? Can you post some sample code?

**Comment by hzn6426** [comment]
some code snippet:
`ReceiveMailSession session = imapServer.createSession();
	    session.open();
	    ReceivedEmail[] mails = session.receiveEmail(
	    		EmailFilter.filter().flag(Flag.SEEN, false).or(EmailFilter.filter().from(SystemConstants.SUPPLIER_DISPATCH_EMAIL_ADDRESS.toLowerCase()),
	    				EmailFilter.filter().from(SystemConstants.SUPPLIER_INVENTORY_EMAIL_ADDRESS.toLowerCase()))
	    		);`

**Comment by neroux** [comment]
I reformatted the code for better readability
```java
ReceiveMailSession session = imapServer.createSession();
session.open();
ReceivedEmail[] mails = session.receiveEmail(
	EmailFilter.filter().flag(Flag.SEEN, false)
		.or(
			EmailFilter.filter().from(SystemConstants.SUPPLIER_DISPATCH_EMAIL_ADDRESS.toLowerCase()),
			EmailFilter.filter().from(SystemConstants.SUPPLIER_INVENTORY_EMAIL_ADDRESS.toLowerCase())
		)
);
```

The string in question is tagged as GBK character set, but in fact it is a regular base64 encoded latin string (`SFJHcm91cA==` -> `HRGroup`).

I am not sure though if this is an issue in Jodd and not rather in Java EE. Jodd uses the standard javax.mail packages for this feature it seems

https://github.com/oblac/jodd/blob/908fb8ec7dca13d1d8072b693ad946164d328169/jodd-mail/src/main/java/jodd/mail/ReceiveMailSession.java#L315

Could you find anything in regard to javax.mail having problems with MIME encoded-words and the GBK character set?

@igr, anything I missed?

**Comment by igr** [comment]
@neroux all good! Jodd does not use anything specific, just pass the value. Let me check if terms can be MIME encoded.

**Comment by igr** [comment]
Closed due inactivity.
