### ISSUE TITLE
Don't overwrite character encoding when setting bodyText()

### ISSUE THREAD

**Issue by igr** [oblac/jodd#663]
```
.bodyText()
```

overides

```
contentTypeJson
```

**Comment by neroux** [comment]
Are you referring to https://github.com/oblac/jodd/blob/a5d8ea82554279497f5a5c7d96b395dd128928ea/jodd-http/src/main/java/jodd/http/HttpBase.java#L663?

Thats on purpose, isnt it? It explicitly sets the default mime type, right? In case thats not desired one has the other two `bodyText`s, right?

Am I missing something? :)

**Comment by igr** [comment]
The use case is the following:

    HttpRequest
        .contentTypeJson()
        .bodyText("json");

This means that `bodyText` will override the content type and I need to re-order the methods.

I would like to preserve the content type if set, when assuming defaults.

**Comment by neroux** [comment]
I think I got you :), you only want to use defaults when there is nothing specified yet, right?

**Comment by igr** [comment]
Correct :)
