### ISSUE TITLE
How to enbale sql debug mode when using joy?

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#667]
hi!
How to configue the web app to ouput the sql like "SELECT * FROM user WHERE username ='abc'"
use the real sql parameter's value instead of '?' Not found this information on the documation of jodd.org website!

**Comment by yujinping** [comment]
Jodd version:5.0.6

**Comment by igr** [comment]
Just use `DbOom.get().queryConfig().setDebug(true)`.

There is no need to go over the Joy classes; `DbOom` is designed to be used like this. Run above code after the initialization, of course.
