### ISSUE TITLE
When entity id type is not Long,cannot using GenericDao's findById method!

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#673]
## Current behavior
declare:
User.java:
```
@DbTable
public class User extends Entity<String>{
  @DbId private String id=null;
///some getter and setter
}
```
but GenericDao only declare findById:

```
    public <E> E findById(Class<E> entityType, long id) 
```

## Expected behavior

public <E,Id> E findById(Class<E> entity,Id id);

## Steps to Reproduce the Problem
 using typed parameter type instead of hard code of long

**Comment by igr** [comment]
Thank you! I will release `v5.0.7` this week so you can try it!
