### ISSUE TITLE
joy should add getJoyPetite method for command line program!

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#680]
This test class is command line program using joy db access!

code is here:

```java
public class Test {
    private static final Logger logger = LoggerFactory.getLogger(Test.class);
    public static void main(String[] args) {
        String driver="com.mysql.cj.jdbc.Driver";
        String url="jdbc:mysql://localhost:3306/hotel";
        String username="root";
        String password="";
        JoddJoy joy = JoddJoy.get();
        joy.withLoggerProvider(() -> Slf4jLogger.PROVIDER);
            joy.withDb(db -> db.withConnectionProvider(() -> new DriverManagerConnectionProvider(driver,url,username,password)));

        joy.withPetite(joyPetiteConfig -> joyPetiteConfig.withPetite(consumer -> {
            logger.info("container={}", consumer);
        }));

        joy.start(null);


        PetiteContainer pc =joy.getJoyPetite().getPetiteContainer();


// here some code with petite-bean
        LoginService loginService = pc.getBean(LoginService.class);
        Admin admin = loginService.findAdmin(1L);
        logger.info("admin.id={}",admin.getId());
//Assert admin.id==1L
    }
}

```
Focus line: **PetiteContainer pc =joy.getJoyPetite().getPetiteContainer();**
Current jodd joy class does not contain the method "getJoyPetite()".
## Current behavior

There is no getJoyPetite() method in Joy class.

```java
    public JoyPetite getJoyPetite(){
        return this.joyPetite;
    }
```
## Expected behavior

Add getJoyPetite() method or give a way to access the JoyPetite instance in Joy class.

## Steps to Reproduce the Problem

Feature for command line runtime env.

**Comment by igr** [comment]
Hey! Can't you just use:

```
joy.withPetite(cfg -> cfg.withPetite(petite -> {...
```

Then just put the code there. This is how it was meant to be used - this code will be called just on the right time - when the application starts.

Wdyt?

Btw, do you use [Jodd Boot](https://jodd.org/joy/index.html#joy-boot)?

**Comment by yujinping** [comment]
yeah! I miss the method!thanks @igr !
Not using Jodd boot yet!Will try it a few days later!

**Comment by yujinping** [comment]
I try with this code :
```java
joy.withPetite(joyPetiteConfig -> joyPetiteConfig.withPetite(consumer -> {
            logger.info("container={}", consumer);
            LoginService loginService = consumer.getBean(LoginService.class);
            Admin admin = loginService.findAdmin(1L);
            logger.info("admin.id={}",admin.getId());
 }));
 joy.start(null);
```
       
The above code throw NullException, maybe joy not start and bean not initialized!
,then try using the following code:

```java
 joy.start(null);

joy.withPetite(joyPetiteConfig -> joyPetiteConfig.withPetite(consumer -> {
            logger.info("container={}", consumer);
            LoginService loginService = consumer.getBean(LoginService.class);
            Admin admin = loginService.findAdmin(1L);
            logger.info("admin.id={}",admin.getId());
}));
```
No exception but no log info printed! "admin.id=1" string is excepted!

finally I use ``` static PetiteContainer pc;``` to hold the consumer.
like this:
```java
static PetiteContainer pc;

public static main(){
// same code 
  joy.withPetite(joyPetiteConfig -> joyPetiteConfig.withPetite(consumer -> {
            logger.info("container={}", consumer);
            pc = consumer;
  }));

 joy.start(null);

            LoginService loginService = pc.getBean(LoginService.class);
            Admin admin = loginService.findAdmin(1L);
            logger.info("admin.id={}",admin.getId());
}
```
This work fine!

In general , a getter method of petite maybe a better choice.Or my code wrong ?

**Comment by igr** [comment]
Sorry, my information was wrong. The method I gave should be used only when Petite is NOT started and for configuration.

Note that `joy.start()` method returns the `JoddJoyRuntime`. This class contains everything you ever wanted :)

**Comment by yujinping** [comment]
Fine!
