### ISSUE TITLE
relics of removed JDateTime

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#702]
Hi,

i have found some relics of (removed) `JDateTime`.
- `readme.md`
- `jodd.datetime.JDateTimeTest`
- full text search within whole project -> few javadoc entries
- within test resources

Should i do a _cleanup_ through a PR?

Greetz,
Sascha

**Comment by igr** [comment]
I am doing that now. The thing is that the test might be reused for new JulianDate class, so I will not remove it.

Thank you for notifying, I forgot about this :)
