### ISSUE TITLE
[HTTP] Chunk length could be "null"

### ISSUE THREAD

**Issue by neroux** [oblac/jodd#709]
This issue is not a big deal, as it is likely supposed to eventually throw an exception anyhow, however an `HttpException` is likely better than a `NumberFormatException` :)

I am afraid I dont have the full response body at this point, however with one of the services I am querying I regularly get aforementioned `NumberFormatException` at https://github.com/oblac/jodd/blob/60c0078974e830223a95a43304daa6e55b51e1ce/jodd-http/src/main/java/jodd/http/HttpBase.java#L988 when the previous `readLine` call actually returned `null`.

**Comment by igr** [comment]
May I assume that when `null` is returned, `len` equals to 0?

**Comment by neroux** [comment]
`len` wont get a value in that case as `parseInt` will throw a `NumberFormatException` because its argument is `null` and not a parseable string.

6d0e680 should fix it in this regard, respectively "fix" as in throwing a "clearer" exception. I'd maybe even omit the `null` check as I cant tell right now what will happen now. According to the documentation the end of the stream has been reached when `readLine` returns `null`, so I'd assume the response body might not have a valid structure to begin with in these cases.

**Comment by igr** [comment]
True, according to spec this case is not ok. I just wonder if maybe that server you are talking to is using some 'shortcuts', i.e. with `null` check the code would simply carry on and - just by quick look at the code - the request would end successfully (but I need to test this). Maybe that was the intention.

Let me google, and if I dont find anything on this, I will remove null check.

**Comment by igr** [comment]
By the spec:

> The transmission ends when a zero-length chunk is received.

And by returning `null` we can't be sure if it is the last chunk, or simply the error in communication. Hence, I will remove the null check!

**Comment by igr** [comment]
Done, thank you!!!

**Comment by neroux** [comment]
The server I am talking to is not necessarily best maintained ;), so I wouldnt be surprised if it returns some semi-valid responses.

The `null` would make me think the communication was aborted for some reason, otherwise I presume it should have run through the defined flow and transferred a zero chunk, upon which the connection can be closed in an orderly fashion. So yes, I guess 4a4ecd3 is the right approach.

Again, it wasnt really an issue to begin with as an exception would be expected in that case anyhow. It was just about which kind of exception :)
