### ISSUE TITLE
Custom SSL socket http connection provider.

### ISSUE THREAD

**Issue by lwu-gd-china** [oblac/jodd#711]
## Current behavior

I created SSLSocketHttpConnectionProvider with the customized SSLContext or SSLSocketFactory and set it to a HttpRequest by method "withConnectionProvider()". But it looks like that SSLContext or SSLSocketFactory I have provided is not be used when creating SSLSocket.

## Expected behavior

Here is the source code in SSLSocketHttpConnectionProvider to create a socket. Note that the SSLSocketFactory is always created by a new SSLContext instance, not what I have set before.

	/**
	 * Returns socket factory based on proxy type and SSL requirements.
	 */
	protected SocketFactory getSocketFactory(final ProxyInfo proxy, final boolean ssl, final boolean trustAllCertificates) throws IOException {
		switch (proxy.getProxyType()) {
			case NONE:
				if (ssl) {
					return getDefaultSSLSocketFactory(trustAllCertificates);
				}
				else {
					return SocketFactory.getDefault();
				}
			case HTTP:
				return new HTTPProxySocketFactory(proxy);
			case SOCKS4:
				return new Socks4ProxySocketFactory(proxy);
			case SOCKS5:
				return new Socks5ProxySocketFactory(proxy);
			default:
				return null;
		}
	}

	/**
	 * Returns default SSL socket factory allowing setting trust managers.
	 */
	protected SSLSocketFactory getDefaultSSLSocketFactory(final boolean trustAllCertificates) throws IOException {
		if (trustAllCertificates) {
			try {
				SSLContext sc = SSLContext.getInstance(sslProtocol);
				sc.init(null, TrustManagers.TRUST_ALL_CERTS, new java.security.SecureRandom());
				return sc.getSocketFactory();
			}
			catch (NoSuchAlgorithmException | KeyManagementException e) {
				throw new IOException(e);
			}
		} else {
			return (SSLSocketFactory) SSLSocketFactory.getDefault();
		}
	}

**Comment by igr** [comment]
Good catch!!! The code in `SSLSocketHttpConnectionProvider` simply does not implement the right method. Fixing...
