### ISSUE TITLE
jodd-http: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by srinivas-n4u** [oblac/jodd#713]
Hello,

I am trying to use jodd-http library in Jenkins pipeline groovy scripts. I am sending a post to https end point with self signed cert. I've added .trustAllCerts(true) to the post request and it is working fine with 3.8.6 version of jodd-http. But I needed tokenAuthentication, so I've upgraded to latest version of jodd-http. Now my post request is failing with below error. I tired installing the cert in jenkins jre cacerts, but still the same issue. Please help.

jodd.http.HttpException: Received fatal alert: handshake_failure; <--- javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

Thank you..

**Comment by igr** [comment]
Hello! Would you be so kind to try your example with `-Djavax.net.debug=ssl:handshake:verbose` flag turned on?

If possible, could you give me the target HOST name, so I can try it here? Feel free to send sensitive data on my personal email: igor@jodd.org.

Finally, can you try to disable `verifyHttpsHost` by using `verifyHttpsHost(false)` in your HttpRequest?

Thank you!

**Comment by igr** [comment]
Also, could you check this artice: https://confluence.atlassian.com/jirakb/sslhandshakeexception-received-fatal-alert-handshake_failure-due-to-no-overlap-in-cipher-suite-943544397.html

**Comment by srinivas-n4u** [comment]
Thanks igr for quick response.

Apologies, I forgot to mention earlier. I've already tried using verifyHttpsHost(false), tried adding -Dhttps.protocols=SSLv3,TLSv1,TLSv1.1,TLSv1.2 and copied jre policy jars to jre/lib/security, but no luck. 
I've enabled verbose -Djavax.net.debug=ssl:handshake:verbose, but it is not giving much details in logs.

Running CpsFlowExecution[Owner[Test1/129:Test1 #129]], WRITE: TLSv1.2 Handshake, length = 214
Running CpsFlowExecution[Owner[Test1/129:Test1 #129]], READ: TLSv1.2 Alert, length = 2
Running CpsFlowExecution[Owner[Test1/129:Test1 #129]], RECV TLSv1.2 ALERT:  fatal, handshake_failure
Running CpsFlowExecution[Owner[Test1/129:Test1 #129]], called closeSocket()
Running CpsFlowExecution[Owner[Test1/129:Test1 #129]], handling exception: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

Rest api which I am trying to connect is internal to organization, which is not accessible from outside. 

Issue is coming up when i upgrade Jodd-http to 4.x or 5.x version, and working fine with 3.8.x version. Do we have any changes related to ssl in latest version?

Thank You!

**Comment by igr** [comment]
I must ask, maybe it's stupid, but does your server support TLSv1.2? I will check the difference between 3.x and later, but atm I dont remeber something very specific...

Would you mind if I send you here raw java code to execute on your side? Its all about opening sockets, just to debug easier.

**Comment by srinivas-n4u** [comment]
Yes, Most of our servers have TLSv1.2 enabled. 

Sure, i can execute the code but i might not be able to provide all the logs it generates due to security constraints.

Thanks!

**Comment by igr** [comment]
Sure, I will prepare some code; just need to see if it works or not, that is all, logs are not important... thank you.

**Comment by igr** [comment]
Huh, sorry for the late response... I had some health issues.

Now, back to the problem. Can you try the following:

`SocketHttpConnectionProvider` has changed ssl protocol from `SSL` to `TLSv1.1`.

Could you try setting back to `SSL` with `setSslProtocol()`?

**Comment by srinivas-n4u** [comment]
Hello, Hope you are good..
Currently I am using different library due to project timelines. Can I come back to you after some time.
Thanks and regards,
Srinivas Nedunuri

**Comment by igr** [comment]
@srinivas-n4u any chance you had time to check :)? Thank you!

**Comment by dimitarmd** [comment]
Hey Igor, I've been having the same issue while using jodd-http:5.0.6 on Jenkins2. Your advice on setting the default SSL protocol of SocketHttpConnectionProvider to "SSL" worked fine with all of the other conditions that are mentioned by Srinivas.

Thanks for your advice!

**Comment by igr** [comment]
Thank you @dimitarmd !

**Comment by srinivas-n4u** [comment]
Thanks Igor, Sorry for the late reply, I've tried jodd http again today.  It worked for me too with setSslProtocol().

**Comment by sjethvani** [comment]
Want to add my troubleshooting here , hoping that it may be useful for someone

I was using jodd-http(5.0.6) in my gradle project & was getting SSLHandshakeException 

> jodd.http.HttpException: Received fatal alert: handshake_failure; <--- javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

I checked supported TLS on my server using 'nmap' utility on mac . After installing 'nmap' through brewin terminal . I checked its response for myserver.com (testing server running with https , i.e https://myserver.com)
```
brew install nmap
nmap --script ssl-enum-ciphers -p 443 myserver.com
Starting Nmap 7.80 ( https://nmap.org ) at 2020-04-08 18:52 IST
Stats: 0:00:18 elapsed; 0 hosts completed (1 up), 1 undergoing Script Scan
NSE Timing: About 60.00% done; ETC: 18:53 (0:00:11 remaining)
Nmap scan report for myserver.com (xx.xx.xx.xx)
Host is up (0.32s latency).
Other addresses for myserver.com (not scanned): xx.xx.xx.xx
rDNS record for xx.xx.xx.xx: ec2-xx.xx.xx.xx.ap-southeast-2.compute.amazonaws.com
PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A
|     compressors: 
|       NULL
|     cipher preference: server
|_  least strength: A
Nmap done: 1 IP address (1 host up) scanned in 19.06 seconds
```

Here I found that myserver.com (which is my testing server) accepts only TLSv1.2 connections only 

Upon further debugging , I came to know that jodd-http creates by default 'TLSv1.1' connection. 
hence changed my code to honor SocketHttpConnectionProvider & passing supported 'TLSv1.2' exclusively while creating HttpRequest . Below is code snippet

```
SocketHttpConnectionProvider socketHttpConProvider = new SocketHttpConnectionProvider();
socketHttpConProvider.setSslProtocol("TLSv1.2");
    
HttpRequest httpRequest = HttpRequest.post(service).withConnectionProvider(socketHttpConProvider);
HttpResponse httpResponse = httpRequest.send();
```

Once I used SocketHttpConnectionProvider & setSslProtocol to 'TLSv1.2' , using this in Httprequest solved SSLHandshakeException
