### ISSUE TITLE
jodd.util.ClassUtil - WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by xingxiuyi** [oblac/jodd#714]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jodd.util.ClassUtil (file:/Users/testuser/.gradle/caches/modules-2/files-2.1/org.jodd/jodd-core/5.0.13/a7ecea06b18bfa5bae2c860cee057d231efa2a75/jodd-core-5.0.13.jar) to method java.util.LinkedHashMap.newNode(int,java.lang.Object,java.lang.Object,java.util.HashMap$Node)
WARNING: Please consider reporting this to the maintainers of jodd.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

openjdk version "11.0.2" 2019-01-15

**Comment by igr** [comment]
Hi! Thanx for reporting!

The issue happens because `ClassUtil` probably scans `LinkedHashMap`'s internal methods.

I guess we can just ignore them if the target class is from java packages.

I am not sure when Jodd is going to be migrated to higher Java, but I will try to fix this :)

**Comment by igr** [comment]
See https://github.com/oblac/jodd/issues/747
