### ISSUE TITLE
Please bundle LICENSE/NOTICE files in the produced jar files

### ISSUE THREAD

**Issue by vlsi** [oblac/jodd#717]
It would be nice if you could add LICENSE to `META-INF/LICENSE` , so the license could be automatically discovered.

## Current behavior

jodd jar files contain NO license files, and the license itself (BSD-2-Clause) requires re-distributions to reproduce copyright notice.
It requires manual work to figure out the exact copyright notice for each and every jodd release, thus it makes it hard to update jodd dependencies

## Expected behavior

Relevant (up to date) LICENSE/NOTICE files should be included to `jodd-*.jar/META-INF/` artifacts, so the required "copyright notice" can be reproduced automatically by consumers.

## Steps to Reproduce the Problem

Download jodd-core-5.0.13.jar (e.g. from https://search.maven.org/artifact/org.jodd/jodd-core/5.0.13/jar)
The file contains NO LICENSE/NOTICE files.

**Comment by igr** [comment]
True! Thank you, will do ASAP

**Comment by vlsi** [comment]
Update: `NOTICE` file is optional (you might omit it and it would be just fine provided there are no other requirements to have the file).

Bundling license text with JAR would still help to associate the license with a specific jar in question.

**Comment by vlsi** [comment]
@igr , just letting you know, `jodd-core-5.0.13.jar` and other files do not contain `META-INF/LICENSE` file.

Frankly speaking I did not try to verify if 10b5f5ca9871fac35abaa574142bc113672ea564 worked, however in practice it turned out it did not.
