### ISSUE TITLE
Jodd Mail:  Chinese Charset (e.g. gb2312) txt file attachment garbled

### ISSUE THREAD

**Issue by jawar-cn** [oblac/jodd#723]
## Current behavior

Recieve a mail with chinese charset txt file attachement, and all Chinese Charactors ard garbled
接受一封带有中文编码格式txt附件的邮件,附件中的中文乱码.

**Comment by igr** [comment]
Would you be so kind to save the email content? Usually this is a  problem of sending and not having set the correct encoding. You can use `EMLComposer` for saving received emails.

**Comment by lwu-gd-china** [comment]
@igr   Hey, man. It had the same mistake as issue 725. You can have a look!

@jawar-cn 老外很懒，😄

**Comment by igr** [comment]
This should work:)

**Comment by igr** [comment]
Please see #723 - I added sending of Cyrilic string. Just please check the encodings.
