### ISSUE TITLE
JTX the parameter order in  JtxResource.isSameTypeAsResource(line 49) maybe inverted

### ISSUE THREAD

**Issue by ylyxf** [oblac/jodd#727]
the type of  JtxResource<E>'s E may be an interface 
JtxResource's member "resouece“  getType()  must be a class. 

the logic of line 49  may be:
    ClassUtil.isTypeOf(interface,class)  =>  classType.isAssignableFrom(interface);

will always return flase.

**Comment by igr** [comment]
Please check the test in commit, I am doing it with an interface and it works.

**Comment by igr** [comment]
Please reopen the issue if I am doing something wrong :))) It looks like everything is good.
