### ISSUE TITLE
twitter "joddorg" -> not found anymore

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#733]
Hi,

[twitter page for jodd](https://twitter.com/joddorg) is not available anymore :  

Do you know the reasons?
Any comments possible?

Thx!

Greetz

**Comment by igr** [comment]
Yeah, sorry for that. I need to reboot the Twitter, as I was using it for personal tweets

**Comment by igr** [comment]
@jodd_org is the new one - only for the Jodd-related tweets :)
