### ISSUE TITLE
boo or bar?

### ISSUE THREAD

**Issue by libinjareo** [oblac/jodd#740]
## Current behavior

when i read the document from [https://jodd.org/petite/wiring.html](url),
I am puzzled by a sentence, please help me to explain it:

> Knowing this, in the previous example Petite lookups for the following bean names:

> boo

> boo (ignored as equals to #1)

>  org.jodd.Boo

The previous example in the document, like this:
`  public class Foo {
        @PetiteInject
        Bar bar;
        public void foo() {
            bar.boo();
        }
    }`
so Petite lookups for the following bean names should **bar**  instead of  **boo**?

**Comment by igr** [comment]
Correct! Fixed. To be deployed later today.
