### ISSUE TITLE
Jodd 6 - some decisions and preparation

### ISSUE THREAD

**Issue by igr** [oblac/jodd#742]
Long time no code.

This code base becomes huge and not easy to maintain and publish. Also, documentation is painful to update and maintain. That being said, the following will happens starting with version 6:

+ Work in this repo will be stopped. New repo for each component will be created with _independent_ lifecycle, releases, documentation.
+ Some of the projects will merge. Tools will remain separate. Frameworks will merge. For example, anything used for building webapp will be one project, merged.
+ Not all project will support java8. Tools will remain on Java8. Frameworks will shoot for Java11, GraalVM compatibility and so on.
+ None of the packages will be renamed.
+ The migration will go "lazy" - first will be moved the tools that I know they are used.

Sorry for inconvenience. This way I would give opportunity to libraries to find more usages and help more people and make it easier for ppl to add fixes.

**Comment by moh-sushi** [comment]
"independent lifecycle, releases, documentation"
what about case in issue [634](https://github.com/oblac/jodd/issues/634#issuecomment-420992973)?

**Comment by igr** [comment]
I don't see any other way, to be honest. Need to reduce the number of components. It will be more work now, but later not so many. I am already stuck with big codebase that needs to be published all at once. Instead, I will go with monorepo (so to keep this project) and merge several components together.

**Comment by moh-sushi** [comment]
How is the state / schedula plan of your "ready to work with jodd in new repo" ?
 
Thank you!

**Comment by igr** [comment]
@moh-sushi I will start in february, this is the date: **02.02.2020** :) the new branch will be created.

**Comment by igr** [comment]
Execution started.
