### ISSUE TITLE
jodd-all stuck at 5.1.0

### ISSUE THREAD

**Issue by neroux** [oblac/jodd#751]
jodd-all is stuck at 5.1.0

https://search.maven.org/search?q=a:jodd-all

I assume this is intentional and jodd-all is no longer maintained, right?

**Comment by igr** [comment]
I had issues with migrating to new Gradle... Ended up spending waaaaay too much time hacking Gradle, so I had to cut it off :( It's just - would love to add more docs and java code instead...

I know it's a bummer...

**Comment by neroux** [comment]
I was afraid that was the case :/

Thanks for the clarification, @igr

**Comment by neroux** [comment]
Feel free to close at your discretion :)
