### ISSUE TITLE
wanna add new method ‘getRemoteFileSize’

### ISSUE THREAD

**Issue by MrXionGe** [oblac/jodd#755]
### [new feature]
I want to find a method to get the size of remote files in JODD.
Did not seem to be found.
I wrote a tool.
```
    /**
     * get remote file size.<br>
     * -1 if the content length is not known.
     *
     * @param url remote file url
     * @return file size
     * @throws IOException JDK-IOException
     */
    public static long getRemoteFileSize(String url) throws IOException {
        HttpURLConnection connection = null;
        try {
            connection = (HttpURLConnection) new URL(url).openConnection();
            return connection.getContentLengthLong();
        } finally {
            if (connection != null) {
                connection.disconnect();
            }
        }
    }
```
I hope this method can be added to JODD. But I don’t know where to build.

**Comment by igr** [comment]
Seems like a good match for a `NetUtil`.

Thank you, this is great! Will add it today!

**Comment by MrXionGe** [comment]
I thought about it again. It would be better not to throw Exception.
Users care about file size, not Exception.
If it fails, return -1.
So, 'try-catch'.

**Comment by igr** [comment]
Thank you @MrXionGe!
Just pushed!
