### ISSUE TITLE
optional return types for jodd-json

### ISSUE THREAD

**Issue by xaph** [oblac/jodd#760]
Hello,

do you think about adding optional return types for jodd-json?

Instead of using these nullable return

```java
String test = jsonObject.getString("test");
if(test != null) {
    //do something
}
```
using optional return is more modern way to handle null

```java
Optional<String> test = jsonObject.getOptionalString("test");
if(test.isPresent()) {
    //do something
}
```

what about implement these methods?

**Comment by igr** [comment]
Yeah, Jodd is old :)

I personally prefer `Consumer`, e.g.:

```
json.withStringValue("test", value -> {});
```

but again, I could add `Optional` as well. Just not sure about the method name... `getStringValue` maybe?

**Comment by neroux** [comment]
> more modern

That is not necessarily better and - at least in your example - there is no actual advantage over it. It will only require more memory.

**Comment by igr** [comment]
After some thinking, I believe its better not to migrate anything now. Otherwise, the change should be applied all over the code, and that would break the API.
