### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by marekhudyma** [oblac/jodd#763]
## Current behavior
I got java.lang.IndexOutOfBoundsException while parsing http://cnn.com page:

I use:
```
    <dependency>
      <groupId>org.jodd</groupId>
      <artifactId>jodd-lagarto</artifactId>
      <version>5.1.4</version>
    </dependency>
```
I use Java 11. 

Exception that I have: 
```
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at jodd.util.CharArraySequence.<init>(CharArraySequence.java:69)
	at jodd.util.CharArraySequence.of(CharArraySequence.java:47)
	at jodd.lagarto.Scanner.charSequence(Scanner.java:142)
	at jodd.lagarto.LagartoParser.emitComment(LagartoParser.java:2977)
	at jodd.lagarto.LagartoParser$28.parse(LagartoParser.java:1411)
	at jodd.lagarto.LagartoParser.parse(LagartoParser.java:135)
```

## Expected behavior
No exception.

## Steps to Reproduce the Problem
My code:
```
        LagartoParser lagartoParser = new LagartoParser(html.toString());
        TagVisitorImpl tagVisitor = new TagVisitorImpl();
        lagartoParser.parse(tagVisitor);

        class TagVisitorImpl implements TagVisitor {
        @Override
        public void tag(Tag tag) {
            href = tag.getAttributeValue("href");
            if (href != null) {
                // ... 
            }
        }
```

Here I uploaded file which causes error, so it would be easy to reproduce: 
```
https://www.dropbox.com/s/soqzjz2d7p33soo/0126_cnn.com.html?dl=0
```

**Comment by slandelle** [comment]
This is a bug with Jodd's IE conditional comments support:

```html
<html><head>
<!--[if lte IE 9]><meta http-equiv="refresh" content="1;url=/2.218.0/static/unsupp.html" /><![endif]-->
<!--[if gt IE 9><!--><script>alert("Hello!");</script><!--<![endif]-->
</head>
</html>
```

The first line works fine, the second one crashes with IOOBE.
A possible workaround is to disable IE conditional comments support in Lagarto config.

**Comment by igr** [comment]
Thanx @slandelle for fast detection! It seems that the second line has the syntax error for Conditional Comments, i.e. its missing the `]`. I guess that in this case this is _not_ a conditional comment, but regular one. Jodd should 'roll back' the conditional condition parsing and go with comment (just need to verify what happens in browser).

**Comment by slandelle** [comment]
Let me check if I didn’t introduce a typo when simplifying cnn.com HTML content.

**Comment by igr** [comment]
I checked the code, you didnt make mistake

**Comment by igr** [comment]
if I assume that `[if gt IE 9>` is a regular comment, should Jodd emit _conditional comment_ on `endif` or regular comment?

**Comment by slandelle** [comment]
Regular comment IMHO

**Comment by slandelle** [comment]
Thanks mate!

**Comment by igr** [comment]
Releasing new version @slandelle atm :)

**Comment by vlsi** [comment]
The fix breaks nested conditional comment processing:

```html
<HTML>
<head>
<!--[if gt IE 6]>
    <!--[if lte IE 8]>
        <!--[if IE 7]>
            <link rel="stylesheet" type="text/css" href="fileForIE7.css">
        <![endif]-->
        <link rel="stylesheet" type="text/css" href="fileForIE7or8.css">
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="fileForIE7or8or9.css">
<![endif]-->
</head>
```

For IE 9, it should resolve to `fileForIE7or8or9.css`, however, currently jodd uses a single `conditionalCommentStarted` field which resets to `false` on the first `<![endif]-->`, so jodd no longer emits `condComment`, so the clients can't get the parsing right.
