### ISSUE TITLE
envelopeOnly() results in lots of fetching compared to folder.search

### ISSUE THREAD

**Issue by maxandersen** [oblac/jodd#767]
## Current behavior

when doing:

`var mails = session.receive().filter(
                EmailFilter.filter().flag(Flag.SEEN, false))
                .envelopeOnly()
                .get();`

the amount of data fetched is much larger than when doing:

``` 
f.open(javax.mail.Folder.READ_ONLY);

var messages = f.search(EmailFilter.filter().flag(Flag.SEEN, false).getSearchTerm());
```

## Expected behavior

there should be a way to fetch just the minimum data to make initial searches faster.

...i'm wondering if jodd email assumes you will always be interested in all data ?

**Comment by igr** [comment]
Speaking out loud w/o looking at the code, Jodd email _should_ not perform any additional logic to underlying `mail` library. I will check whats going on.

How did you measure the amount of data?

**Comment by igr** [comment]
As said, Jodd is just passing the flag to the implementation:

https://github.com/oblac/jodd/blob/723bba35881d0f9fb9b2c28821dcded976ae70ab/jodd-mail/src/main/java/jodd/mail/ReceiverBuilder.java#L121
