### ISSUE TITLE
Can you integrate Swagger Doc like Spring frame?

### ISSUE THREAD

**Issue by Mr-Hongan** [oblac/jodd#774]
## Current behavior

Not sure how to integrate Swagger Doc

## Expected behavior

You can tell us how to integrate,thanks

**Comment by igr** [comment]
You might start with listing Madvoc components, like here:

https://github.com/oblac/jodd/blob/master/jodd-joy/src/main/java/jodd/joy/JoyMadvoc.java#L175

And then you can add your custom annotations and code.

Sorry for not having this in Madvoc (https://github.com/oblac/jodd#%EF%B8%8F-the-future-and-versions)
