### ISSUE TITLE
InterfaceImplementation.java ClassCastException  when interface return primitive type but not number

### ISSUE THREAD

**Issue by tanliyuan** [oblac/jodd#777]
![image](https://user-images.githubusercontent.com/8876684/103333304-7d2d1600-4aa8-11eb-971d-2a7df19d513f.png)

 exception caused by type conversion when interface return primitive type not number

return default value for primitive types  
boolean -> false
int -> 0

**Comment by igr** [comment]
Thank you! Fixed!
