### ISSUE TITLE
Required OSGi headers missing

### ISSUE THREAD

**Issue by oliverlietz** [oblac/jodd#779]
Starting from `5.1.0` several required OSGi headers are missing from `MANIFEST.MF`, e.g. `Bundle-SymbolicName`, `Import-Package` and `Export-Package`:
![jodd-core-manifest](https://user-images.githubusercontent.com/441166/106398450-21410e80-6413-11eb-8926-ee40308adbdc.png)
This prevents successful deployment of Jodd bundles in OSGi runtimes.

**Comment by igr** [comment]
True that; I remember I had some issues with the plugin.

Which Jodd libraries are you using? Just to prioritize my work.

**Comment by oliverlietz** [comment]
I guess it's the same issue for all Jodd bundles and it needs to be fixed only once (for all).
I'm trying to deploy [Redisson](https://github.com/redisson/redisson) which has a transitive dependency on `jodd-bean`.

**Comment by igr** [comment]
Added for all Jodd v6.x libs :)
