### ISSUE TITLE
IDEA: Provide PathMacros in util module

### ISSUE THREAD

**Issue by zqq90** [oblac/jodd#780]
## Current behavior

`PathMacros` is provided in madvoc module, as a internal util 

## Expected behavior

+ provide `PathMacros` in util module
+ combined with `StringTemplateParser`, do `parse()` also do `format()`
+ can be used in two ways like `DateTimeFormatter`: `ofPattern(...)` or `DateTimeFormatterBuilder`

**Comment by igr** [comment]
Added `StringTemplateMatcher` :)
